### ISSUE TITLE
Static Translations

### ISSUE THREAD

**Issue by gisu** [engram-design/SuperTable#101]
I currently translate the customer backend into several languages for the editors. With the regular fields the translation of the names and instructions works, quite well. Only if it is a supertable field, the texts remain in the source language. Is there a trick to translate these texts?

**Comment by engram-design** [comment]
Thanks for reporting this - its now fixed in the [latest master](https://github.com/engram-design/SuperTable/archive/master.zip), and will be rolled into the next release.
