### ISSUE TITLE
Locale content being overwritten by default language content 

### ISSUE THREAD

**Issue by miromo** [engram-design/SuperTable#102]
I have a multilingual site (Spanish, English and French). It has a matrix field with a block type that contains a nested supertable field. One of the fields in the supertable field is an asset (image) which is set to not translatable. My client entered all the other supertable fields in all 3 languages, before they had images ready. Now they've gone back to add images and when they add a single Image within one supertable row, all of the copy fields get overwritten with the English version-across all rows in the field. I might have changed the asset field from translatable to not translatable after the initial content was entered (can't remember for sure), but still, this shouldn't be happening after the initial save, should it? Is there a way to turn off the copying of default language content altogether?
![screen shot 2017-02-17 at 9 03 19 pm](https://cloud.githubusercontent.com/assets/25856363/23089291/9d96feb8-f554-11e6-9da1-49ccb3086be8.png)

**Comment by engram-design** [comment]
I believe thats default behaviour for any field thats set to non-translatable. See http://craftcms.stackexchange.com/questions/2191/how-to-only-show-translated-fields-in-an-additional-locale

I'd need a bit more information anyway - what fields are set to translatable? The Matrix, Super Table and inner fields?

Also refer to https://github.com/engram-design/SuperTable/issues/22#issuecomment-243111646

**Comment by miromo** [comment]
See picture above, but to fill in the blanks: Matrix field that contains "Feature Tiles": non translatable. "Tiles" is a supertable field: non-translatable (per the picture above). "Image" within the supertable: non translatable. All other fields alongside the Image field, ARE translatable. 

The client creates content for this field (Chooses the Matrix Block: Feature Tiles and adds many Tiles (Supertable) with all their translations (Copy, Feature Heading etc) but does not add an image and saves the page. Then, later they come back and add the image and all of the spanish and french fields for copy and heading etc are being overwritten with English copy. Is this what you're saying is default behaviour?

(I read case 22 but I'm having trouble relating it to this)

**Comment by engram-design** [comment]
Thanks for the clarification, but having some issues replicating things. Can you have a look at the video below and confirm if there's anything I'm doing wrong? Note that "Australian English" is the primary Locale, with "US English" being the secondary one.

https://www.dropbox.com/s/oky8ao2txwl5tja/Matrix_ST_Locale.mov?dl=0

**Comment by engram-design** [comment]
Any update on this? Have you had a chance to review that video?

**Comment by miromo** [comment]
I'm sorry I never came back to this. I restored a previous version of the system and compared it. Determined that somebody switched the matrix field from not translatable, to translatable. So, when they edited content and saved it, it saved it as though it was the first time the entry was created and copied the english to the other languages. I owe you one for letting you go to the trouble of trying to replicate it. So, so sorry.

**Comment by engram-design** [comment]
Ah gotcha, glad you got it figured out in the end! Thanks for letting me know, but chime back in if you have further issues.
