### ISSUE TITLE
Craft Requirement is Incorrect

### ISSUE THREAD

**Issue by mikevaux** [engram-design/SuperTable#105]
Hi! Thanks so much for this plugin, it's great! :-)

I was trying to use this to add an update to a site which runs an old version of Craft (2.4.2677) and I had a problem.

`SuperTableFieldType` implements the `IEagerLoadingFieldType` interface, but I think this was only added in [Craft 2.6.2771](https://craftcms.com/changelog#2-6-2771)

I'm going to try using Super Table 0.4.6 for now, which seems to be the latest version which doesn't use Eager Loading (as updating the whole site could add quite a bit of time to the update), but it might be worth you updating the '[Requirements](https://github.com/engram-design/SuperTable#requirements)' section as it currently reads "2.3.2615+"

Thanks!
M

**Comment by engram-design** [comment]
Ah, great point @mikevaux that completely slipped my mind! Too eager (excuse the pun) to support the latest and greatest Craft.

Closing for now, as this has been modified in the read me. Thanks again!
