### ISSUE TITLE
After the update of craft 2.6.2974

### ISSUE THREAD

**Issue by SilverCrowS** [engram-design/SuperTable#106]
Right after my update i wanted to create a new field supertable, but when i click on the new block button nothing happen and for the already existing fields 'supertable' i can't modify or view or do anything is this just me or something happened when i updated craft ?
![image](https://cloud.githubusercontent.com/assets/23082556/25378814/0eec89f2-29a3-11e7-9ec7-dead54111942.png)

**Comment by engram-design** [comment]
Have you tried clearing Craft's caches? Are there any JS errors in the console for your browser?

**Comment by SilverCrowS** [comment]
i did clear the cache and this is what i ve got in my console i don't think is related though, still i have an earlier version of the site on a diffrent domaine the supertable work fine it's just after this update i had the probleme so it's just me not a bug or something?
![image](https://cloud.githubusercontent.com/assets/23082556/25422751/cd438d54-2a59-11e7-8e7f-3a0898133728.png)

**Comment by SilverCrowS** [comment]
i did clear the cache and this is what i ve got in my console i don't think is related though, still i have an earlier version of the site on a diffrent domaine the supertable work fine it's just after this update i had the probleme so it's just me not a bug or something?
![image](https://cloud.githubusercontent.com/assets/23082556/25422790/fe93973c-2a59-11e7-8a28-43ddf345468a.png)

**Comment by engram-design** [comment]
If you have any Javascript errors in the control panel, it may very well cause issues with other plugins. Are you able to disable the SEO plugin and try again?

**Comment by SilverCrowS** [comment]
yep it worked thank you so i have to correct the probleme of this seo things ... still thank you very much !
