### ISSUE TITLE
Feature: Ability to set folder and # of files in Asset fields

### ISSUE THREAD

**Issue by madebyshape** [engram-design/SuperTable#12]

**Comment by engram-design** [comment]
You can alter any fields settings from the Super Table's settings - just click on the settings 'cog' for the table column. See below screenshots to illustrate a working example for Assets.

![screen shot 2015-06-25 at 10 56 40 pm](https://cloud.githubusercontent.com/assets/1221575/8354721/78f3032e-1b8d-11e5-8e6e-941aca5e4bb6.png)
![screen shot 2015-06-25 at 10 57 00 pm](https://cloud.githubusercontent.com/assets/1221575/8354727/8300b8c0-1b8d-11e5-8fea-ebd83848a644.png)

**Comment by madebyshape** [comment]
DOH!

BIG DOH

Didn't see that cog.

**Comment by engram-design** [comment]
Haha - yeah you're the second person to miss that so don't feel too bad :smile: But just quietly, its outlined [here](https://github.com/engram-design/SuperTable#field-settings).

In fact, the settings screen will be getting a big makeover in a later update, as the field has moved past the simplistic table layout for settings. Be on the lookout for some cool drag/drop action!
