### ISSUE TITLE
Static row field validation within an optional field

### ISSUE THREAD

**Issue by timeverts** [engram-design/SuperTable#121]
Please see the attached image for reference purposes.
![static_field_validation_issue](https://user-images.githubusercontent.com/15150632/35719450-8191770a-0824-11e8-8de1-322eb1e29c36.png)

I've created a Super Table field called 'Heading' and set the field to be a *static* field (to only display a single row of fields). The 'Heading' field itself is marked as _not_ required but the fields within the Super Table row are required (i.e. in the example, if you're going to set a value for the heading, then you must specify the text and the alignment). 

However, when attempting to save an entry with this field inside it, Craft is still asking me to enter values for the fields within the static Super Table row, even though the 'Heading' field itself is optional.

I would have thought that if the field containing my static Super Table row is not required, then the Text and Alignment row fields would be smart enough to work out that they are not required in this context either.

My only alternative at this stage is to not make the field a static one.

### Additional info
- Plugin version: 1.0.6
- Craft version: 2.6.3004

**Comment by engram-design** [comment]
I can sort of see where you're coming from here, but conversely, I think this works just like normal field validation would.

For example, if you had a regular Plain Text field called Heading and that was required, you'd need to enter a value before saving the element.

If this was a repeatable Super Table or Matrix, you would first create a new block, after which you'd be required to enter in information.

As such, a static Super Table field's aren't optional, and they act just like regular fields. Even if you save an entry, content is saved for a static Super Table field (just blank values), so in some ways, the field itself is always required and visible.

My question, is why is the Text field marked as required? if I don't add a value into the Text field, the element should save properly, and when I do add content to that Text field - its got content so passes validation.

**Comment by engram-design** [comment]
Closing due to age/Craft 2.
