### ISSUE TITLE
'SortOrder' missing from supertableblocktypes

### ISSUE THREAD

**Issue by icreatestuff** [engram-design/SuperTable#123]
When I try to save a Super Table field I get a Database Exception thrown.

I had a quick look through the plugin migrations but couldn't see any reference to a SortOrder column.

**Exception Error**
```
Database Exception – yii\db\Exception

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sortOrder' in 'field list'

The SQL being executed was: SELECT `id`, `fieldId`, `fieldLayoutId`, `sortOrder`
FROM `supertableblocktypes`
WHERE `fieldId`=163
ORDER BY `sortOrder`
Error Info: Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'sortOrder' in 'field list'
)
↵
Caused by: PDOException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sortOrder' in 'field list'
```

### Steps to reproduce

1. `composer require verbb/super-table`
2. Install through Craft Settings > Plugins
3. Create new SuperTable field and click save

### Additional info

- Plugin version: 2.0
- Craft version: Craft CMS 3.0.0-RC9

**Comment by engram-design** [comment]
@icreatestuff Sorry about this, seems like some leftover code on my end (that shouldn't be there anyway). The latest master should hopefully fix this for you.

**Comment by icreatestuff** [comment]
Thanks @engram-design. I uninstalled and removed the plugin from composer (and re-ran `composer update` to clear it out) before re-installing but I'm getting the same issue. Does packagist need updating?

Or equally is there anything else hanging around related to sortOrder? I did a quick search of the repository and got a few results https://github.com/verbb/super-table/search?utf8=%E2%9C%93&q=sortOrder&type=. I appreciate some were marked as indexed before your last update but I think when compared to the commit (https://github.com/verbb/super-table/commit/600e3d100d32f16d63f1961bff9ee6b0d64aec3a) there could be a couple more spots where sortOrder is still referenced.

Thanks again

**Comment by engram-design** [comment]
@icreatestuff You may need to manually replace the folder, as I haven't pushed a new release (just wanted to check it worked for you first). 

You can either:
- Download the repo and replace the `src` folder
- Run `composer require verbb/super-table:dev-craft-3`.

Additionally, `sortOrder` is required for a `SuperTableBlock` model, just not a `SuperTableBlockType` model, which is why you will still see references to it.
