### ISSUE TITLE
“Add a Category” Button is displayed when it should be disabled

### ISSUE THREAD

**Issue by richhayler** [engram-design/SuperTable#124]
### Description
The button to “add a category” within a superTable field should be disabled or hidden (ideally) when the “limit the number of branches” option for the category field is set to 1 and 1 category has already been added.

### Steps to reproduce

1. Create a new supertable field
2. Add a category field and set branch limit to 1
3. Setup your section to use this new field
4. Create a new entry in the section
5. Add a row for your supertable field
6. Select a category
7. Category select button is still displayed

### Additional info

- Plugin version: v2.0.2
- Craft version: RC9

**Comment by engram-design** [comment]
@richhayler This is actually out of our control, and would be the responsibility of the Categories field (which doesn't seem to do this even when not in a Super Table field). Are you seeing this with a normal Categories field?

**Comment by richhayler** [comment]
You’re absolutely right. Sorry. I just certified it. I created a new section and a single category field with a single branch restriction and the button is still displayed (not disabled) after selecting a category. I’ll log against the CraftCMS GitHub. Thanks.

**Comment by engram-design** [comment]
No worries! And if its means to act the same way as an Assets' `limit` attribute, then the button should disappear when it reaches its limit.
