### ISSUE TITLE
Invalid ContentBehavior.php

### ISSUE THREAD

**Issue by KevinBeckers** [engram-design/SuperTable#125]
### Description

Saving a supertable field adds following to "/storage/runtime/compiled_classes/ContentBehavior.php"

```

    /**
     * @var mixed Value for field with the handle “”.
     */
    public $;

```

### Steps to reproduce

1. Save super table field

### Additional info

- Plugin version: 2.0.2
- Craft version: Craft Pro 3.0.0-RC9

**Comment by engram-design** [comment]
Have you deleted the `storage` folder and cleared the caches?

**Comment by KevinBeckers** [comment]
Yes, doesn't work. Manually editing the ContentBehavior.php does. Just remove the public $;
But you need to do it every time you saved the supertable field.

**Comment by engram-design** [comment]
I'm not familiar with ContentBehavior.php at all. Seems like it is stores a cache of your fields?

In any case, the error seems to point the field handle not being set for some reason. How many Super Table fields do you have? Was this an upgrade from Craft 2?

**Comment by KevinBeckers** [comment]
Didn't have to deal with the ContentBehavior ether. I have only one supertable on a fresh Craft 3 installation. 

I am using this table inside a general.

**Comment by engram-design** [comment]
@KevinBeckers Very odd. Don't support you're on the Craft Slack? I'd be interested to see if I could grab your database just to see what's going on, as it's not something I can replicate here...

**Comment by engram-design** [comment]
Issue resolved, and fixed due to proper lack of field validation. Rolling into the next release.
