### ISSUE TITLE
Error loading entries after migration of multi language Craft 2 site

### ISSUE THREAD

**Issue by florentineprinzessinzusachsen** [engram-design/SuperTable#127]
### Description
Maybe related to #126

When migrating a multi language craft installation containing multiple Super Table blocks (from 2.6.3008) migration **m160807_144858_sites** adds a **locale__siteId** column to each supertablecontent_* table. The code is located at m160807_144858_sites.php, line 324. 

As far as I understand though, Super Tables is looking for a **siteId** column when looking up blocks.

Thus the following error is being thrown when loading an existing entry containing a Super Table into the editor:
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'content.siteId' in 'where clause'`

I don't exactly understand what the correct behavior would be, so I'm just leaving this here. I'm happy to help/test if I can.

I can upload a database dump for a test installation.

### Steps to reproduce
1. create a matrix field in a Craft 2.6.3008 installation containing at least two locales
2. create a Super Table in that matrix field
3. add matrix field to an entry type in a section with at least two locales activated
3. create at least one field in that Super Table and set translatable
4. create an entry containing that matrix field in whichever locale you wish
5. copy database to empty Craft 3, RC10 installation
6. run migration
7. try opening said entry in admin, editor

### Additional info
- Plugin version: 2.0.3
- Craft version: 3.0.0-RC10

**Comment by engram-design** [comment]
This should be fixed in the [2.0.4 release](https://github.com/verbb/super-table/releases/tag/2.0.4).
