### ISSUE TITLE
Button margin issue

### ISSUE THREAD

**Issue by lukeyouell** [engram-design/SuperTable#132]
### Description

It looks like when using matrix fields the button has a `margin-top` which leads to a slightly disjointed layout.

<img width="162" alt="image" src="https://user-images.githubusercontent.com/24975058/37144554-52b64a3a-22b6-11e8-9203-cfad7d580074.png">

### Additional info

- Plugin version: 2.0.4
- Craft version: 3.0.0RC-14

**Comment by engram-design** [comment]
Fixed in the latest code (update via `composer require verbb/super-table:dev-craft-3`) and will be rolled into the next release shortly.
