### ISSUE TITLE
Neo migration tool

### ISSUE THREAD

**Issue by devinellis** [engram-design/SuperTable#133]
At Moz we're very interested in moving from Neo to SuperTable. Are there any tips for automating the migration process? If we were to try and tackle writing a migration tool, do you have any insight on what we should try? I was thinking something in conjunction with the Element API…

cc @caseycoates

**Comment by engram-design** [comment]
Hey @devinellis There aren't any plans to provide a tool for this built into Super Table, and I've not had the chance to dive into the internals of Neo, but the two aren't extremely different.

First of all, you'll want to convert the actual field setup. Neo uses existing fields, so you'll need to create every field for existing blocks and Super Table contexted ones (like Matrix).

Now that just goes for the actual fields. Content is a little trickier, as Neo will store field content in the `craft_content` table, whereas Super Table will require it to be stored in its own table. There's probably no real easy way to do this manually as it involved creating Super Table Block elements, block types (only one). 

I would recommend using something like Element API and Feed Me to create and consume a feed of content and import it into Craft, respectively. You can easily create a JSON feed via Twig as well if you don't want to use the Element API plugin. Once you've created a 'feed' of entries you can use Feed Me to map those values to Super Table fields, and update your entries.

Hope that helps a little bit!

**Comment by devinellis** [comment]
Last week we migrated moz.com from Neo to SuperTable. We built a plugin off of the Neo->Matrix functionality in Neo, it will use SuperTable for one level of nesting. We don't have time to put any more work into it now that we've moved off Neo, but feel free to use it however you like: https://github.com/blasvicco/NeoToMatrixExportPlusPlugin

**Comment by engram-design** [comment]
@devinellis This looks great, and will certainly dive into it.

**Comment by engram-design** [comment]
While @devinellis work is great on this, not looking to add Neo migration support, instead focusing on a Craft 4 Matrix migration path as a priority.
