### ISSUE TITLE
Craft 3 Can't Save Asset Field From Front-end Matrix > Super Table

### ISSUE THREAD

**Issue by theskyfloor** [engram-design/SuperTable#135]
### Description

I can't get assets to save from the front-end when SuperTable is wrapped in a Matrix block.

### Steps to reproduce

1. Create a Matrix with a sub field of a SuperTable including an Asset field
2. Attempt to upload an asset

### Additional info

- Plugin version: Latest
- Craft version: 3 RC14

```
<form method="post" enctype="multipart/form-data">
  {{ csrfInput() }}
  <input type="hidden" name="action" value="globals/save-content">
  <input type="hidden" name="setId" value="127"> 

    <input type="hidden" name="fields[simpleMatrixSt][new1][type]" value="images">{# the matrix block type #}

    <input type="hidden" name="fields[simpleMatrixSt][new1][fields][images]" value="">{# the matrix block field #}

    <input type="hidden" name="fields[simpleMatrixSt][new1][fields][images][new1][type]" value="8">{# the super table type #}

  <input type="file" name="fields[simpleMatrixSt][new1][fields][images][new1][fields][image]" value="">{# the super table field #}
  <input type="hidden" name="fields[simpleMatrixSt][new1][fields][images][new1][fields][image]" value="">

  <input type="submit" value="Save Global" />
</form>
```

**Comment by theskyfloor** [comment]
I also did a test with just a SuperTable field and I can't get front-end asset uploads to work from there either... so it seems to be an actual issue with SuperTable since it works just fine in a Matrix with similar syntax. Any help would be appreciated : )

```
<form method="post" enctype="multipart/form-data">
  {{ csrfInput() }}
  <input type="hidden" name="action" value="globals/save-content">
  <input type="hidden" name="setId" value="127"> 

    <input type="hidden" name="fields[supertableAsset][new1][type]" value="9">{# the super table type #}

    <input type="hidden" name="fields[supertableAsset][new1][fields][image]" value="">
  <input type="file" name="fields[supertableAsset][new1][fields][image]" value="">{# the super table field #}
  
  

  <input type="submit" value="Save Global" />
</form>
```

**Comment by theskyfloor** [comment]
Just trying to be thorough. If I bury an asset field inside of Matrix > ST > Matrix the image still won't upload. So 100% involving ST seems to be causing the issue. If I just use a Matrix field with no ST then the image uploads perfectly.

**Comment by engram-design** [comment]
Can you give the latest code a go via `composer require verbb/super-table:dev-craft-3` just to confirm all works?

**Comment by theskyfloor** [comment]
We have success! Was just able to successfully upload. Thanks for the speedy response.

**Comment by engram-design** [comment]
Awesome, will roll into the next release shortly.
