### ISSUE TITLE
Field names are not translated

### ISSUE THREAD

**Issue by mmikkel** [engram-design/SuperTable#136]
### Description
Field names appear to not be translated. I think the issue is that SuperTable uses the wrong translation category handle, e.g. [here](https://github.com/verbb/super-table/blob/craft-3/src/templates/row/fields.html#L9) (should be `'site'`).

### Steps to reproduce

1. Create a static SuperTable field w/ row layout
2. Add some fields
3. Translate the field names in `translations/{locale}/site.php`
4. Confirm that the field names are not translated for the SuperTable input

See http://cly.mmikkel.no/1B1u2M2L1h0w for an example ("Heading", "Price" and "Services" are all translated in `site.php`, but do not appear translated for this SuperTable input).

### Additional info

- Plugin version: 2.0.4
- Craft version: 3.0.0-RC14

**Comment by engram-design** [comment]
Fixed in the latest code (update via `composer require verbb/super-table:dev-craft-3`) and will be rolled into the next release shortly.
