### ISSUE TITLE
Deprecation error: Fields' isEmpty() method has been deprecated. Use isValueEmpty() instead.

### ISSUE THREAD

**Issue by robzor** [engram-design/SuperTable#138]
### Description
I'm using a Super Table inside a Matrix so unsure if that's causing this deprecation error that I got today.

> Fields’ isEmpty() method has been deprecated. Use isValueEmpty() instead.

Stack Trace info:

```
Deprecation error: Fields’ isEmpty() method has been deprecated. Use isValueEmpty() instead. Called from /vendor/craftcms/cms/src/base/Field.php:315
-- | --
verbb\supertable\fields\SuperTableField::isValueEmpty(verbb\supertable\elements\db\SuperTableBlockQuery, craft\elements\MatrixBlock) Called from /vendor/craftcms/cms/src/base/Element.php:1037
```

### Additional info

- Plugin version: Super Table 2.0.4
- Craft version: RC15

**Comment by robzor** [comment]
I think this isn't a Super Table issue and perhaps a Craft issue. Sorry!

**Comment by engram-design** [comment]
This is actually a Super Table responsibility, but was only deprecated in RC15. This was implemented in https://github.com/verbb/super-table/commit/ca50279ea8be374b0f873063141d1c595ab5c4f2 and will be rolled into the next release.

**Comment by robzor** [comment]
Ah cool. Thanks!
