### ISSUE TITLE
Able to save column handle with hyphen

### ISSUE THREAD

**Issue by hudakdidit** [engram-design/SuperTable#14]
Hi, Lovin this plugin! Thanks so much for all the effort behind it.

I encountered an error when saving fields a few times which seems to be due to hyphens included in the column handle. It might save others some confusion if the plugin validated the column handle value before saving. I could attempt a pull request if you have time to point me in the right direction.

Thanks!

**Comment by engram-design** [comment]
@hudakdidit It should validate all field handles before saving through [validate()](https://github.com/engram-design/SuperTable/blob/master/supertable/fieldtypes/SuperTableFieldType.php#L302). Is your field inside a Matrix per chance? I've been notified that fields don't properly validate if they are inside a Matrix.

**Comment by hudakdidit** [comment]
@engram-design Ah, yes it is within a Matrix. No wonder

**Comment by engram-design** [comment]
That explains it! :smile: it's in the top of the todo list to fix!

**Comment by hudakdidit** [comment]
I'll close this as it seems its already in the works. Thanks for getting back!
