### ISSUE TITLE
Can't delete rows in Table layout

### ISSUE THREAD

**Issue by daltonrooney** [engram-design/SuperTable#143]
### Description
I can add rows to a SuperTable field, but can't delete them if the field is set to Table layout. It works as expected in Row layout.

No javascript console errors that I can see.

### Steps to reproduce

1. Create a new Super Table field with a single 'plain text' subfield. Add to a section entry type.
2. Populate the field in an entry with a few rows
3. Try to delete a row... can't

### Additional info

- Plugin version: 2.0.4
- Craft version: 3.0.0.2

**Comment by engram-design** [comment]
This has been fixed in [2.0.5](https://github.com/verbb/super-table/releases/tag/2.0.5).
