### ISSUE TITLE
Can't delete rows from SuperTable that is in a Matrix 

### ISSUE THREAD

**Issue by dgrigg** [engram-design/SuperTable#144]
### Description
I have a Supertable field that existing in a Matrix block. The row can not be deleted after adding.

### Steps to reproduce

1. Create a Matrix block with a Supertable field
2. Create a new entry using the Matrix field
3. Add a block with the Supertable field
4. Add a row to the Supertable field
5. Try to delete the row

### Additional info

- Plugin version: 2.0.4
- Craft version: 3.0.1

**Comment by engram-design** [comment]
This was just fixed in [2.0.5](https://github.com/verbb/super-table/releases/tag/2.0.5)

https://github.com/verbb/super-table/issues/143
