### ISSUE TITLE
Supertable Matrix fields data randomly deleted 

### ISSUE THREAD

**Issue by mark-chief** [engram-design/SuperTable#145]
### Description
I populated  a load of content earlier in a Matrix > Supertable > Matrix setup, across multiple pages. I thought I was going mad when i went back later to see that **ALL** content within the Matrix > SuperTable > Matrix fields had disappeared, on all pages, across the entire site.

### Steps to reproduce

1. None yet...
2. reluctant to add all the content again in case it happens again so will keep an eye on a few fields.

### Additional info

- Plugin version: 2.0.5
- Craft version: 3.0.1

**Comment by engram-design** [comment]
Sorry to hear that. Any indication of what you've done between adding the content and now? Updating Craft (which version to version), anything to do with sites, field changes, etc?

**Comment by mark-chief** [comment]
Howdy, I have only been switching between Section, Entries, and Fields adding content. I've tried to replicate it by adding new matrix blocks to the field and then deleting, refreshing etc.. I'll keep trying. Any idea if this thing would be in the logs? If so happy to take a look if you have any pointers.

**Comment by engram-design** [comment]
Difficult to say, but doubtful there'd be any logs. Worth checking out in `storage/runtime/logs`. How many Matrix > Super Table > Matrix fields were you creating? Any with the same handles (same Super Table handles, or either Matrix's)? Are these also across different sections?

**Comment by lukeyouell** [comment]
@mark-chief could your issue be related to #191?

**Comment by brandonkelly** [comment]
Most likely this is a result of craftcms/cms#3249, where multiple Matrix fields with the same handle would share the same content table (`matrixcontent_<FieldHandle>`). That has been fixed for this week’s Craft release.

@mark-chief if you’d like to test the fix early, open `composer.json` and change your `craftcms/cms` version requirement to `"dev-develop as 3.0.22"`, and then run `composer update` from your terminal. (Make sure to make a backup first.)

**Comment by brandonkelly** [comment]
@engram-design considering how similar Super Table is to Matrix under the hood, there’s a pretty good chance ST has the same bug. The fix should be pretty similar, too (craftcms/cms@ed44fc15b94db27ef298d2555007af23aad3a57c).

**Comment by engram-design** [comment]
@brandonkelly Thanks for your feedback here, I'll check these changes out shortly, run some tests and see where we get to

**Comment by EFWall** [comment]
@brandonkelly we have a pretty complex field structure with lots of super tables and matrix fields. I looked through and found two sets of matrix fields that have the same handle. We have not run the latest update yet. When we run the CraftCMS update with the fix, will it correct these issues on already-existing matrix fields with the same handle?

**Comment by brandonkelly** [comment]
@EFWall yep; some of your Matrix fields will get new content tables that end in `_1`, etc.

**Comment by EFWall** [comment]
@brandonkelly awesome, thank you!

**Comment by engram-design** [comment]
@EFWall As @brandonkelly has mentioned, I believe this was an issue with Matrix (as the top-level owner of your field), but its hardly its fault - it wasn't designed to be nested!

The fix to Craft should solve this and the similar issue for Matrix fields - we'll be making a similar fix for Super Table itself.

**Comment by EFWall** [comment]
@engram-design are you saying that SuperTable has a similar issue where two SuperTable fields with the same handle will share a table and this may cause issues down the line? I believe we do have multiple supertable fields with the same handle, but I looked in the database and I thought all of the tables were unique (supertable seems to add a number into the table name to keep them unique) so I thought we were ok in this regard. Are you saying there is still an issue? Anything we need to watch out for here while we are waiting for your fix?

**Comment by engram-design** [comment]
@EFWall So firstly, Its not possible to have two Super Table fields with the same handle - just like you can't have two fields with the same handle.

However, there's a special case when a Super Table field is nested within a Matrix field. Fortunately, as you've mentioned, we already take care of this by prefixing the content table with the ID of the matrix field, so its unique.

So please disregard my previous comment, I think we're all good.
