### ISSUE TITLE
Responsive Static Field

### ISSUE THREAD

**Issue by kragit** [engram-design/SuperTable#147]
### Description
The "Static Field" option is not responsive (particularly when in live preview on smaller screens), so the contents of some of the columns can overflow over or under other columns. Illustrated with Rias500/craft-position-fieldtype/issues/11 and supercool/buttonbox/issues/17.

![screen shot 2018-04-09 at 3 23 24 pm](https://user-images.githubusercontent.com/296050/38518089-ff9303c6-3c09-11e8-9848-338fc79a6670.png)

### Steps to reproduce

1. Create a Super Table Field
2. Populate with fields that aren't responsive by default (nativley the Dropdown field falls victim to this with long labels, but the above plugins, Position Fieldtype and Button Box do as well).
3. Shrink the entry screen (ie Live Preview)

### Additional info

- Plugin version: 2.0.5
- Craft version: Craft 3.0.1

### Thoughts on a solution
An option to set a breakpoint where the columns would be responsive (where they would collapse under each other) would potentially be the most flexible, if possible.

**Comment by engram-design** [comment]
Very likely not going to happen (sorry), as we push towards a native Craft 4 solution.
