### ISSUE TITLE
Matrix embedded in SuperTable not fully working with Sites

### ISSUE THREAD

**Issue by narration-sd** [engram-design/SuperTable#148]
### Description

This is best described by the original bug and @brandonkelly's fix for Matrix itself, which likely suggests what needs to happen for SuperTable: https://github.com/craftcms/cms/issues/2683#event-1564762472

The problem is that when using Sites, if an Entry section enables only the default site, then it can be added to a Matrix entry which does enable Sites, but then won't actually be saved when you save the Entry.

This was true in general for Matrix, but that is now fixed. The problem continues, however, with Matrix embedded in SuperTable, and that's this issue.

### Steps to reproduce

1. per https://github.com/craftcms/cms/issues/2683#event-1564762472
2.

### Additional info

- Plugin version: 2.0.5 apparently; via current Composer  update
- Craft version: very latest dev-develop Craft 3.0.1 -- commits are listed in the link

**Comment by engram-design** [comment]
Added in [2.0.6](https://github.com/verbb/super-table/releases/tag/2.0.6).
