### ISSUE TITLE
Matrix in Super Table does not appear in Live Preview

### ISSUE THREAD

**Issue by xavianaxw** [engram-design/SuperTable#149]
### Description

I've a Matrix within the Super Table field that allows me to add
- Heading (Text)
- Wysiwyg (Redactor)
- Card (Entry)

While I am able to view the Heading in the Live Preview, the Wysiwyg and Card fails to appear. This is not the case on the website itself. I noticed that it was mentioned on https://github.com/verbb/super-table/issues/117

### Steps to reproduce

Not sure how to reproduce, but here is the code snippet of mine when rendering the page.

```
{% for section in entry.sections.all() %}
    {% for content in section.body.all() %}
        {{ content.type }}
    {% endfor %}
{% endfor %}
```

It only prints out Heading

### Additional info

- Plugin version: 2.0.5
- Craft version: 3.0.1

**Comment by engram-design** [comment]
Strange, I can't seem to replicate this, see the attached screenshot for a working example.
```
{% for row in entry.superTableMatrixTest.all() %}
    {% for block in row.matrix.all() %}
        {{ block.type }}
    {% endfor %}
{% endfor %}
```

![screen shot 2018-04-24 at 11 07 13 am](https://user-images.githubusercontent.com/1221575/39160632-b0ebd192-47af-11e8-9173-b1030724180c.png)

**Comment by xavianaxw** [comment]
Is `sections` perhaps like a reserved word that throws off Super Table. Happened to me on Hubspot before on a separate occasion.

**Comment by engram-design** [comment]
Doesn't seem to be, and switched all the field handles to match your just to be double sure. Still an ongoing issue though?

**Comment by xavianaxw** [comment]
Yeah just tested and still the same.

**Comment by xavianaxw** [comment]
Also, when I update the headings, it doesn't seem to even update my Live Preview. It notices the change and did a soft flicker refresh but doesn't change anything on the Live Preview

**Comment by engram-design** [comment]
Is is a brand new entry, with no other blocks set?

**Comment by xavianaxw** [comment]
I tried with a brand new entry with no blocks set and is still the same? What version of craft are you on? (if it makes a difference)

**Comment by engram-design** [comment]
Yeah just trying to check all possibilities, just on Craft CMS 3.0.2

**Comment by xavianaxw** [comment]
![screen shot 2018-04-24 at 11 57 45 am](https://user-images.githubusercontent.com/8082158/39162027-d441e77e-47b6-11e8-9db5-5f14e0a1a310.png)

![screen shot 2018-04-24 at 11 58 04 am](https://user-images.githubusercontent.com/8082158/39162026-d3ee871e-47b6-11e8-9426-dd8e95f7e126.png)

Here are my configuration

**Comment by engram-design** [comment]
Well, short of a full database dump from you, thinking I'm going to struggle - tried just about every conceivable way to reproduce this!

You're more than welcome to sent through your database (@crawf on Slack) if you'd like to help, but can also understand if you're unable to share.

**Comment by xavianaxw** [comment]
Do I have to be on your channel or something? @engram-design

**Comment by engram-design** [comment]
@xavianaxw Just on the Craft Slack (if you're on there)?

**Comment by engram-design** [comment]
Likely related: https://github.com/craftcms/cms/issues/2801

**Comment by xavianaxw** [comment]
Thanks for looking into this @engram-design :)

**Comment by xavianaxw** [comment]
Hey @engram-design manage to solve this on my end. Thanks again mate!
