### ISSUE TITLE
Calling unknown method

### ISSUE THREAD

**Issue by worshiplive** [engram-design/SuperTable#150]
### Description
Under Craft 3 I have an error thrown when using  {% set reverseRelatedTable = craft.supertable.getRelatedElements({

I get Calling unknown method: craft\web\twig\variables\CraftVariable::supertable() when trying render my template.

### Steps to reproduce

1. Create field with Super Table, 3 fields -> 2 Categories and one Table field.
2. Use craft.supertable.getRelatedElements in template.

### Additional info

- Plugin version: 2.0.5
- Craft version: 3.0.2

**Comment by worshiplive** [comment]
I also uninstalled via composer and re-installed with the same result.

**Comment by engram-design** [comment]
`getRelatedElements` has been removed temporarily, which is the cause of the issue. We'll re0implement it shortly.

**Comment by engram-design** [comment]
Added in [2.0.6](https://github.com/verbb/super-table/releases/tag/2.0.6).
