### ISSUE TITLE
siteId error when migrating from Craft 2 to Craft 3

### ISSUE THREAD

**Issue by jsunsawyer** [engram-design/SuperTable#151]
### Description
We’re getting the error `Syntax error or access violation: 1072 Key column 'siteId' doesn't exist in table`. The table seems to have a "locale" column and not a "siteId" column.

### Steps to reproduce

1. Upgrade from Craft 2 to Craft 3
2. Install Super Table

### Additional info

- Plugin version: 2.0.5
- Craft version: 3.0.3.1

**Comment by engram-design** [comment]
I've seen this issue on another occasion, and has to do with your foreign keys not being setup properly, and is strictly an issue when upgrading your site from Craft 2 to Craft 3.

Have you tried running https://github.com/pixelandtonic/craft-fixfks on your Craft 2 site? It won't fix Super Table fields, but using https://github.com/engram-design/craft-fixfks/blob/master/fixfks.php in the same manner will fix things before you migrate to Craft 3.

**Comment by jsunsawyer** [comment]
Thanks! I think you worked through this with my co-worker. Was definitely a foreign keys issue that the normal fixfks plugin wouldn't resolve.

**Comment by jsunsawyer** [comment]
@engram-design I'm trying to upgrade another old Craft 2 site (Currently on 2.7.10)  and I seem to be having these same issues again. Unfortunately,  I can't seem to get craft-fixfks or your custom fixfks scripts to run. Do you know if these are still valid tools for fixing Craft 2 > 3 migration issues?

**Comment by engram-design** [comment]
@jsunsawyer Happy to chat through it if you're on Discord (handle `crawf`), as it might be easier to see if I can get a bit more 'hands on' with this, as if its the same issue as previous, it might be a bit complicated to restore the foreign keys.

**Comment by jsunsawyer** [comment]
@engram-design Just wanted to follow up with you. I ended up taking another stab at this Craft 3 upgrade. It looks like you've made some improvements to the migration process. All seems to have went well so far!

**Comment by engram-design** [comment]
Thanks for the follow-up @jsunsawyer and good to hear
