### ISSUE TITLE
Information tool-tip freezes browser window

### ISSUE THREAD

**Issue by baileydoestech** [engram-design/SuperTable#152]
### Description
When adding in a description for a field, Super Table exposes this as a tool-tip icon as shown below:

![image](https://user-images.githubusercontent.com/3185073/39315247-2320cdde-496e-11e8-8dc2-504f5b40bd58.png)

However, after selecting the tool-tip this seems to freeze the browser window and can only be recovered by refreshing the page. 

### Steps to reproduce

1. Create a Super Table field with the instructions for a given field populated with text
2. Add the new field to a section in Craft
3. Select the 'i' to display instructions, the browser window will become unresponsive.

### Additional info

- Plugin version: 2.0.6
- Craft version: 3.0.4

**Comment by engram-design** [comment]
What browser/OS are you using? Certainly not seeing that on Chrome/Mac

**Comment by baileydoestech** [comment]
Latest build of Chrome on Windows machine, works fine on IE - actually seems to be a Craft 3 issue
