### ISSUE TITLE
Invalid field handle: dropdownItem

### ISSUE THREAD

**Issue by KatieMFritz** [engram-design/SuperTable#153]
### Description
Can't save entry with content in new SuperTable field. Getting error `invalid field handle: dropdownItem`. I don't think I have any field with the handle dropdownItem. 

```
yii\base\Exception: Invalid field handle: dropdownItem in C:\wamp64\www\safs-effs\vendor\craftcms\cms\src\base\Element.php:1900
Stack trace:
#0 C:\wamp64\www\safs-effs\vendor\craftcms\cms\src\base\Element.php(1580): craft\base\Element->normalizeFieldValue('dropdownItem')
#1 C:\wamp64\www\safs-effs\vendor\verbb\super-table\src\fields\SuperTableField.php(572): craft\base\Element->getFieldValue('dropdownItem')
#2 C:\wamp64\www\safs-effs\vendor\craftcms\cms\src\services\Content.php(236): verbb\supertable\fields\SuperTableField->getSearchKeywords(Object(verbb\supertable\elements\db\SuperTableBlockQuery), Object(craft\elements\Entry))
#3 C:\wamp64\www\safs-effs\vendor\craftcms\cms\src\services\Content.php(201): craft\services\Content->_updateSearchIndexes(Object(craft\elements\Entry), Object(craft\models\FieldLayout))
#4 C:\wamp64\www\safs-effs\vendor\craftcms\cms\src\services\Elements.php(459): craft\services\Content->saveContent(Object(craft\elements\Entry))
#5 C:\wamp64\www\safs-effs\vendor\craftcms\cms\src\controllers\EntriesController.php(539): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#6 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#7 C:\wamp64\www\safs-effs\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#8 C:\wamp64\www\safs-effs\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#9 C:\wamp64\www\safs-effs\vendor\craftcms\cms\src\web\Controller.php(76): yii\base\Controller->runAction('save-entry', Array)
#10 C:\wamp64\www\safs-effs\vendor\yiisoft\yii2\base\Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#11 C:\wamp64\www\safs-effs\vendor\craftcms\cms\src\web\Application.php(272): yii\base\Module->runAction('entries/save-en...', Array)
#12 C:\wamp64\www\safs-effs\vendor\craftcms\cms\src\web\Application.php(520): craft\web\Application->runAction('entries/save-en...', Array)
#13 C:\wamp64\www\safs-effs\vendor\craftcms\cms\src\web\Application.php(256): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#14 C:\wamp64\www\safs-effs\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#15 C:\wamp64\www\safs-effs\web\index.php(43): yii\base\Application->run()
#16 {main}
```

### Steps to reproduce

1. Create new SuperTable field called `courseVideo` with Row Layout, manage blocks on per-site basis, no min or max rows, not static, Next row label: "Add a video."
2. Add two fields: `videoUrl` (required, plain text) and `videoCaption` (not required, Redactor). 
3. Add field to section entry type. 
4. Add a video on an entry edit page. Include a valid URL and some simple text.
5. Save entry.

### Additional info

- Plugin version: 2.0.6
- Craft version: Craft Pro 3.0.4

![screenshot-safs msu edu-2018 04 30-14-40-53](https://user-images.githubusercontent.com/7085184/39444089-7f9a0bf2-4c84-11e8-976d-c40c20bcc7e8.png)

**Comment by engram-design** [comment]
Was this a Craft 2 upgraded site? Its certainly complaining about a Super Table field that also has an inner field with a handle `dropdownItem`. Are there any other Super Table fields on the entry? Re-saving Super Table fields in most cases will fix things up.

**Comment by KatieMFritz** [comment]
Thanks for the response!

Yes, it's a craft 2 upgraded site, but I didn't add supertable until after I upgraded to Craft 3.

There is another supertable field on the entry, and it works fine.

**Comment by engram-design** [comment]
Great - if you want to try re-saving any Super Table field you have (you don't need to change any field settings), then see if the error persists?

**Comment by KatieMFritz** [comment]
Tried that, no change. 😕

**Comment by engram-design** [comment]
Fixed via Slack. There were some leftovers blocktypes from previous versions of the field.

**Comment by jbye** [comment]
I am having a similar issue, except my field type is 'space'. Can you elaborate on how you fixed the issue?

`yii\base\Exception: Invalid field handle: space in /var/www/craft/vendor/craftcms/cms/src/base/Element.php:1934
Stack trace:
#0 /var/www/craft/vendor/craftcms/cms/src/base/Element.php(1614): craft\base\Element->normalizeFieldValue('space')
#1 /var/www/craft/vendor/verbb/super-table/src/fields/SuperTableField.php(572): craft\base\Element->getFieldValue('space')
#2 /var/www/craft/vendor/craftcms/cms/src/services/Content.php(236): verbb\supertable\fields\SuperTableField->getSearchKeywords(Object(verbb\supertable\elements\db\SuperTableBlockQuery), Object(craft\elements\Entry))
#3 /var/www/craft/vendor/craftcms/cms/src/services/Content.php(201): craft\services\Content->_updateSearchIndexes(Object(craft\elements\Entry), Object(craft\models\FieldLayout))
#4 /var/www/craft/vendor/craftcms/cms/src/services/Elements.php(480): craft\services\Content->saveContent(Object(craft\elements\Entry))`
