### ISSUE TITLE
Can't use handles with the same name for different super table elements inside a matrix

### ISSUE THREAD

**Issue by jsunsawyer** [engram-design/SuperTable#155]
### Description
All of a sudden I'm getting the validation error `Handle "image" has already been taken.` on a large matrix, where multiple, different super table fields use the same, generic field handle. We never had an issue with our naming before and same handle names shouldn't be causing an issue.

This is preventing me from making updates without having to rename all my handles to unique values.

### Additional info

- Plugin version: 2.0.6
- Craft version: 3.0.5

**Comment by engram-design** [comment]
The validation handling in Craft 2 (when used in a Matrix field) was actually incorrect. Previously parent Matrix fields wouldn’t be notified of Super Table fields errors, particularly when using reserved field handles, which caused some bad results.

Now however, brings up another issue in that when in the context of a Matrix, we can have repeated field handles, as they’re in the context of a Matrix field. In a normal Super Table field, this wouldn’t be allowed (just like it isn’t allowed in Matrix block types).

A fix for this is in the [2.0.7](https://github.com/verbb/super-table/releases/tag/2.0.7).
