### ISSUE TITLE
Allow fields to be translated by Site Group

### ISSUE THREAD

**Issue by jsunsawyer** [engram-design/SuperTable#156]
Craft allows us to use [site groups](https://docs.craftcms.com/v3/sites.html#site-groups) to save some time when managing content that shares the same content between various locales. There are several instances where this functionality would save us a lot of time when using Super Tables as well.

Here's a screenshot of the current options for a field in a Super Table field:

![screen shot 2018-05-15 at 1 43 23 pm](https://user-images.githubusercontent.com/1007191/40082625-672fcfc0-5846-11e8-9b59-63958e7a6921.png)

Here's what Craft gives you for non Super Table fields:

![screen shot 2018-05-15 at 1 42 37 pm](https://user-images.githubusercontent.com/1007191/40082655-7a696d58-5846-11e8-85b3-baa3bac3e033.png)

### Additional info

- Plugin version: 2.0.7
- Craft version: 3.0.7

**Comment by engram-design** [comment]
Added in [2.0.8](https://github.com/verbb/super-table/releases/tag/2.0.8)
