### ISSUE TITLE
Column Width in Table Layout

### ISSUE THREAD

**Issue by jtenclay** [engram-design/SuperTable#157]
### Description

This is less of an issue and more of a question – was the Column Width option removed for the Craft 3 release? I remember in Craft 2 being able to choose a width for each field inside a Super Table table layout, but in Craft 3 I don't see a place to do that. This forces all columns to the same width.

### Additional info

- Plugin version: 2.0.7
- Craft version: Craft Solo 3.0.7

**Comment by engram-design** [comment]
Added back in, in [2.0.8](https://github.com/verbb/super-table/releases/tag/2.0.8)
