### ISSUE TITLE
SuperTable hiding my Matrix field headings within SuperTable 

### ISSUE THREAD

**Issue by theskyfloor** [engram-design/SuperTable#16]
SuperTable is hiding my Matrix field headings when I am adding or editing an entry. Was able to quick fix it by adding to the SuperTableInput.css file.

table.editable.superTable tbody tr td .field .matrix .heading {
	display: block;
}

![screen shot 2015-07-16 at 1 48 42 pm](https://cloud.githubusercontent.com/assets/8887839/8732641/72f07226-2bc4-11e5-9574-1a0d704b5111.png)
![screen shot 2015-07-16 at 1 48 34 pm](https://cloud.githubusercontent.com/assets/8887839/8732642/72f73e4e-2bc4-11e5-8f75-f43dc204ef77.png)

**Comment by theskyfloor** [comment]
After shot:

![screen shot 2015-07-16 at 2 19 08 pm](https://cloud.githubusercontent.com/assets/8887839/8732845/a4c864c4-2bc5-11e5-9188-3a7ff2fbae95.png)

**Comment by engram-design** [comment]
@theskyfloor Thanks for pointing this out - never noticed this until now! Will add this to the next release.

**Comment by engram-design** [comment]
@theskyfloor Fixed in the [0.3.1](https://github.com/engram-design/SuperTable/releases/tag/0.3.1) release.

**Comment by theskyfloor** [comment]
Awesome thanks!
