### ISSUE TITLE
Required field can be saved if empty on Matrix -> Super Table -> Matrix content, causing PHP error

### ISSUE THREAD

**Issue by pauljohnston** [engram-design/SuperTable#160]
### When you have Matrix -> SuperTable -> Matrix content, the required 'handle' field can be left blank, allowing empty values to be passed in to the ContentBehaviour class causing the following syntax error (that will bring down the whole site).

`syntax error, unexpected '$', expecting function (T_FUNCTION) or const (T_CONST) in /home/forge/www.scotlandshop.apptesting.online/storage/runtime/compiled_classes/ContentBehavior.php on line 133`

```
// Properties
// =========================================================================

/**
 * @var mixed Value for field with the handle “”.
 */
public $;
```

### Steps to reproduce

1. Create a Matrix that contains 2 Super Tables, then a Matrix inside each of those with 2 levels.
2. Save the field, then go back in and add an item to one of the Matrix inside the Super Table, but leave the handle blank. Click onto another field so the new handle field is no longer showing.
3. Save the field, the site should now no longer work (front end or control panel)

### Additional info

- Plugin version: 2.0.7
- Craft version: Craft Pro 3.0.9

**Comment by engram-design** [comment]
Fixed in [2.0.8](https://github.com/verbb/super-table/releases/tag/2.0.8)
