### ISSUE TITLE
Cannot be blank error on first save after adding multiple supertable fields

### ISSUE THREAD

**Issue by skramstad** [engram-design/SuperTable#161]
### Description
I've created a matrix -> supertable -> matrix field with various buttons.
The first time I add some buttons, only the first button will be saved but the other 2, 3 etc will not be saved and I get this "Myfieldname cannot be blank". (required field). If its not required the field is just empty after page reload (saved page).
If I then add button 2 and 3 again everything will be saved.

This happens with other fields as well when I have a matrix -> supertable -> matrix field.

### Steps to reproduce

1. Create a matrix field (body)
2. Create a new block inside the matrix (buttons)
3. Create a new field inside the block buttons, and lets name it superTableButtons
4. Create a new matrix field inside superTableButtons named stMatrixButtons
5. Create a new block inside the field stMatrixButtons named ButtonOne and 2 new fields inside like Title and Button Url
6. Repeat step 5 to create some various buttons.
7. Save
8. Go to an entry and add you buttons matrix. Add 2 -3 buttons and fill out the fields.
9. Save and see if you get "Myfieldname cannot be blank".

### Additional info

- Plugin version: 2.0.7
- Craft version: 3.0.9 Pro

**Comment by skramstad** [comment]
**Update**: When I change the language to English it works. But when I change it back to Norwegian it fails again.

**Comment by engram-design** [comment]
Should be fixed in [2.0.8](https://github.com/verbb/super-table/releases/tag/2.0.8). You may need to re-create your Matrix fields from the start due to incorrect namespacing being generated.
