### ISSUE TITLE
Static field light switch in settings creates a broken delete row function

### ISSUE THREAD

**Issue by MakeilaLundy** [engram-design/SuperTable#162]
### Description
When you have a table inside of a matrix that is inside a Super Table, and the static field light switch is set to true.  Deleting a row inside a table deletes the entire matrix field within the super table. 

### Steps to reproduce

1. Create a Super table field type.
2. Within the Super Table field, create a matrix field type.
3. Within the Matrix create a table field type.
4. Set static field to true
5.  Add rows to table and save.
6. Try to delete one row from table.

### Additional info

- Plugin version: 2.0.7
- Craft version: 3.0.9

**Comment by engram-design** [comment]
Fixed in [2.0.8](https://github.com/verbb/super-table/releases/tag/2.0.8)
