### ISSUE TITLE
SuperTableField::getEagerLoadingMap() returns an elementType that does not exist

### ISSUE THREAD

**Issue by rob-c-baker** [engram-design/SuperTable#163]
### Description

When using a super table containing a matrix in a global variable, I get the following error (with dev mode enabled, otherwise it's just a 500 server error) :

"Class 'verbb\supertable\fields\SuperTableBlock' not found"

I have had a look through the code and it seems that this class does not exist in version 2.0.7.

The trace indicates that this code in craft's core (craft\services\Elements line 1244):

`$query = $targetElementType::find();`

Expects `SuperTableField::getEagerLoadingMap()` to return an 'elementType' class name that resolves to the string content of the `$targetElementType` variable above. However, right now it contains the string `verbb\supertable\fields\SuperTableBlock` which is not a class I can find in your code base, hence the error when PHP tries to call the `find()` method and load the non-existent class.

The fix for this might be a simple as correcting the class that `SuperTableField::getEagerLoadingMap()` returns for the 'elementType' array key. My current guess would be: `verbb\supertable\elements\SuperTableBlockElement`.

### Steps to reproduce

This might be to do with the way the data was automatically migrated from the Craft 2 installation, but I see this behaviour when I have a Super table field used in field groups attached to structure sections. However, if the correct value for 'elementType' can be established above it might not be necessary to reproduce and can be verified with a unit test?

### Additional info

- Plugin version: 2.0.7
- Craft version: 3.0.9

I am working on moving a Craft 2 site (that uses Super table in this way) into Craft 3. The Craft 3 migration seemed to work fine (in terms of no errors, the control panel works and all data is displayed as it should in the control panel).

**Comment by howells** [comment]
I'm getting this same error - is it not possible to eager load super table blocks?

**Comment by engram-design** [comment]
Fixed in [2.0.8](https://github.com/verbb/super-table/releases/tag/2.0.8)
