### ISSUE TITLE
Static field, maxtrix layout not saved

### ISSUE THREAD

**Issue by jeroenlammerts** [engram-design/SuperTable#164]
### Description

Supertable field being blank after save entry. Matrix Layout and Static Field enabled.

### Steps to reproduce

1. Create a new field name "test"
2. Field type "Super Table"
3. Set Field Layout to "Matrix Layout"
4. Create field under configuration with name "Test2" Plain Text
5. Enable "Static Field" lightswitch
6. Assign the field to a section an try to save the entry

### Additional info
I have 3 languages configured.

- Plugin version: 2.0.7
- Craft version: 3.0.9

**Comment by wewereyoung** [comment]
second that, works only if switched to row layout

**Comment by dgrigg** [comment]
Same here, row/table layout works. Tried  a min 1 row, max 1 row, that also failed.

**Comment by Christo55** [comment]
I got this too, switched too Row, but still prefer Matrix

**Comment by engram-design** [comment]
This was an issue in the original PR for this feature, but fixed in [2.0.8](https://github.com/verbb/super-table/releases/tag/2.0.8)
