### ISSUE TITLE
Field layout | Matrix Layout

### ISSUE THREAD

**Issue by RoyVeldman** [engram-design/SuperTable#166]
### Description

When I use supertable and I use the layout: Matrix Layout, than use min rows:2, max: rows:2. I get the error when i fill them in, Columns should contain at least 2 blocks.

### Steps to reproduce

1. Create SuperTable in Matrix Field
2. Select layout: Matrix Layout
3. Min rows: 2
4. Max rows: 2

### Additional info
Row Layout does work!

- Plugin version: 2.0.7
- Craft version: Craft CMS 3.0.10.3

**Comment by daltonrooney** [comment]
Confirmed, I'm getting the exact same error.

**Comment by engram-design** [comment]
This was an issue in the original PR for this feature, but fixed in [2.0.8](https://github.com/verbb/super-table/releases/tag/2.0.8)
