### ISSUE TITLE
Redactor Initialization Groups Fields Together

### ISSUE THREAD

**Issue by theskyfloor** [engram-design/SuperTable#17]
When I initialize more than one redactor field in a single SuperTable row the two fields end up next to each other instead of in their proper boxes. It ends up saving them correctly and displaying them correctly on refresh but not when the entry hasn't been saved... in fact once the entry is saved the javascript no longer puts the redactor field in the wrong place (even when you add more rows) so it appears to be an issue only when the entry hasn't been saved yet.

![screen shot 2015-07-16 at 2 24 54 pm](https://cloud.githubusercontent.com/assets/8887839/8733047/145fa4a4-2bc7-11e5-9689-c660cc6c5447.png)

**Comment by engram-design** [comment]
@theskyfloor Interesting, I can't seem to reproduce this. I imagine you mean you have a Matrix in a Super Table, then a block (Text) has a single redactor field. I tested this when creating new entries in a channel, and I can't get it to replicate this.

I've also tried adding two Rich Text fields per block, but that doesn't work either. See below setup, but please correct me if I'm wrong. Really appreciate your feedback by the way!

![screencapture-client-craft-dev-office-settings-fields-edit-86-1437207605937](https://cloud.githubusercontent.com/assets/1221575/8760918/a4279fac-2d79-11e5-8bcf-b03102481c1c.png)
![screencapture-client-craft-dev-office-entries-news-new-1437207645899](https://cloud.githubusercontent.com/assets/1221575/8760919/bbe24606-2d79-11e5-8605-7f767cd663d5.png)

**Comment by theskyfloor** [comment]
This seems to be solved with 0.3.2

**Comment by engram-design** [comment]
@theskyfloor My mistake - I didn't realise you were using a Matrix-SuperTable-Matrix field layout, which this does occur in. This has been fixed in the [0.3.2 release](https://github.com/engram-design/SuperTable/releases/tag/0.3.2).
