### ISSUE TITLE
Unable to remove an item from a Radio field

### ISSUE THREAD

**Issue by swthate** [engram-design/SuperTable#170]
### Description
I have a radio field with three available options. I need to remove one of these options, but the delete button does not do anything. I am, however, able to rename the option, move it around, etc. This super table field does have a matrix field within it, and this matrix field has its own radio field which I can delete options in.

### Additional info

- Plugin version: 2.0.7
- Craft version: 3.0.13.1

**Comment by engram-design** [comment]
Can you clarify if this you're talking about the Super Table settings, or the actual input (when editing an entry). Radio buttons are generally not something you can remove once clicked (on the web in general), and interested to know what you mean by the 'delete button' as well.

If you could clarify, I can see what may be going on.

**Comment by swthate** [comment]
This is while editing the super table field itself in the cp. I'm trying to click the 'x' icon in order to remove an option from the radio button field inside my super table field, but nothing happens.

This same super table field has a matrix field. And this matrix field has a radio button inside it as well. And I am able to remove options on that one.

So this might be because the option I want to remove is actually selected on some entry? 

**edit:** I'm pretty sure no entries have this option selected.

**Comment by engram-design** [comment]
I'm unable to reproduce this I'm afraid. To confirm, created a Super Table field that contains a Radio button field. I can add and remove items before saving the field. Going back and editing the field, I can still delete items. I have also tried the same thing with Matrix combinations, and is working fine.

Are there any Javascript errors in the console?

I wonder if you'd be able to put together a video showing this? I'd like to see if I can replicate it.

Please note, it might be worth updating to [2.0.8](https://github.com/verbb/super-table/releases/tag/2.0.8) as well.
