### ISSUE TITLE
Adding a supertable field to a section with existing entries results in a error when attempting to edit an existing entry

### ISSUE THREAD

**Issue by richhayler** [engram-design/SuperTable#171]
### Steps to reproduce

1. Create a supertable field with at least one  plain text row
2. Select row layout
3. Check option for a static table
4. Add field to a section with existing entries
5. Try to open any of those existing entries in the control panel. 

### Additional info

- Plugin version: 2.0.7
- Craft version: 3.0.13.2

**Comment by maxstrebel** [comment]
+1 same Problem here

**Comment by engram-design** [comment]
Can you let me know the specific error? I've tried several different setups, but unable to reproduce this.

**Comment by engram-design** [comment]
Going to close this due to lack of feedback. Please ping me to reopen if still an issue.
