### ISSUE TITLE
Matrix-in-Matrix: Re-ordering large tables

### ISSUE THREAD

**Issue by huelabs** [engram-design/SuperTable#173]
### Description
When trying to create more complex Matrix in Matrix solutions using Super Table, dragging to re-order very tall tables becomes a huge challenge, and in our case, nearly impossible. I think several suggestions could solve the problem:

1. Add UI elements to re-order tables: https://monosnap.com/file/HbX0mQOFXGKj7lzm4UdRIKlgbobMXp

2. Make tables collapsible like Matrix: https://monosnap.com/file/rb00mY6Jk9z3G5jDofGOBe3sJfJdrD

### Additional info

- Plugin version: 2.0.7
- Craft version: 3.0.13.1

**Comment by engram-design** [comment]
Great suggestions, we'll add them to our list to consider!

**Comment by engram-design** [comment]
Very likely not going to happen (sorry), as we push towards a native Craft 4 solution.
