### ISSUE TITLE
Dropdown for field options

### ISSUE THREAD

**Issue by kdouglass** [engram-design/SuperTable#180]
Add a setting to display the field options in a dropdown. It would be nice to have this option on larger screens when there's numerous options.

**Comment by kdouglass** [comment]
Temporary fix:
$('[STRING_PATTERN_OR_ID] .menubtn.hidden').removeClass('hidden');
$('[STRING_PATTERN_OR_ID] .btngroup').addClass('hidden');

**Comment by engram-design** [comment]
Sorry, I'm not clear what this feature request is for specifically, is this when editing a Super Table field, or when editing its content in an entry? What are the field options?

Would you be able to provide a before/after screenshot for clarity?
