### ISSUE TITLE
Unknown method when submitting a form for an entry with a static Super Table field

### ISSUE THREAD

**Issue by HeleenE** [engram-design/SuperTable#181]
### Description
`Calling unknown method: verbb\supertable\elements\SuperTableBlockElement::count()` is thrown when you submit a front-end entry form to an entry that has a static Super Table field, even if that field data is not rendered or called upon by the form.

### Steps to reproduce

1. Create an entry type with a plain text field and a static Super Table field
2. Create an entry of this type
3. Create a template with a form to update the data in the plain text field as described [here](https://docs.craftcms.com/v3/dev/examples/entry-form.html).
4. Try to submit the form

### Additional info

- Plugin version: 2.0.7
- Craft version: 3.0.16.1

**Comment by HeleenE** [comment]
Work around: create a non-static Super Table field with a 'Max Rows: 1' setting.

**Comment by engram-design** [comment]
Fixed in [2.0.8](https://github.com/verbb/super-table/releases/tag/2.0.8)
