### ISSUE TITLE
Feature Request: Contextual Menu for Rows

### ISSUE THREAD

**Issue by adrianjean** [engram-design/SuperTable#182]
Similar to the Matrix field, could each row have a contextual menu (cog icon) that allow the ability to add rows above or below the selected row and collapse rows? 

This is useful for pages with many large rows. Right now, one has to scroll to the bottom to create a new row and move it up to where it's need it.

<img width="102" alt="screen shot 2018-08-05 at 8 23 12 am" src="https://user-images.githubusercontent.com/3161182/43685866-e1c49cca-9888-11e8-8056-c1eb9b0a4c6d.png">

Killer Plugin btw.

**Comment by engram-design** [comment]
Yep, It's something we'll consider!

**Comment by lukeyouell** [comment]
+1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1

**Comment by lukeyouell** [comment]
@engram-design is this something that's in the pipeline? We have a few clients that have been asking if this is possible.

Cheers!

**Comment by engram-design** [comment]
@lukeyouell Not on the immediate todo list, but sure, its on our todo list. The issue is really just with the various layouts making it look good and un-cluttered! Stay tuned though.

**Comment by engram-design** [comment]
Very likely not going to happen (sorry), as we push towards a native Craft 4 solution.
