### ISSUE TITLE
Unable to escape/close HTML list in Redactor field inside a SuperTable

### ISSUE THREAD

**Issue by mmikkel** [engram-design/SuperTable#186]
### Description

There seems to be an issue with _lists_ in Redactor fields inside SuperTable, where it's impossible to escape/close the list by hitting Enter two times – specifically, the list just keeps growing infinitely with empty list items, for each Enter stroke, rather than close/escape after two consecutive empty items, which would be the normal behaviour.

* The issue occurs in Redactor fields inside both Table and Row layouts, but **not** inside Matrix layouts.

* The issue affects both standalone SuperTable fields, and SuperTable fields inside Matrix blocks.

* There are no JS errors printed to the console.

* I've not crossbrowser tested the issue. Here are my browser details: http://whatsmybrowser.org/b/YYXG4R2

Demo:  
![Screencast demo](http://g.recordit.co/ScBUS1uDPS.gif)

### Steps to reproduce

1. Create a SuperTable field, and add a Redactor field to it.
2. Create a list (ordered or unordered) in the Redactor fields, and add a couple of list items
3. Keep hitting the Enter key, notice how the list isn't escaped after adding two empty list items, but keeps growing.

### Additional info

- Plugin version: SuperTable 2.0.8, Redactor 2.1.6
- Craft version: 3.0.21

**Comment by engram-design** [comment]
So this seems to be an issue with the markup Super Table uses - namely the layout for the field makes use of the `<table>` element, which is what seems to throw off Redactor. Removing the input field from the table tag works, which also explains why the Matrix layout is fine, which doesn't use a Table.

Short of a refactor of the Super Table input HTML, this won't be fixed unless Redactor want to fix this (unlikely).
