### ISSUE TITLE
DSTC error when saving globals that contain super-table fields

### ISSUE THREAD

**Issue by jsunsawyer** [engram-design/SuperTable#187]
### Description
Whenever a global set is saved that contains a super-table field, and caching is enabled, we get an instant `Deleting stale template caches` error.

The error returned in queue table in the database is:
```
Argument 1 passed to verbb\supertable\services\SuperTableService::getContentTableName() must be an instance of verbb\supertable\fields\SuperTableField, instance of craft\fields\Matrix given, called in /Users/jason/Sites/schmidtsnaturals.test/craft/vendor/verbb/super-table/src/elements/db/SuperTableBlockQuery.php on line 266
```

Attempting to `Try again` does nothing.

I tried to reproduce this issue on another Craft 3 install with Craft and Super Table up to date, and did not have this error.

This site had been migrated from Craft 2, and at one point, we had some issues with foreign keys and had to fix several issues.

I tested globals with new, basic super-table fields in a new global set with the same issue.

Tests were done with all plugins except for super-table disabled.

### Additional info

- Plugin version: 2.0.8
- Craft version: 3.0.21

**Comment by engram-design** [comment]
Can you advise on your field setup? Is it a Matrix and Super Table combo? I've tried a whole collection of different field setups without being able to reproduce.

It does seem like its trying to pass in a Matrix field when saving the Super Table field.

I wonder if there's some sort of collision with your field handles potentially messing things up?

**Comment by jsunsawyer** [comment]
I have it failing with a basic, test supertable that only uses plain text fields.

**Comment by engram-design** [comment]
Any other fields in your Globals, particularly Matrix fields?

What's the handle of your Super Table Field? Might be worth getting in touch on the Craft Slack (handle crawf) to see if I can get a database dump, as I can't reproduce the issue here.

**Comment by jsunsawyer** [comment]
It looks like it was most likely an issue with a supertable field being deleted, then recreated as a matrix field with the same handle.

Clearing out our templatecaches in our db resolved this.
