### ISSUE TITLE
Cards Layout?

### ISSUE THREAD

**Issue by proimage** [engram-design/SuperTable#188]
I'd love to have a sort of [Cards](https://foundation.zurb.com/sites/docs/card.html) layout for Super Table. Each row added to a Super Table field would be a card. Cards would be rendered similarly to the existing Matrix or Row layouts, where with the fields of the card are stacked vertically. The kicker would be that instead of the full-width that Row and Matrix have for fields, where each new row adds a block below the existing rows, they would be restricted to a user-defined (min?)width (eg 300px, 25%, etc), and would be displayed using `flex-flow: row wrap` on the parent. Here's a Chrome dev-tools "Photoshop":

![image](https://user-images.githubusercontent.com/1027523/44658767-902c0900-aa0a-11e8-99ae-7086a78fb557.png)

**Comment by 23d1** [comment]
This and the ability to add tabs for blocks would be fantastic (for example; Content / Settings / Styling or what have you).

**Comment by engram-design** [comment]
Very likely not going to happen (sorry), as we push towards a native Craft 4 solution.
