### ISSUE TITLE
[Bug] Setting max rows disables reordering

### ISSUE THREAD

**Issue by turnstylerj** [engram-design/SuperTable#189]
### Description

I would like to create a Super Table field that must have 8 row items, but I'd like those items to be re-orderable. Currently, setting min and max rows to the same value will remove the "move/delete" option on the right side in the authoring view, when it should only remove the "delete" option.

### Steps to reproduce

1. Create a Super Table field with the same number of min/max rows (more than 1)
2. View Authoring experience

#### Expected result
Rows cannot be deleted, but should be re-orderable.
![screen shot 2018-08-27 at 3 40 39 pm](https://user-images.githubusercontent.com/42223501/44690569-31698e00-aa10-11e8-90b0-1e518fadc253.png)

#### Actual Result
Rows are not re-orderable.
![screen shot 2018-08-27 at 3 41 08 pm](https://user-images.githubusercontent.com/42223501/44690573-375f6f00-aa10-11e8-844e-35920fd1df6b.png)

### Additional info

- Plugin version: 2.0.8
- Craft version: 3.0.21

**Comment by engram-design** [comment]
Fixed in [2.0.10](https://github.com/verbb/super-table/releases/tag/2.0.10).
