### ISSUE TITLE
LinkIt fields aren’t saving correctly

### ISSUE THREAD

**Issue by joshuabaker** [engram-design/SuperTable#19]
The cell is returning a `Twig_Markup` instance with an empty link string, instead of the expected array.

```html
<a href=""></a>
```

**Comment by theskyfloor** [comment]
That's odd... I am using SuperTable and Linkit together and mine are saving. Is the error coming up on the template side? Or when you save in the back end? Is your Linkit field in a SuperTable cell on the top level or in a Matrix in a SuperTable?

I am not the developer of course... I am just curious if I can be of any help!

**Comment by joshuabaker** [comment]
Thanks, @theskyfloor!

The field is inside a SuperTable block, which is inside a Matrix block.

I’ve tested and it works as expected when used outside of SuperTable.

**Comment by engram-design** [comment]
@joshuabaker I can't seem to replicate this. See the below screenshots for my field setup, which is pretty normal. Going to go out on a limb here - I hope your Linkit field's handle isn't `link`?

Like @theskyfloor mentioned - is this an issue when you're saving the Super Table field from the control panel, or an error that pops up when viewing the template from the front-end?

![screen shot 2015-07-24 at 10 57 41 pm](https://cloud.githubusercontent.com/assets/1221575/8874798/abb38e6a-3257-11e5-9a98-f34aa2b80067.png)
![screen shot 2015-07-24 at 11 00 04 pm](https://cloud.githubusercontent.com/assets/1221575/8874807/c1f3357c-3257-11e5-849b-e2aafee0dca3.png)

```
{% for block in entry.matrixSuperTableLinkit %}
	{% for row in block.superTable %}
		{{ row.linkUrl.url }}<br>
	{% endfor %}
{% endfor %}

Renders:
/test
http://client.craft.dev/news/test
```

**Comment by joshuabaker** [comment]
![Oh deer, this is embarrassing](http://www.quickmeme.com/img/21/21f09c3590670b09ae768414530f1533192e0b0b8e91f1c42fb95a5ed2f0f042.jpg)

The handle was indeed `link`.

Sorry! Thanks for taking the time to check on this.

**Comment by engram-design** [comment]
@joshuabaker +2 points for that pic haha! Glad that's all it was.

On a related note, I'm really struggling to make validation work when the ST field is inside a Matrix. It's something that I'm not even sure is possible without P&T making some changes on their end. That would solve a lot of these problems :smile:
