### ISSUE TITLE
SQL error when creating/editing a Super Table field with PostgreSQL

### ISSUE THREAD

**Issue by brandonkelly** [engram-design/SuperTable#193]
When saving a Super Table field’s settings on an Craft install that uses PostgreSQL, the following SQL error will occur:

> SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "new1"
> The SQL being executed was: SELECT EXISTS(SELECT *
> FROM "fields"
> WHERE ("fields"."handle"='matrix') AND ("fields"."context" IS NULL) AND (NOT ("id"='new1')))

This happens because Super Table is setting new sub-fields’ `id` attributes to `newX`, which ends up as part of a WHERE condition during unique validation, which PostgreSQL isn’t happy with because it’s not an integer.

We just fixed the same bug in Matrix (craftcms/cms#3252) so the fix should be pretty much identical (craftcms/cms@eeac5b670583167704f86196f1b9323aa19aeb5b).

**Comment by engram-design** [comment]
Merged in [2.0.9](https://github.com/verbb/super-table/releases/tag/2.0.9)
