### ISSUE TITLE
getFieldLayout() not working anymore after update

### ISSUE THREAD

**Issue by xenoy** [engram-design/SuperTable#197]
### Description

After updating to Super Table 2.0.8 the following code isn't working anymore
`{% for field in my_global.super_table_field.getFieldLayout().fields %}
		{{field.handle}} : '{{my_global.super_table_field[field.handle]}}',
{% endfor %}`
 
and throws this error message

`Calling unknown method: verbb\supertable\elements\db\SuperTableBlockQuery::getFieldLayout()`

### Steps to reproduce

1. Create a  Super Table field in the CP and declare it as a **static field**
2. Add multiple fields
3. Add Super Table field to global or entry
4. Use code above in your template

### Additional info

- Plugin version: 2.0.8
- Craft version: 3.0.22

**Comment by engram-design** [comment]
This change in 2.0.9 is actually a correction of an issue in the previous release. In previous releases, when calling a static Super Table field, it wouldn't return a query object, which it certainly should (so you can use `all(), one(), etc`. It sort-of worked in previous releases, but it was a bit of a hack. As such it's caused this sort of behaviour, but its actually correct behaviour now.

Having said that, I have fixed this in the [2.0.10](https://github.com/verbb/super-table/releases/tag/2.0.10) release for methods being called on static Super Table fields..
