### ISSUE TITLE
Upgrade from Super Table 0.2.8 fails

### ISSUE THREAD

**Issue by outline4** [engram-design/SuperTable#198]
### Description

I try to upgrade from Super Table 0.2.8 to any other version and I get an error Message saying that the update failed. 

I've tried to upgrade to version 0.4.2, 0.4.6, and the latest version 1.0.6. 

This is what I've found in the log of craft: 

	2018/09/03 12:43:16 [info] [application] [Forced] Preparing to update supertable.
	2018/09/03 12:43:16 [info] [application] [Forced] Finished preparing to update supertable.
	
	******************************************************************************************************
	2018/09/03 12:43:17 [info] [application] [Forced] Starting to backup database.
	2018/09/03 12:43:17 [info] [application] [Forced] Starting to backup database.
	2018/09/03 12:43:25 [info] [application] [Forced] Finished backing up database.
	
	******************************************************************************************************
	2018/09/03 12:43:25 [info] [application] [Forced] Starting to update the database.
	2018/09/03 12:43:25 [info] [application] [Forced] The plugin "Super Table" wants to update the database.
	2018/09/03 12:43:25 [info] [application] [Forced] Running migrations...
	2018/09/03 12:43:25 [info] [application] [Forced] Total 1 new migration to be applied for plugin SuperTable:
	2018/09/03 12:43:25 [info] [application] [Forced] m150901_144609_superTable_fixForContentTables
	2018/09/03 12:43:25 [info] [application] [Forced] Applying migration: m150901_144609_superTable_fixForContentTables for plugin: SuperTable
	2018/09/03 12:43:25 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'craft_supertablecontent_75_icons_supertable_elementId_locale_unq_id' is too long. The SQL statement executed was: CREATE TABLE `craft_supertablecontent_75_icons_supertable` (
	  `id` int(11) NOT NULL AUTO_INCREMENT,
	  `elementId` int(11) NOT NULL,
	  `locale` char(12) COLLATE utf8_unicode_ci NOT NULL,
	  `field_iconTitle` text COLLATE utf8_unicode_ci,
	  `field_inconDesc` text COLLATE utf8_unicode_ci,
	  `dateCreated` datetime NOT NULL,
	  `dateUpdated` datetime NOT NULL,
	  `uid` char(36) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
	  PRIMARY KEY (`id`),
	  UNIQUE KEY `craft_supertablecontent_75_icons_supertable_elementId_locale_unq_id` (`elementId`,`locale`),
	  KEY `craft_supertablecontent_75_icons_supertable_locale_idx` (`locale`),
	  CONSTRAINT `craft_supertablecontent_75_icons_supertable_elementId_fk` FOREIGN KEY (`elementId`) REFERENCES `craft_elements` (`id`) ON DELETE CASCADE,
	  CONSTRAINT `craft_supertablecontent_75_icons_supertable_locale_fk` FOREIGN KEY (`locale`) REFERENCES `craft_locales` (`locale`) ON DELETE CASCADE ON UPDATE CASCADE
	) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci.
	2018/09/03 12:43:25 [error] [application] CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'craft_supertablecontent_75_icons_supertable_elementId_locale_unq_id' is too long (/craft/app/framework/db/CDbCommand.php:358)
	2018/09/03 12:43:25 [error] [application] #0 /craft/plugins/supertable/migrations/m150901_144609_superTable_fixForContentTables.php(56): CDbCommand->execute()
	#1 /craft/app/etc/db/BaseMigration.php(33): Craft\m150901_144609_superTable_fixForContentTables->safeUp()
	#2 /craft/app/services/MigrationsService.php(149): Craft\BaseMigration->up()
	#3 /craft/app/services/MigrationsService.php(91): Craft\MigrationsService->migrateUp('m150901_144609_...', Object(Craft\SuperTablePlugin))
	#4 /craft/app/etc/updates/Updater.php(180): Craft\MigrationsService->runToTop(Object(Craft\SuperTablePlugin))
	#5 /craft/app/services/UpdatesService.php(749): Craft\Updater->updateDatabase(Object(Craft\SuperTablePlugin))
	#6 /craft/app/controllers/UpdateController.php(301): Craft\UpdatesService->updateDatabase('supertable')
	#7 /craft/app/framework/web/actions/CInlineAction.php(49): Craft\UpdateController->actionUpdateDatabase()
	#8 /craft/app/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
	#9 /craft/app/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
	#10 /craft/app/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
	#11 /craft/app/framework/web/CWebApplication.php(282): CController->run('updateDatabase')
	#12 /craft/app/etc/web/WebApp.php(937): CWebApplication->runController('update/updateDa...')
	#13 /craft/app/etc/web/WebApp.php(262): Craft\WebApp->_processUpdateLogic()
	#14 /craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
	#15 /craft/app/index.php(62): CApplication->run()
	#16 /public_html/index.php(17): require_once('/home/fountai1/...')
	#17 {main}
	2018/09/03 12:43:25 [error] [application] Failed to apply migration: m150901_144609_superTable_fixForContentTables (time: 0.164s)
	2018/09/03 12:43:25 [error] [application] Migration failed for plugin SuperTable. All later SuperTable migrations are canceled.
	
	******************************************************************************************************

I have found a database table "craft_supertablecontent_icons_supertable" but not "craft_supertablecontent_75_icons_supertable_elementId_locale_unq_id"

Do you know what could be wrong here? 

### Additional info
- Craft version: 2.6.2993

Cheers 
Stefan

**Comment by engram-design** [comment]
0.2.8 was some time ago, and there have certainly been a few 'gotchas' along the way. These were documented below:

- [Updating from 0.4.2 to 0.4.3](https://github.com/engram-design/SuperTable/wiki/Release-Notes#updating-from-042-to-043)
- [Updating from 0.3.4 to 0.3.5](https://github.com/engram-design/SuperTable/wiki/Release-Notes#updating-from-034-to-035) 

Note that 1.x.x releases are only for Craft 3.

**Comment by outline4** [comment]
Hi,  
your links don't work...  
it's redirected to verbb, and verbb has no wiki...  
Is this information available anywhere else?

**Comment by outline4** [comment]
Hi, I've found the link: 

https://verbb.io/craft-plugins/super-table/docs/support/release-notes

Thanks for pointing that out!

**Comment by engram-design** [comment]
Whoops, sorry about that, I replied this comment while offline without checking the links. Let me know if any of that doesn't make sense, but best to get in touch via Slack (@crawf) as it might be tedious with the back-and-forth. Closing for now.
