### ISSUE TITLE
Config for rich text table cell?

### ISSUE THREAD

**Issue by eheiser** [engram-design/SuperTable#2]
Right now when I select the rich text field it gives me the config with all the buttons... is there any way of choosing which button config gets loaded for a rich text field?

**Comment by engram-design** [comment]
@eheiser not sure I know what you mean. You can alter any fields settings from the Super Table's settings - just click on the settings 'cog' for the table column. See below screenshots to illustrate a working example.

![screen shot 2015-05-09 at 12 27 33 am](https://cloud.githubusercontent.com/assets/1221575/7538320/56e629e4-f5e2-11e4-9e94-bf060d7085ff.png)
![screen shot 2015-05-09 at 12 27 43 am](https://cloud.githubusercontent.com/assets/1221575/7538319/56e08480-f5e2-11e4-895d-4450c4d292f3.png)
![screen shot 2015-05-09 at 12 27 56 am](https://cloud.githubusercontent.com/assets/1221575/7538318/56dfd80a-f5e2-11e4-8eee-85d89edab2fb.png)

**Comment by eheiser** [comment]
Yup - *facepalm* totally missed that one. Thanks!

**Comment by engram-design** [comment]
No worries - happens all the time to me! :)
