### ISSUE TITLE
SuperTable and Rich Text Fields - Data Not Saving

### ISSUE THREAD

**Issue by theskyfloor** [engram-design/SuperTable#20]
Hey,

I am having a relatively major issue where rich text fields aren't saving one or more fields of data when I add more than one rich text field on an edit page. This seems to happen on a new entry or on an existing entry - so long as I am initiating more than one new rich text field on the page prior to saving. Seems to be a naming issue with JS or the saving logic because the last added field often retains the data. In case you are curious this is with a Matrix which then contains a SuperTable which then contains a Matrix and that is where the rich text fields are being added.

Any help would be amazing as this is a site under active development and I am nervous my client will notice and not be happy.

Thanks as always!

**Comment by theskyfloor** [comment]
I guess this relates to my last issue as well but I didn't seem to be having issues with saving at that time.

**Comment by theskyfloor** [comment]
Testing this out I just had the issue from #17 appear and when that happened neither rich text field saved my data : (

Rich Text box 1(hidden texture name):

`fields[pageBuilder][new1][fields][columns][new1][fields][columnContent][new1][fields][text]`

Rich Text box 2 (hidden texture name):

`fields[pageBuilder][new2][fields][columns][new1][fields][columnContent][new2][fields][text]`

Don't know if this is helpful at all because I am not sure of how this all works together!

**Comment by theskyfloor** [comment]
Finally let me know if you want a dump of my set up - I will be available over the weekend if you have any time that would be swell!

**Comment by engram-design** [comment]
@theskyfloor This has been fixed in the [0.3.2 release](https://github.com/engram-design/SuperTable/releases/tag/0.3.2).
