### ISSUE TITLE
Unable to navigate between fields if field fails validation

### ISSUE THREAD

**Issue by lukeyouell** [engram-design/SuperTable#202]
### Description

I'm unable to navigate between fields if one of them fails validation, it seems like a JS issue but nothing is displayed in the console. This means that the only solution is to quit the process and create the field again from scratch. 

![image](https://user-images.githubusercontent.com/24975058/45158472-09cab080-b1dc-11e8-8c79-fe5a47d3d152.png)

It's worth noting that I'm using `dev-craft-3 as 2.0.8`

### Steps to reproduce

1. Create a ST field with multiple fields
2. Ensure that one of the fields (not the first one) fails validation
3. Try to navigate to that field
4. Clicking the 'tab' has no effect

### Additional info

- Plugin version: dev-craft-3 as 2.0.8
- Craft version: 3.0.23.1

**Comment by janhenckens** [comment]
Can reproduce that with the same versions installed, not with 3.0.20 & the "real" 2.0.8

**Comment by engram-design** [comment]
Fixed in [2.0.10](https://github.com/verbb/super-table/releases/tag/2.0.10).
