### ISSUE TITLE
Craft3 - nested supertable content disappearing across sites upon enabling "manage blocks on per-site basis"

### ISSUE THREAD

**Issue by EFWall** [engram-design/SuperTable#203]
### Description

We have a fairly complex site using lots of fields with supertables and supertables nested inside of matrix fields, and so on. We have multiple sites and we originally enabled the content across all sites without allowing any translation so that content would copy across and stay in sync until we were ready to begin translating and sculpting the content per site. This has all been working great but when we change one of the matrix fields that contains nested super tables and other matrix fields to "manage blocks on per-site basis" then we go to any entry using that field and save the entry, all of the sites except the one currently being edited lose the supertable content for that entry.

### Steps to reproduce

1. Create a matrix field with nested supertables and other matrix fields. Do not set the field to "manage blocks on per site basis."
2. Enable section with this field across multiple sites. 
3. Add content to nested supertable fields within matrix field. Content should be replicated exactly across all enabled sites.
4. Change top-level matrix field to "managed blocks on per site basis"
5. Return to entry where content exists and resave entry.
6. Supertable content is retained on the specific site you were editing but disappears from all other sites for that one entry.

Note: I have tested this on stand alone supertables and it does not seem to affect them. It definitely affects matrix content that is nested inside a supertable and supertable content nested inside a matrix. I am unsure whether it also impacts supertable content nested inside a supertable.

**Comment by jeroenlammerts** [comment]
I have the same issue.

**Comment by engram-design** [comment]
This is tricky if nothing else that when nested in a Matrix field, there's a limited amount of things we can do on Super Table's end. I'll likely have to get @brandonkelly 's involvement to put our heads together on this one.

**Comment by brandonkelly** [comment]
Managed to fix this in Matrix.

**Comment by engram-design** [comment]
I can confirm @brandonkelly 's commit has fixed this issue.

If you’re comfortable with Terminal/Composer, you can get this change right away by updating your craftcms/cms version requirement in composer.json:

```
"require": {
    "craftcms/cms": "dev-develop#c017661317cbf1bcedc4ee7d16d8657bcbccde26 as 3.0.28.1",
    "verbb/super-table": "dev-craft-3",
},
```

Then go to your project in Terminal and run `composer update`.

**Comment by howells** [comment]
Sorry to reference this old issue, but I just had this problem with 3.1.7. Is it still a problem?
