### ISSUE TITLE
Doesn't work with optimizeimage

### ISSUE THREAD

**Issue by dubcanada** [engram-design/SuperTable#205]
### Description
If you use it with https://github.com/nystudio107/craft-imageoptimize you end up getting an error at `src/fields/SuperTableField.php` line 221 `'name' => $fieldConfig['name'],` undefined. It is specifically a optimize image field error, as it works with all the others.

### Steps to reproduce

1. Create super table.
2. Attempt to add imageOptimize field

### Additional info

- Plugin version: 2.0.10 and latest optimizieImage
- Craft version: 3.0.25

**Comment by engram-design** [comment]
@khalwat was kind enough to merge this fix on the Optimize Image end, so marking this as fixed.
