### ISSUE TITLE
Can't add new options to Super Table dropdown field

### ISSUE THREAD

**Issue by jonlivingston** [engram-design/SuperTable#209]
### Description
After creating the initial Super Table I'm unable to add a new option at the bottom where it says "+ Add an Option". Selecting it does nothing. I have tried in Google Chrome, Firefox and Safari.

<img width="763" alt="screen shot 2018-10-19 at 1 18 05 pm" src="https://user-images.githubusercontent.com/175549/47233769-c0a47980-d3a1-11e8-9827-9df78c350251.png">

### Steps to reproduce

1. Create initial Super Table
2. Save Super Table
3. Go back into table and try to select  "+ Add an Option"
4. Nothing happens

### Additional info

- Plugin version: SuperTable 2.0.10
- Craft version: 3.0.27.1

**Comment by engram-design** [comment]
Can you check the developer console (in Chrome) if there are any Javascript errors on the page?

**Comment by McCrisp** [comment]
I'm having the same issue on Craft 3.0.33 when creating new rows on an entry nothing happens.
I get the following error in the console:
![screen shot 2018-11-30 at 11 18 45](https://user-images.githubusercontent.com/13944443/49283364-da050f00-f491-11e8-8d50-8038cd61298d.png)

**Comment by engram-design** [comment]
Still struggling to replicate this I'm afraid on 3.1.x. Are you able to try out the latest Super Table and Craft versions to see if this still occurs @McCrisp and @jonlivingston?

**Comment by engram-design** [comment]
Still looking to see if I can help with this issue. Also happy to chat on the Craft Slack (handle `crawf`)

**Comment by McCrisp** [comment]
My issue seem to be solved after the latest updates.
