### ISSUE TITLE
0.3.2 Matrix within SuperTable (where SuperTable is the parent field) JS Error

### ISSUE THREAD

**Issue by theskyfloor** [engram-design/SuperTable#21]
I was testing out my second field where the SuperTable is the outer most parent field and the Matrix is a child of a SuperTable row and it seems to be broken in 0.3.2. As we discussed in the morning the configuration that I need is working but if others are using it `SuperTable > Matrix` and not `Matrix > SuperTable > Matrix` it seems like this would be a fatal update.

    TypeError: undefined is not an object (evaluating 'Craft.MatrixInput.getCollapsedBlockIds')
    initMatrixInputAlt.js:56

**Comment by engram-design** [comment]
This has been fixed in the [0.3.3 release](https://github.com/engram-design/SuperTable/releases/tag/0.3.3). Thanks once again for identifying this!
