### ISSUE TITLE
Entry versioning history error

### ISSUE THREAD

**Issue by umkasanki** [engram-design/SuperTable#212]
### Description

I get an error if I try to see old versions

![scr-1](https://user-images.githubusercontent.com/496132/47953320-0f026c80-df8d-11e8-946f-d56483857a5b.png)

I tried to fix the condition in the templates:
`
{% if not staticField %} > {% if staticField is defined and not staticField %}
`
This helped solve this problem, but the second problem appeared.
Fields are displayed without styles.

![scr-2](https://user-images.githubusercontent.com/496132/47953424-8b497f80-df8e-11e8-9219-858f5c5bbcd8.png)

### Steps to reproduce

1. Use static field
2. Try to see old versions

### Additional info

- Plugin version: 2.0.11
- Craft version: 3.0.29

**Comment by engram-design** [comment]
Fixed in [2.0.12](https://github.com/verbb/super-table/releases/tag/2.0.12)

**Comment by umkasanki** [comment]
Thanks so much!

**Comment by umkasanki** [comment]
The main problem with the twig error is fixed, but the fields are still displayed without styles.

![scr-2](https://user-images.githubusercontent.com/496132/47953424-8b497f80-df8e-11e8-9219-858f5c5bbcd8.png)

**Comment by engram-design** [comment]
Fixed in [2.0.13](https://github.com/verbb/super-table/releases/tag/2.0.13)
