### ISSUE TITLE
Super Table link appearing in CP main nenu.

### ISSUE THREAD

**Issue by mark-chief** [engram-design/SuperTable#213]
### Description
Just updated to the latest version 2.0.13 and noticed a "Super Table" link in the left main menu in the CP. It's goes to a 404 `/admin/supertable`

### Steps to reproduce

See attached screenshot
<img width="279" alt="screen shot 2018-11-12 at 09 33 18" src="https://user-images.githubusercontent.com/18699249/48338603-fe718680-e65d-11e8-823d-c450472902fd.png">

**Comment by engram-design** [comment]
Fixed in [2.0.14](https://github.com/verbb/super-table/releases/tag/2.0.14)
