### ISSUE TITLE
Question: Pre-Setup Structure of Table and Custom Functionality

### ISSUE THREAD

**Issue by rhoffmann** [engram-design/SuperTable#214]
### Description

I have a scenario where i want to set up a SuperTable Field with exactly 3 (or any number) of rows, each row should have pre-filled values, for example i want to have setup a table looking exactly like this. 

| value  |  x  |  y  |  
|------|---|---|
| 100 |  |  | 
| 500  |   |   |
| 1000 |   |   | 

Is this currently possible to setup with supertable as is, or how would one go about it creating this feature? Is it necessary to create a custom plugin with my own `FieldType` or are there ways to 'enhance' supertable with this?

Also relating to this, i need to add a custom functionality (client-side in the CP) which copies values (x, y) entered in the first row (in the above scenario with value 100), to the other rows. Any hints on how to achieve that with custom functionality?

*Disclaimer*: I am aware this is no real feature request, feel free to delegate me to another source / close this issue if necessary. :)

**Comment by engram-design** [comment]
There's currently no method for pre-populating or setting defaults on Super Table fields like you would with a Table field. As such, the plugin acts closer to a Matrix field.

There's always room for FR's, so we'll add this to the list, but its likely not going to be implemented in the short term. In an older version of Super Table, it actually bundled a 'Label' field, which were read-only labels suitable for this purpose. You might want to see if Sprout Fields or similar field bundles have something similar to this field?

You can also set the min and max rows to be exactly 3, or opt for a static field. This will give you a set number of rows, but depending on your needs, this may not be what you're after.

I will say that second part is not this plugin's responsibility. You could use something like CP JS and some Javascript to achieve what you need.

Hope that helps a little?

**Comment by rhoffmann** [comment]
Thanks for the super fast answer :) 👍 

Actually i was starting with CP JS and started with some jQuery wrapper functionality, but then i thought there should be an easier way. I was missing out on some docs for the `Craft` and `Garnish` global modules, so i felt i was doing double work. But probably this is the way to go currently... do yo know if any of the `Craft.SuperTable<XY>` namespaces can be helpful for this? 

Will check out the hints about Sprout Fields, also if maybe a simple table field can be configured for that. Thanks!
