### ISSUE TITLE
Random seems to be choosing fields outside it's row

### ISSUE THREAD

**Issue by jonlongnecker** [engram-design/SuperTable#215]
### Description
Bear with me, this is kind of hard to explain. I have a Super table with these fields (columns)

- Background Image
- Heading Color
- SubHeading Color

On the template side I am only showing one random row per page load. So I should be getting an image and the two heading colors that correspond with that image each load.

But what I'm seeing is that it's pulling in colors from other rows on the headings. Like it's pulling randomly from each cell instead of each row.

### Code
I'm using this code to set the random row - maybe there's something I'm missing here?

Set row:
`{% set randBannerImage = entry.bannerImages.orderby('RAND()').limit(1) %}`

Call color:
`{% for color in randBannerImage.all() %}{{ color.headingTextColor }}{% endfor %}`

### Additional info

- Plugin version: 2.0.14
- Craft version: 3.0.33

**Comment by jonlongnecker** [comment]
Hey sorry to bump this again - we've launched the site and I'd love to get this figured out so our banner text is readable on the homepage :)

thanks!

Jonathan

**Comment by engram-design** [comment]
Hey Jonathan, I struggled to reproduce this actually, but I'm not sure your template code is quite correct anyway, although that shouldn't be the issue.

As a handy hint, you don't need to fetch all the blocks if you're limiting to one:
```
{% set randBanner = entry.bannerImages.orderBy('RAND()').one() %}

{{ randBanner.backgroundImage }}
{{ randBanner.headingTextColor }}
{{ randBanner.subheadingColor }}
```

Otherwise, on my end its certainly working as expected!

**Comment by jonlongnecker** [comment]
So apparently looping through it again was the issue. Once I moved to setting it globally and then calling by the individual variables alone it worked itself out. I'm not sure why either, but thanks for the tip!
