### ISSUE TITLE
Super Table doesn't allow any sub-fields to be saved in Craft 3.1.0-beta

### ISSUE THREAD

**Issue by jdsimcoe** [engram-design/SuperTable#217]
### Description

`Super Table` doesn't allow any sub-fields to be saved in Craft `3.1.0-beta.4`. Trying to save `Super Table` settings in the cp produces a stack trace error (see below).

### Steps to reproduce

1. Update Craft to `3.1.0-beta.4`.
2. Install `Super Table` from the Craft Plugin Store.
3. Go to `Super Table` settings in the Control Panel `.../settings/plugins/super-table`.
4. Click `Save` in the upper right and it will produce the following stack trace: https://gist.github.com/jdsimcoe/b5142f775b2426d49dd8e1d960d51eb6.
5. Go to `Settings/Fields` and add a `Super Table` filed to a field set.
6. Add sub-fields to the `Super Table` and click 'Save'.
7. Return to the `Super Table` field and see that it is empty; none of the sub-fields are saved.

### Additional info

- Plugin version: `2.0.14`
- Craft version: `3.1.0-beta.4`

**Comment by engram-design** [comment]
3.1 beta is not yet supported, but we're about to jump into this on the feature/craft-3.1 branch.

**Comment by thatONEjustin** [comment]
Is there a projected date for 3.1 integration? I need to know if I should downgrade an upcoming project.

**Comment by engram-design** [comment]
@jdsimcoe Firstly, the plugin settings shouldn't be there, and will be removed in the next release.

I'm testing this out on 3.1.0, and saving fields is going okay in a few different scenarios. Can you advise if its still an issue?

Please also see [2.1.0](https://github.com/verbb/super-table/releases/tag/2.1.0) to fix some 3.1 compatibilities.

**Comment by engram-design** [comment]
Closing in favour of https://github.com/verbb/super-table/issues/222

**Comment by jdsimcoe** [comment]
@engram-design FWIW `2.1.0` solved all my issues
