### ISSUE TITLE
Reordering blocks in a matrix field that is inside a Super Table field doesn't work properly

### ISSUE THREAD

**Issue by davefischoff** [engram-design/SuperTable#218]
### Description
When using a Super Table field that has a matrix field within it, reordering the matrix blocks in the matrix field is difficult- the block that is being dragged becomes almost completely transparent and the outer Super Table block moves along with the inner matrix block that the user is trying to drag and drop.

### Steps to reproduce

1. Create a Super Table field that contains a matrix field.
2. Add multiple blocks of content to the matrix field within the Super Table field and then try to reorder those blocks using drag and drop.

### Additional info

- Plugin version: 2.0.14
- Craft version: Craft Pro 3.0.34

**Comment by engram-design** [comment]
Just to confirm is this when the Super Table field's layout is set to "Matrix Layout"? I can only replicate it when using that layout - Row and Table seem to be fine.

Is this what you're seeing also?

**Comment by davefischoff** [comment]
Yes, I'm seeing this when using the Matrix Layout.

**Comment by engram-design** [comment]
Fixed in [2.1.1](https://github.com/verbb/super-table/releases/tag/2.1.1)

**Comment by riccardolardi** [comment]
I have this issue with latest Version for CraftCMS 3 but only with Row Layout...

**Comment by n-kingan** [comment]
I'm seeing this issue on Craft 4.6.1 and Super Table 3.0.12 when using row layout.
