### ISSUE TITLE
Issue saving SuperTable subfields within a Matrix Field on Craft 3.1

### ISSUE THREAD

**Issue by bringmethedeathstar** [engram-design/SuperTable#222]
### Description
When creating Subfields on a Supertable within a Matrix, the Supertable itself is created, but any Subfields seem to disappear silently without an error.

Creating Subfields on a Supertable outside of a Matrix, as well as saving Subfields on a previously created Supertable within a Matrix seems to work fine.

(possibly related to #217)

### Steps to reproduce

1. Create a Matrix field
2. Create a block within the Matrix
3. Create a Supertable field within that block
4. Create any field within that Supertable

### Additional info

- Plugin version: 2.1.0
- Craft version: 3.1.0 & 3.1.1

**Comment by engram-design** [comment]
Its a known issue, and potentially something might need to be done on the Craft end. Will keep you posted!

**Comment by linotex** [comment]
When we can expect fix, because it is epic fail...?. I have a lot of super table fields and nothing to work((((

**Comment by RaederDev** [comment]
I'm not sure if I have the same issue. When I add a new field to a nested matrix field all previously entered content disappears. Is this the same issue?

**Comment by engram-design** [comment]
@N0ps32 Its the same issue, and @linotex rest-assured we're working on this as a priority

**Comment by missmatsuko** [comment]
We have a structure Neo > Matrix > Supertable that does not save, either. 
And disabling project config doesn't affect it.

**Comment by marcdebiak** [comment]
Similar issue here. Craft 3.1.1 and Super Table 2.1.0.

In our case, we are using a Matrix inside a Super Table.

**Comment by engram-design** [comment]
Fixed in [2.1.1](https://github.com/verbb/super-table/releases/tag/2.1.1) and [Craft 3.1.2](https://github.com/craftcms/cms/releases/tag/3.1.2). Please update both Super Table and Craft as these changes effect both packages.

**Comment by engram-design** [comment]
Additionally, [2.1.5](https://github.com/verbb/super-table/releases/tag/2.1.5), introduces a new "Content Table Checker/Fixer" which I'd recommend people run via `http://mysite.com/actions/super-table/plugin/check-content-tables` to ensure everything is okay. This check won't write any changes, but will give you the opportunity to do so if any errors our found.

If any errors are found, you can run the fixer. Database backups are triggered before the fixer runs as well, just in case something goes wrong at that point.
