### ISSUE TITLE
Matrix > Super Table > Matrix fields get dropped on 2.1.0 update

### ISSUE THREAD

**Issue by ghost** [engram-design/SuperTable#223]
When updating to 2.1.0, after updating the database, all my Matrix > Super Table > Matrix content is dropped.

**Comment by linotex** [comment]
I have some problem! And new fields doest save(((

**Comment by juddlyon** [comment]
Can also confirm that Super Table fields inside Matrix Blocks are not saving. No error is thrown upon save, but when you return to edit the fields the Super Table fields are gone.

GIF: https://juddlyon.d.pr/uNVwoe

- Craft CMS 3.1.1
- Super Table 2.1.0

**Comment by engram-design** [comment]
Fixed in [2.1.1](https://github.com/verbb/super-table/releases/tag/2.1.1) and [Craft 3.1.2](https://github.com/craftcms/cms/releases/tag/3.1.2). Please update both Super Table and Craft as these changes effect both packages.

**Comment by ghost** [comment]
@engram-design 

After updating to craft 3.1.2 and super table 2.1.3 I can't access any page with super table content, I always get error 500, with no additional error messages. This is from /storage/logs/web.log

```
Next yii\db\Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'hbs.stc_columns' doesn't exist
The SQL being executed was: SELECT `elements`.`id`, `elements`.`fieldLayoutId`, `elements`.`uid`, `elements`.`enabled`, `elements`.`archived`, `elements`.`dateCreated`, `elements`.`dateUpdated`, `elements_sites`.`slug`, `elements_sites`.`uri`, `elements_sites`.`enabled` AS `enabledForSite`, `supertableblocks`.`fieldId`, `supertableblocks`.`ownerId`, `supertableblocks`.`ownerSiteId`, `supertableblocks`.`typeId`, `supertableblocks`.`sortOrder`, `content`.`id` AS `contentId`, `content`.`field_width`, `content`.`field_background`, `content`.`field_offset`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`
FROM `elements` `elements`
INNER JOIN `supertableblocks` `supertableblocks` ON `supertableblocks`.`id` = `elements`.`id`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `stc_columns` `content` ON `content`.`elementId` = `elements`.`id`
WHERE (`supertableblocks`.`fieldId`='51') AND (`supertableblocks`.`ownerId`='3074') AND (`elements_sites`.`siteId`=2) AND (`content`.`siteId`=2) AND (`elements`.`archived`=FALSE) AND (`elements`.`dateDeleted` IS NULL)
ORDER BY `supertableblocks`.`sortOrder`) `subquery`
INNER JOIN `supertableblocks` `supertableblocks` ON `supertableblocks`.`id` = `subquery`.`elementsId`
INNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `stc_columns` `content` ON `content`.`id` = `subquery`.`contentId`
ORDER BY `supertableblocks`.`sortOrder` in /home/matthias/craft/hbs/vendor/yiisoft/yii2/db/Schema.php:664
```

**Comment by janhenckens** [comment]
Getting an error issue on ST 2.1.3 here.

**Comment by ccchapman** [comment]
I am having a SQL error on Super Table 2.1.3 and CraftCMS 3.1.2.1.

```
Database Exception – yii\db\Exception
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'craftcms.craft_stc_mainblock' doesn't exist
The SQL being executed was: SELECT `elements`.`id`, `elements`.`fieldLayoutId`, `elements`.`uid`, `elements`.`enabled`, `elements`.`archived`, `elements`.`dateCreated`, `elements`.`dateUpdated`, `elements_sites`.`slug`, `elements_sites`.`uri`, `elements_sites`.`enabled` AS `enabledForSite`, `supertableblocks`.`fieldId`, `supertableblocks`.`ownerId`, `supertableblocks`.`ownerSiteId`, `supertableblocks`.`typeId`, `supertableblocks`.`sortOrder`, `content`.`id` AS `contentId`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`
FROM `craft_elements` `elements`
INNER JOIN `craft_supertableblocks` `supertableblocks` ON `supertableblocks`.`id` = `elements`.`id`
INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `craft_stc_mainblock` `content` ON `content`.`elementId` = `elements`.`id`
WHERE (`supertableblocks`.`fieldId`='32') AND (`supertableblocks`.`ownerId`='3') AND (`elements_sites`.`siteId`=1) AND (`content`.`siteId`=1) AND (`elements`.`archived`=FALSE) AND (`elements`.`enabled`=TRUE) AND (`elements`.`dateDeleted` IS NULL) AND (`elements_sites`.`enabled`=TRUE)
ORDER BY `supertableblocks`.`sortOrder`) `subquery`
INNER JOIN `craft_supertableblocks` `supertableblocks` ON `supertableblocks`.`id` = `subquery`.`elementsId`
INNER JOIN `craft_elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `craft_stc_mainblock` `content` ON `content`.`id` = `subquery`.`contentId`
ORDER BY `supertableblocks`.`sortOrder`
```

**Comment by engram-design** [comment]
@mgrandl @janhenckens @ccchapman I believe this should be addressed in the latest release (hopefully to finalise this issue) of [2.1.4](https://github.com/verbb/super-table/releases/tag/2.1.4).

Apologies for the ongoing issues, and thanks for your patience. This has been a complicated underlying issue in 3.1.x with a few things going on.

Additionally, if this latest version doesn't work, you can try to re-save any Super Table fields, or fields with a Matrix + Super Table combo. But do try the latest version first.

Please let me know if there are any further issues.

**Comment by juddlyon** [comment]
@engram-design Thank you for your attentiveness and awesome add-ons.

**Comment by engram-design** [comment]
Additionally, [2.1.5](https://github.com/verbb/super-table/releases/tag/2.1.5), introduces a new "Content Table Checker/Fixer" which I'd recommend people run via `http://mysite.com/actions/super-table/plugin/check-content-tables` to ensure everything is okay. This check won't write any changes, but will give you the opportunity to do so if any errors our found.

If any errors are found, you can run the fixer. Database backups are triggered before the fixer runs as well, just in case something goes wrong at that point.

**Comment by ghost** [comment]
@engram-design hmm weird the tool managed to fix some errors in my dev environment, but it doesn't work in my production environment. after i tried the fixer from the dev env on the production environment it also doesn't seem to work. now I guess I am probably fucked and will have to add all the corrupted content manually again...
