### ISSUE TITLE
Server error when importing project.yaml from different branch

### ISSUE THREAD

**Issue by TobiasDax** [engram-design/SuperTable#226]
### Description
After my last problem with updating SuperTables (#224 ) i setup a previous backup and managed to get an update to the latest versions of Craft and Super Tables working.

After that i wanted to import a backup of the project.yaml that contained a lot of changes i did since the backup.

After Craft informs me, that i need to update the configuration, it runs into an error:

> Status:  Internal Server Error
>
> Antwort: {"error":"Unable to save a Super Table field’s settings without knowing its content table."}

After that i can reload the CP and it has imported most of my Fields. But a lot are missing. Mostly Matrix fields inside super table.

### Steps to reproduce

1. import project.yaml with a lot of content
2. wait for the error
3. reload CP
4. look for missing fields

### Additional info

- Plugin version: 2.1.4.2
- Craft version: 3.1.2.2

**Comment by engram-design** [comment]
Are you able to share your project config file (happy to so so over the Craft Slack if you prefer - handle "crawf"). It's possible there's an issue with the field structure in that project config file.

**Comment by engram-design** [comment]
It looks like there might have been an issue before the project config was enabled, but trying to fix it after the fact can be a bit tricky.

Would you be able to try removing the `useProjectConfigFile` config setting and delete your `config/project.yaml` file temporarily? Then update to [2.1.5](https://github.com/verbb/super-table/releases/tag/2.1.5), which introduces a new "Content Table Checker/Fixer".

Run the checker via `http://mysite.com/actions/super-table/plugin/check-content-tables` to ensure everything is okay. This check won't write any changes, but will give you the opportunity to do so if any errors our found.

If any errors are found, you can run the fixer. Database backups are triggered before the fixer runs as well, just in case something goes wrong at that point.

If all went well, error-free, you can re-enabled project config.

**Comment by jesuismaxime** [comment]
Got the same issue. When I run the checker, I got a TypeError 

> Argument 1 passed to craft\db\Connection::tableExists() must be of the type string, null given, called in /[...]/vendor/verbb/super-table/src/controllers/PluginController.php on line 72

**Versions**
Craft : 3.1.3
Super Table: 2.1.5.2

**Comment by engram-design** [comment]
@jesuismaxime Think this should be fixed in [2.1.5.3](https://github.com/verbb/super-table/releases/tag/2.1.5.3), but let me know if not.

**Comment by engram-design** [comment]
Closing original issue, unless @TobiasDax is still having the issue, and happy to follow up.

**Comment by engram-design** [comment]
There have been a number of improvements to project config for both Super Table and Matrix in [2.1.9](https://github.com/verbb/super-table/releases/tag/2.1.9).

I've also added a new settings page for the checker/fixer, along with making sure to check for the correct columns in Super Table content tables.
