### ISSUE TITLE
Return value of ...\SuperTableBlockElement::getContentTable() must be of the type string, null returned

### ISSUE THREAD

**Issue by outline4** [engram-design/SuperTable#228]
### Description

I've upgraded from version 3.0.20 to the latest craft version 3.1.3.  
After the cms update there was an update to super table available (2.1.5). 
I've installed that too, but this broke some things.

### Steps to reproduce

Now if I try to save any entry that has a super table field (in my case with an asset field inside) it will generate the following error: 

	TypeError
	
	Return value of verbb\supertable\elements\SuperTableBlockElement::getContentTable() must be of the type string, null returned
	
When I leave the super table field empty, it saves without a problem. 

halp :)

**Comment by engram-design** [comment]
The transition to 3.1 was a bit tricky, because it requires both Craft and Super Table to be updated at the same time. It sounds like you might've done Craft first, then Super Table?

Can you head to `/actions/super-table/plugin/check-content-tables` and let me know the output of this? This should determine any issues with relation to Super Table's content tables caused by the update.

**Comment by outline4** [comment]
Hi, Thanks for the quick reply. 
Where do I have to go exactely? Is this an url? 
https://www.mysite.com/index.php?p=backend/actions/super-table/plugin/check-content-tables

I only get a white page...

**Comment by outline4** [comment]
In fact, I’ve updated Super Table first, then Craft. After that there was a new update available, then I’ve installed this update and that’s where the problems began.

**Comment by engram-design** [comment]
Yep, that's the one, it should just be off your main site url - `https://mysite.com/actions/super-table/plugin/check-content-tables`. That's interesting how its a blank page.

If you want to try going to: `https://mysite.com/actions/super-table/plugin/fix-content-tables` to just try and automatically fix things? It'll take a backup first FYI.

**Comment by outline4** [comment]
I did that, but there's still only a blank page and the problem remains...

**Comment by engram-design** [comment]
@outline4 Please note they're two different links:

`https://mysite.com/actions/super-table/plugin/check-content-tables` and `https://mysite.com/actions/super-table/plugin/fix-content-tables`

They both have blank pages?

**Comment by outline4** [comment]
yep... both blank pages...

**Comment by engram-design** [comment]
Are you using project config for your site? If so, can you share the contents?

Also, available on the Craft Slack (handle "crawf") if you're on there and would like some easier debugging.

**Comment by outline4** [comment]
I am very new to 3.1 and project config... where would I find this? 

Sorry I am not on slack anymore...

**Comment by engram-design** [comment]
For Craft 3.1, its opt-in, so unless you've added `useProjectConfigFile` to your general.php file, it'll be off. Can you confirm if you're using it?

Otherwise, would you be able to your database, and go to the `fields` table. Find the name of your field and send through the row of information for this field? In particular, I'm interested in the settings columns's content.

Finally, is this just a Super Table field with an Asset field (no Neo, Matrix or Spoon involvement)?

**Comment by outline4** [comment]
I've added the useProjectConfigFile to general.php. 
Here's the file: 
[project.yaml.txt](https://github.com/verbb/super-table/files/2781282/project.yaml.txt)

**Comment by engram-design** [comment]
@outline4 Thanks for this, can let me know what version of Super Table you had installed previously?

**Comment by outline4** [comment]
The same error is generated when inside a neo matrix or as a standalone field. 

here's the database line for the field:
<img width="795" alt="bildschirmfoto 2019-01-22 um 04 40 39" src="https://user-images.githubusercontent.com/145828/51512887-0f7a0900-1e00-11e9-8a0b-c56068304855.png">

I think I had super table v2.1.4 installed.

**Comment by engram-design** [comment]
Would you be able to update to [2.1.5.1](https://github.com/verbb/super-table/releases/tag/2.1.5.1), and then run `https://mysite.com/actions/super-table/plugin/check-content-tables`?

**Comment by outline4** [comment]
I did that and the output is: 

	
	> ERROR: Super Table field #37 is missing its content table in settings ...
	> ERROR: Super Table field #242 is missing its content table in settings ...
	> ERROR: Super Table field #258 is missing its content table in settings ...
	> ERROR: Super Table field #262 is missing its content table in settings ...
	> ERROR: Super Table field #192 is missing its content table in settings ...
	> ERROR: Super Table field #197 is missing its content table in settings ...
	> ERROR: Super Table field #201 is missing its content table in settings ...
	> ERROR: Super Table field #216 is missing its content table in settings ...
	> ERROR: Super Table field #228 is missing its content table in settings ...

	Fix the above errors by running the Super Table content table fixer.

Should I run the fixer?

**Comment by engram-design** [comment]
Great, glad its picked up stuff correctly now! Yep, go ahead and run the fixer.

**Comment by outline4** [comment]
I've ran the fixer and the output is something like this: 

	> Trying to create missing content table for #37 ...
	> Generated table name {{%stc_cf_social_table}} ...
	> update in {{%fields}} ... done (time: 0.016s)
	> Local field table name {{%stc_cf_social_table}} ...
	Exception: Unable to save a Super Table field’s settings without knowing its content table. (/../vendor/verbb/super-table/src/services/SuperTableService.php:566)
	#0 /../vendor/verbb/super-table/src/fields/SuperTableField.php(740): verbb\supertable\services\SuperTableService->saveSettings(Object(verbb\supertable\fields\SuperTableField), false)
	#1 /../vendor/craftcms/cms/src/services/Fields.php(1519): verbb\supertable\fields\SuperTableField->afterSave(false)
	#2 /../vendor/craftcms/cms/src/services/Fields.php(817): craft\services\Fields->applyFieldSave('1de6216c-22a0-4...', Array, 'global')
	#3 /../vendor/craftcms/cms/src/services/ProjectConfig.php(815): craft\services\Fields->handleChangedField(Object(craft\events\ConfigEvent))
	#4 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
	#5 /../vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
	#6 /../vendor/craftcms/cms/src/services/ProjectConfig.php(517): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
	#7 /../vendor/craftcms/cms/src/helpers/ProjectConfig.php(63): craft\services\ProjectConfig->processConfigChanges('fields.1de6216c...')
	#8 /../vendor/verbb/super-table/src/services/SuperTableService.php(315): craft\helpers\ProjectConfig::ensureAllFieldsProcessed()
	#9 /../vendor/craftcms/cms/src/services/ProjectConfig.php(815): verbb\supertable\services\SuperTableService->handleChangedBlockType(Object(craft\events\ConfigEvent))
	#10 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
	#11 /../vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
	#12 /../vendor/craftcms/cms/src/services/ProjectConfig.php(510): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
	#13 /../vendor/craftcms/cms/src/services/ProjectConfig.php(364): craft\services\ProjectConfig->processConfigChanges('superTableBlock...', true)
	#14 /../vendor/verbb/super-table/src/services/SuperTableService.php(295): craft\services\ProjectConfig->set('superTableBlock...', Array)
	#15 /../vendor/verbb/super-table/src/services/SuperTableService.php(609): verbb\supertable\services\SuperTableService->saveBlockType(Object(verbb\supertable\models\SuperTableBlockTypeModel), false)
	#16 /../vendor/verbb/super-table/src/migrations/m190120_000000_fix_supertablecontent_tables.php(182): verbb\supertable\services\SuperTableService->saveSettings(Object(verbb\supertable\fields\SuperTableField))
	#17 /../vendor/verbb/super-table/src/migrations/m190120_000000_fix_supertablecontent_tables.php(49): verbb\supertable\migrations\m190120_000000_fix_supertablecontent_tables->_createContentTable(Array, Array)
	#18 /../vendor/craftcms/cms/src/db/Migration.php(56): verbb\supertable\migrations\m190120_000000_fix_supertablecontent_tables->safeUp()
	#19 /../vendor/verbb/super-table/src/controllers/PluginController.php(32): craft\db\Migration->up()
	#20 [internal function]: verbb\supertable\controllers\PluginController->actionFixContentTables()
	#21 /../vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
	#22 /../vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
	#23 /../vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('fix-content-tab...', Array)
	#24 /../vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('fix-content-tab...', Array)
	#25 /../vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('super-table/plu...', Array)
	#26 /../vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('super-table/plu...', Array)
	#27 /../vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
	#28 /../vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
	#29 /../public_html/index.php(24): yii\base\Application->run()
	#30 {main}
	
	Fixes complete.

But when I try to save an entry, the same error occurs. 

	TypeError
	
	Return value of verbb\supertable\elements\SuperTableBlockElement::getContentTable() must be of the type string, null returned

**Comment by engram-design** [comment]
You might want to remove the `useProjectConfigFile` config setting and delete the `config/project.yaml` file before running the fixer, as that error shown means it hasn't worked correctly.

Can you do those things and try the fixer again?

**Comment by outline4** [comment]
YAY!
that did the trick! 

	> Super Table field #37 has content table {{%stc_cf_social_table}} ...
	> Trying to create missing content table for #242 ...
	> Generated table name {{%stc_slider}} ...
	> update in {{%fields}} ... done (time: 0.005s)
	> Local field table name {{%stc_slider}} ...
	> Updated Super Table field after content table creation ...
	
	> Trying to create missing content table for #258 ...
	> Generated table name {{%stc_iconlist}} ...
	> update in {{%fields}} ... done (time: 0.003s)
	> Local field table name {{%stc_iconlist}} ...
	> Updated Super Table field after content table creation ...
	
	> Trying to create missing content table for #262 ...
	> Generated table name {{%stc_linklist}} ...
	> update in {{%fields}} ... done (time: 0.004s)
	> Local field table name {{%stc_linklist}} ...
	> Updated Super Table field after content table creation ...
	
	> Trying to create missing content table for #192 ...
	> Generated table name {{%stc_39_slider}} ...
	> update in {{%fields}} ... done (time: 0.005s)
	> Local field table name {{%stc_39_slider}} ...
	> Updated Super Table field after content table creation ...
	
	> Trying to create missing content table for #197 ...
	> Generated table name {{%stc_40_iconlist}} ...
	> update in {{%fields}} ... done (time: 0.004s)
	> Local field table name {{%stc_40_iconlist}} ...
	> Updated Super Table field after content table creation ...
	
	> Trying to create missing content table for #201 ...
	> Generated table name {{%stc_41_linklist}} ...
	> update in {{%fields}} ... done (time: 0.004s)
	> Local field table name {{%stc_41_linklist}} ...
	> Updated Super Table field after content table creation ...
	
	> Trying to create missing content table for #216 ...
	> Generated table name {{%stc_42_content_matrix_left}} ...
	> update in {{%fields}} ... done (time: 0.004s)
	> Local field table name {{%stc_42_content_matrix_left}} ...
	> Updated Super Table field after content table creation ...
	
	> Trying to create missing content table for #228 ...
	> Generated table name {{%stc_42_content_matrix_right}} ...
	> update in {{%fields}} ... done (time: 0.005s)
	> Local field table name {{%stc_42_content_matrix_right}} ...
	> Updated Super Table field after content table creation ...
	
	
	Fixes complete.

Thanks a lot for helping!

**Comment by engram-design** [comment]
Not a problem, and appreciate your patience!

**Comment by outline4** [comment]
Hi, it's me again. 

This time I've upgraded a craft cms 2.7 site to craft cms 3.2.3
The same error as stated when I try to save an entry. 

I am on craft 3.2.3 and superTable 2.2.1 locally with MAMP

I've tried your link (https://mysite.com/actions/super-table/plugin/check-content-tables), but it generates a 503 error.

Then, I've discovered that you can Check Content Tables in the settings of super Table. 

Did that: 

	> ERROR: Super Table field #162 is missing its content table in settings ...
	> ERROR: Super Table field #177 is missing its content table in settings ...

Then I've fixed the tables

	> Trying to create missing content table for #162 ...
	> Generated table name {{%stc_auswahltage}} ...
	> update in {{%fields}} ... done (time: 0.006s)
	> Content table {{%stc_auswahltage}} already exists, skipping ...
	
	> Trying to create missing content table for #177 ...
	> Generated table name {{%stc_cf_veranstaltungslinks_table}} ...
	> update in {{%fields}} ... done (time: 0.001s)
	> Content table {{%stc_cf_veranstaltungslinks_table}} already exists, skipping ...
	
	> Super Table field #183 has content table {{%stc_cf_veranstaltungsdatum_table_1}} ...
	
	Fixes complete.

And finally resaved the tables

BUT: 

All the super Table fields are empty :(
(it's mostly date and time fields with some lightswitch fields) 

Any help appreciated! 

–
Stefan
