### ISSUE TITLE
Column widths are incorrect when syncing with project.yaml

### ISSUE THREAD

**Issue by darylknight** [engram-design/SuperTable#230]
### Description
Changing a field locally and saving it with project.yaml updates the fields of Super Table on the staging server, but it gets the column widths the wrong way round

### Steps to reproduce

1. Change a column width locally
2. Update staging server project.yaml
3. Server version shows the correct fields, but the column width applies to the wrong field

In the screenshot, my local dev machine is on the left, staging on the right

![image](https://user-images.githubusercontent.com/1250017/51548040-27897100-1e70-11e9-874d-b8520e8fe6bc.png)

### Additional info

- Plugin version: 2.1.5.2 (2.1.5.3 isn't showing in composer still)
- Craft version: 3.1.3

**Comment by engram-design** [comment]
Would you be able to look at your project.yaml file, and find the Super Table field(s) to share its content? Looking to see what the field settings are showing (potentially incorrectly)

**Comment by darylknight** [comment]
![image](https://user-images.githubusercontent.com/1250017/51595772-2738b680-1f00-11e9-9a5e-d57fabe167c9.png)

It looks like it's incorrect in both files, even though it's displaying correctly on the local . machine

**Comment by engram-design** [comment]
Closing due to age, and likely project config issues itself.
