### ISSUE TITLE
Can't enable Redactor field in Supertable after upgrade

### ISSUE THREAD

**Issue by janhenckens** [engram-design/SuperTable#233]
### Description
We're upgrading/updating a site from Craft 2 to Craft 3 and have the following issue with our Supertable fields.
With the Redactor plugin installed, Supertable fields still show the  "Support for Redactor has moved to a plugin" warning, and clicking "Enable" just refreshes the page without any error messages.

![screen shot 2019-01-28 at 17 01 46](https://user-images.githubusercontent.com/755428/51849310-b5a5a180-231f-11e9-8651-a3fb5c000c26.png)

Other Redactor fields show up as expected, with their content from the Craft 2 site.

### Additional info

- Plugin version: 2.1.5.3
- Craft version: 3.1.5

**Comment by engram-design** [comment]
Strange, Super Table doesn't treat this any different compared to other fields.

Can you look in your fields database table and see if there are any rows with the value for `type` to either `RichText` or `craft\\fields\\RichText`?

**Comment by janhenckens** [comment]
The field in question here (`Omschrijving`) is still listed as `craft\fields\MissingField`, there aren't any rows with type containing `RichText` in the fields table.

**Comment by engram-design** [comment]
Should be fixed in [2.1.6](https://github.com/verbb/super-table/releases/tag/2.1.6)

**Comment by janhenckens** [comment]
Thanks Josh!
