### ISSUE TITLE
How do I completely remove the Super Table plugin from Craft?

### ISSUE THREAD

**Issue by ryanpcmcquen** [engram-design/SuperTable#234]
### Description
I am no longer using this plugin, and would like to remove it. I have uninstalled it but it seems there are still some trace elements in the database. I'd like to know all the touch points I should be looking for to completely uninstall the Super Table plugin.

Thank you!

**Comment by engram-design** [comment]
Super Table doesn't remove itself from Craft installs, just as a bit of an opinionated fail-safe in case data is lost. I've been on the fence about this for some time just FYI, and many people have made cases for or against this.

But - you'll just need to manually delete some tables from the database:
- Any `stc_*` or `supertablecontent_*` tables - this is where your content is stored.
- `supertableblocks` table
- `supertableblocktypes` table
- Any elements in `elements` with `type = 'verbb\supertable\elements\SuperTableBlockElement'`
- Any fields in `fields` with `type = 'verbb\supertable\fields\SuperTableField'`
- Any fields in `fields` with `context starts with superTableBlockType:*`
- Any rows in `fieldlayouts` with `type = 'verbb\supertable\elements\SuperTableBlockElement'`

**Comment by ryanpcmcquen** [comment]
@engram-design, I am also seeing some rows in `fieldlayouts` with the type: `verbb\supertable\elements\SuperTableBlockElement`

**Comment by ryanpcmcquen** [comment]
@engram-design, and some in the `elements` table as well, with the type: `verbb\supertable\elements\SuperTableBlockElement`

**Comment by engram-design** [comment]
@ryanpcmcquen Ah yes, good point!

**Comment by ryanpcmcquen** [comment]
@engram-design, are there any others I missed?

**Comment by engram-design** [comment]
@ryanpcmcquen Nope, I believe that's it.

**Comment by ryanpcmcquen** [comment]
@engram-design, looks like `resourcepaths` also gets touched.

**Comment by ryanpcmcquen** [comment]
Also, there is a reference to `supertable` in the `info` table, but that doesn't look like something that should be deleted.

**Comment by engram-design** [comment]
Well, at that point it depends on how thorough you want to be. For instance, Super Table content will likely still be in your search index table, and template caches tables. I would say its pretty harmless as a resource path.

And if you're using, or have used project config, you'll have references to that in the info table, but will require manual editing (or your could edit your project.yaml file)

**Comment by engram-design** [comment]
Closing after adjustments to original answer.
