### ISSUE TITLE
Column not found: 1054 Unknown column 'deletedWithOwner' error

### ISSUE THREAD

**Issue by alexroper** [engram-design/SuperTable#237]
### Description

Deleting an entry with Super Table data or deleting a row from a Super Table field and saving the entry results in an error. Operation does not complete.

### Steps to reproduce

1. Delete an entry that uses a Super Table field.
2. Control panel shows "An unknown error occurred" alert at the top of the screen.

OR

1. Delete a row from a Super Table field.
2. Try to save the entry.
3. Control panel shows "Internal Server Error. Server Error."

### Additional info

Here's the error I think that's relevant from the web.log file:

```log
2019-02-05 03:26:08 [-][1][-][error][yii\db\Exception] PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'deletedWithOwner' in 'field list' in /path-redacted/vendor/yiisoft/yii2/db/Command.php:1258

Next yii\db\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'deletedWithOwner' in 'field list'
The SQL being executed was: UPDATE `craft_supertableblocks` SET `deletedWithOwner`=TRUE WHERE `id`='101' in /path-redacted/vendor/yiisoft/yii2/db/Schema.php:664
```

- Plugin version: 2.1.6
- Craft version: 3.1.6.1

**Comment by engram-design** [comment]
Hmmm, it looks like this migration (https://github.com/verbb/super-table/blob/aea6b9b6bee7f3470b41415ef694f4cc7a8cbd79/src/migrations/m190117_000000_soft_deletes.php) hasn't gone through for some reason.

Would you be able to check your `migrations` db table for `m190117_000000_soft_deletes`? It sounds like this didn't get processed for some reason...

**Comment by alexroper** [comment]
There is a row for `m190117_000000_soft_deletes` in the `craft_migrations` table.

<img width="1022" alt="screen shot 2019-02-05 at 11 31 13 am" src="https://user-images.githubusercontent.com/377542/52299221-c070bf80-2939-11e9-9319-258840758938.png">

Should I try to re-run migrations from the command line?

**Comment by engram-design** [comment]
It might be worth a shot - what does your `supertableblocks` table look like?

You could almost certainly add this column yourself (screenshot), but I'd be good to get to the bottom of why this hasn't done through this migration...

![image](https://user-images.githubusercontent.com/1221575/52299956-d71b2300-29da-11e9-8e69-8d6a1ff69ccc.png)

**Comment by alexroper** [comment]
Running `./craft migrate/all` from the command line doesn't help. 

Is there a way I can re-run a plugin's migrations?

Here's what my `craft_supertablebocks` looks like:

<img width="851" alt="screen shot 2019-02-05 at 1 11 08 pm" src="https://user-images.githubusercontent.com/377542/52304441-9920ef00-2947-11e9-9465-004004a07195.png">

**Comment by alexroper** [comment]
Also here's everything in the `migrations` table for the Super Table plugin:

<img width="1041" alt="screen shot 2019-02-05 at 1 16 14 pm" src="https://user-images.githubusercontent.com/377542/52304765-4b58b680-2948-11e9-930b-e74cb3273be9.png">

**Comment by alexroper** [comment]
Now that I think about it, I got a weird 500 internal server error when installing some plugins thru the control panel. I thought it was some timeout with Composer. But then everything seemed to be installed. So it's possible these migrations didn't actually successfully run?

Should I try to uninstall and re-install?

**Comment by engram-design** [comment]
You can re-run a migration by deleting the associated row from the `migrations` table, and then I believe running `./craft migrate/all` _should_ trigger it to run.

And yeah, its likely that 500 error could be the issue.

Uninstall/Install wouldn't work in this instance i'm afraid, as Super Table doesn't remove tables after uninstalling, and therefore won't add the new, correct tables.

**Comment by alexroper** [comment]
Great. I deleted all the row for Super Table in migrations and re-ran the migrations. 

The `./craft migrate/all` command didn't work tho. I had to migrate the plugin specifically with `./craft migrate/up --plugin=super-table`.

Seems to be working now. The `supertableblocks` table now has  a column for `deletedWithOwner`.

Thanks!

**Comment by engram-design** [comment]
Thanks for the follow up and clarification. Definitely seems due to the migration error this didn't run fully.

**Comment by siffring** [comment]
Thanks for documenting the solution @alexroper. I had the same problem and that same migration script fixed it (after I removed those rows from the migration table).

FWIW, I had run the plugin update via the control panel and was also greeted with a 500 error when it was done. I've seen that almost every time I run Craft updates lately, but everything else seems to work fine if I go back to the control panel after getting the error.

**Comment by proimage** [comment]
For what it's worth, I had nearly the same exact error, just with Neo instead of Super Table. The same procedure—deleting Neo's `soft_deletes`-related row in migrations and running `./craft migrate/up --plugin=neo`—fixed it as well.

**Comment by kr37** [comment]
I had the same issue with Super Table version 2.4.9. The same solution worked a charm: delete `m190117_000000_soft_deletes` and run `./craft migrate/up --plugin=super-table`. Thank you for the beautiful writeup!
