### ISSUE TITLE
Update Super Table

### ISSUE THREAD

**Issue by pette87** [engram-design/SuperTable#239]
### Description
When I use "composer update" in console, I have following issue:

> Your requirements could not be resolved to an installable set of packages.  

> Problem 1
>     - verbb/super-table 2.1.6 requires craftcms/cms ^3.1.2 -> satisfiable by craftcms/cms[3.1.2, 3.1.2.1, 3.1.2.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.6.1, 3.1.7, 3.1.8] but these conflict with your requirements or minimum-stability.
>     - verbb/super-table 2.1.5.3 requires craftcms/cms ^3.1.2 -> satisfiable by craftcms/cms[3.1.2, 3.1.2.1, 3.1.2.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.6.1, 3.1.7, 3.1.8] but these conflict with your requirements or minimum-stability.
>     - verbb/super-table 2.1.5.2 requires craftcms/cms ^3.1.2 -> satisfiable by craftcms/cms[3.1.2, 3.1.2.1, 3.1.2.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.6.1, 3.1.7, 3.1.8] but these conflict with your requirements or minimum-stability.
>     - verbb/super-table 2.1.5.1 requires craftcms/cms ^3.1.2 -> satisfiable by craftcms/cms[3.1.2, 3.1.2.1, 3.1.2.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.6.1, 3.1.7, 3.1.8] but these conflict with your requirements or minimum-stability.
>     - verbb/super-table 2.1.5 requires craftcms/cms ^3.1.2 -> satisfiable by craftcms/cms[3.1.2, 3.1.2.1, 3.1.2.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.6.1, 3.1.7, 3.1.8] but these conflict with your requirements or minimum-stability.
>     - verbb/super-table 2.1.4.3 requires craftcms/cms ^3.1.2 -> satisfiable by craftcms/cms[3.1.2, 3.1.2.1, 3.1.2.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.6.1, 3.1.7, 3.1.8] but these conflict with your requirements or minimum-stability.
>     - verbb/super-table 2.1.4.2 requires craftcms/cms ^3.1.2 -> satisfiable by craftcms/cms[3.1.2, 3.1.2.1, 3.1.2.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.6.1, 3.1.7, 3.1.8] but these conflict with your requirements or minimum-stability.
>     - verbb/super-table 2.1.4.1 requires craftcms/cms ^3.1.2 -> satisfiable by craftcms/cms[3.1.2, 3.1.2.1, 3.1.2.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.6.1, 3.1.7, 3.1.8] but these conflict with your requirements or minimum-stability.
>     - verbb/super-table 2.1.4 requires craftcms/cms ^3.1.2 -> satisfiable by craftcms/cms[3.1.2, 3.1.2.1, 3.1.2.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.6.1, 3.1.7, 3.1.8] but these conflict with your requirements or minimum-stability.
>     - verbb/super-table 2.1.3 requires craftcms/cms ^3.1.2 -> satisfiable by craftcms/cms[3.1.2, 3.1.2.1, 3.1.2.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.6.1, 3.1.7, 3.1.8] but these conflict with your requirements or minimum-stability.
>     - verbb/super-table 2.1.2 requires craftcms/cms ^3.1.2 -> satisfiable by craftcms/cms[3.1.2, 3.1.2.1, 3.1.2.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.6.1, 3.1.7, 3.1.8] but these conflict with your requirements or minimum-stability.
>     - verbb/super-table 2.1.1 requires craftcms/cms ^3.1.2 -> satisfiable by craftcms/cms[3.1.2, 3.1.2.1, 3.1.2.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.6.1, 3.1.7, 3.1.8] but these conflict with your requirements or minimum-stability.
>     - verbb/super-table 2.1.0 requires craftcms/cms ^3.1.0 -> satisfiable by craftcms/cms[3.1.0, 3.1.0-beta.1, 3.1.0-beta.2, 3.1.0-beta.3, 3.1.0-beta.4, 3.1.0-beta.5, 3.1.0-beta.5.1, 3.1.0-beta.6, 3.1.0-beta.7, 3.1.1, 3.1.2, 3.1.2.1, 3.1.2.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.6.1, 3.1.7, 3.1.8] but these conflict with your requirements or minimum-stability.
>     - Installation request for verbb/super-table ^2.1 -> satisfiable by verbb/super-table[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.4.1, 2.1.4.2, 2.1.4.3, 2.1.5, 2.1.5.1, 2.1.5.2, 2.1.5.3, 2.1.6].

I can't update Craft CMS 3 from 3.0.40 to 3.1 and I can't see Super Table on Craft CMS 3 Update overview page.

Can anyone help?

### Additional info

- Plugin version: dev-craft-3
- Craft version: 3.0.40

**Comment by engram-design** [comment]
What are your version values in your composer.json for super-table and craft? If you're trying to load the latest dev-craft-3, you'll need to also install Craft 3.1.x. It sounds like you might be trying to install the latest Super Table for Craft 3.0.x which isn't compatible.

FYI, if you had something like `"super-table": "^2.0"`, it'd install the latest compatible version for your other constraints.

**Comment by pette87** [comment]
Ok, now I have update Super Table to 2.0.14

But the problem is the same. Craft 3.1 can't install because Super Table is not 2.1.x
Otherwise I can't update Super Table to 2.1, because required Craft 3.1

When I deactivat Super Table, alls settings are lost in database or?

**Comment by engram-design** [comment]
It comes down to what you have in your composer.json file. You should have something like"
```
"craftcms/cms":"^3.1.0",
"verbb/super-table":"^2.1.0",
```

If you're updating from the control panel, you'll need to update all your plugins at the same time, because you can't install one without having it throw issues due to an incompatibility with the other.
