### ISSUE TITLE
Querying relationships through a Super Table field

### ISSUE THREAD

**Issue by benjaminkohl** [engram-design/SuperTable#240]
### Description

I feel like I asked about this somewhere else in the past but I can't find evidence of it so I am bringing it up here. I'm using the Craft 2 version of Super Table and I am trying to query entries that relate to another entry through a relationship field that exists in a Super Table field. Is that possible?

### Steps to reproduce

I was guessing at using something similar to Craft's eager-loading syntax but this doesn't appear to work. Is there a way to do this without creating a huge array of ID -> entry maps after looping through them all? Worst-case scenario, I'll create a template variable in our custom plugin to do a single query to get the IDs of entries that relate to the "entryInTheRelationshipField" entry in the example below.

```
{% set criteria = criteria|merge({'relatedTo' : {
	'targetElement': entryInTheRelationshipField,
	'field': 'superTableFieldHandle.relationshipFieldHandle'
}}) %}
```

### Additional info

- Plugin version: 1.0.6
- Craft version: 2.7.4

**Comment by engram-design** [comment]
Yep, so its a little complicated, and a roll-own-own approach, as Craft 2 didn't have a great deal of flexibility with relationship matching. There are some specific cases in Craft's core relationship handling when it comes to Matrix out of the box, but its not the same for Super Table.

There's a special function that might be useful here - https://verbb.io/craft-plugins/super-table/docs/template-guides/available-variables#craft-superTable-getRelatedElements

**Comment by engram-design** [comment]
Closing due to age/Craft 2.
