### ISSUE TITLE
Running Content Table Fixer does not migrate fields within Matrix correctly

### ISSUE THREAD

**Issue by jwb009** [engram-design/SuperTable#242]
### Description
I upgraded from Craft 2 to Craft 3. The upgrade went ok and the site is functional and all the content is in tact in the control panel. Then I checked the content tables using the handy tool. It had a bunch of missing fields. I clicked 'fix' and everything seemed to go ok. Go back to any entry, and all the super table fields are still there, but empty.  

Example output:
`> Trying to create missing content table for #88 ...
> Generated table name {{%stc_randomizedfeaturephotos}} ...
> update in {{%fields}} ... done (time: 0.002s)
> Local field table name {{%stc_randomizedfeaturephotos}} ...
> Updated Super Table field after content table creation ...

> Trying to create missing content table for #149 ...
> Generated table name {{%stc_featuredimage}} ...
> update in {{%fields}} ... done (time: 0.002s)
> Local field table name {{%stc_featuredimage}} ...
> Updated Super Table field after content table creation ...

> Trying to create missing content table for #168 ...
> Generated table name {{%stc_brandmessage}} ...
> update in {{%fields}} ... done (time: 0.003s)
> Local field table name {{%stc_brandmessage}} ...
> Updated Super Table field after content table creation ...`

I can see the new rows created in the database (i.e. _craft_stc_39_image_), but they are empty. The old rows (i.e. _craft_supertablecontent_39_image_) is also still there, and populated correctly.

edit 3: Just noticed that the fields that migrate incorrectly are all Super Table fields inside a Matrix field

### Steps to reproduce

1. Upgrade from Craft 2 to Craft 3
2. Run Content Table Checker and Fix errors
3. Find super table fields empty

### Additional info

- Plugin version: Super Table 2.1.6
- Craft version: 3.1.8

**Comment by engram-design** [comment]
Thanks for this. FYI, the old tables are there as a bit of a backup.

Can I ask what version of Craft and Super Table you were upgrading from?

Might need to see if I can grab a copy (even a cut-down version) of your database to help fix this. If you're on the Craft Slack, I'm happy to see what I can do (handle `crawf`).

**Comment by jwb009** [comment]
Thanks for the reply, I'm going from 2.7.2 to 3.1.8 and Super Table 1.0.6 to 2.1.6

**Comment by engram-design** [comment]
This was due to an outdated migration from Craft 2 > 3.0.x, which worked at the time, but causes undesired issues when going straight to 3.1.x. The migration itself is fixed for future reference.

However, you'll need to run the checker/fixer again, and it should sort out those tables for you. You could also manually delete the `craft_stc_39_image` and rename the `craft_supertablecontent_39_image` as a valid option.

Give https://github.com/verbb/super-table/releases/tag/2.1.7 a try, and let me know if there's any issues!

**Comment by jwb009** [comment]
Thanks for the update! Unfortunately, the same issue is happening with 2.1.7. after running the fixer. 
Also, if I try to rename the table I run into this: 
```SQLSTATE[42S22]: Column not found: 1054 Unknown column 'content.siteId' in 'where clause'
The SQL being executed was: SELECT `elements`.`id`, `elements`.`fieldLayoutId`, `elements`.`uid`, `elements`.`enabled`, `elements`.`archived`, `elements`.`dateCreated`, `elements`.`dateUpdated`, `elements_sites`.`slug`, `elements_sites`.`uri`, `elements_sites`.`enabled` AS `enabledForSite`, `supertableblocks`.`fieldId`, `supertableblocks`.`ownerId`, `supertableblocks`.`ownerSiteId`, `supertableblocks`.`typeId`, `supertableblocks`.`sortOrder`, `content`.`id` AS `contentId`, `content`.`field_caption`, `content`.`field_sizing`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`
FROM `craft_elements` `elements`
INNER JOIN `craft_supertableblocks` `supertableblocks` ON `supertableblocks`.`id` = `elements`.`id`
INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `craft_stc_39_image` `content` ON `content`.`elementId` = `elements`.`id`
WHERE (`supertableblocks`.`fieldId`='178') AND (`supertableblocks`.`ownerId`='7172') AND (`elements_sites`.`siteId`=1) AND (`content`.`siteId`=1) AND (`elements`.`archived`=FALSE) AND (`elements`.`dateDeleted` IS NULL)
ORDER BY `supertableblocks`.`sortOrder`) `subquery`
INNER JOIN `craft_supertableblocks` `supertableblocks` ON `supertableblocks`.`id` = `subquery`.`elementsId`
INNER JOIN `craft_elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `craft_stc_39_image` `content` ON `content`.`id` = `subquery`.`contentId`
ORDER BY `supertableblocks`.`sortOrder`
Error Info: Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'content.siteId' in 'where clause'
)
↵
Caused by: PDOException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'content.siteId' in 'where clause'
in /home/forge/staging.site.com/vendor/yiisoft/yii2/db/Command.php at line 1258```

**Comment by jwb009** [comment]
Update: Everything went fine--as you predicted--when I tried updating from Craft 2 > Craft 3.0.40 > 3.1.8 (and of course Super Table 1.0.6 > ^2.0 > 2.1.7 )

**Comment by engram-design** [comment]
Were any errors thrown in the checker/fixer? Does that SQL error pop up when viewing the Super Table field in an entry, the field settings, or just any page?

**Comment by jwb009** [comment]
So I can't seem to replicate that earlier behavior. Updating from 2 > 3.1.8 is going perfectly now, and the fixer runs as it should with no errors. I'm not really sure what changed, but I think you can close this again.

Thanks again!

**Comment by engram-design** [comment]
Cool, let me know if anything else crops up!
