### ISSUE TITLE
superTableBlockTypes missing in project.yaml after update from craft 3.0 to 3.1

### ISSUE THREAD

**Issue by nettum** [engram-design/SuperTable#249]
### Description
When updating from craft 3.0 to 3.1 and enabling project.yaml, the superTableBlockTypes block is not present in the generated project.yaml.

### Steps to reproduce

1. Take backup of production database. (Craft 3.0.36, Super Table 2.0.14).
2. Import backup to local updated environment (Craft 3.1.14, Super Table 2.1.12).
3. Reload admin and press "Finish up" to run database migrations.
4. Go to Settings -> "Super Table" and run "Check Content Tables". Response is "No errors found."
5. Enable `'useProjectConfigFile' => true` in general.php and reload admin.
6. Check content of project.yaml and verify that the whole "superTableBlockTypes" and all its contents are missing:
![image](https://user-images.githubusercontent.com/798156/53427734-c5310c80-39e9-11e9-9a5f-97f1de51b7a5.png)
(this is a diff from an older checked in project.yaml file and the new generated one).
7. Try run "Check Content Tables" again in admin, just in case. It still says "No errors found.".
8. **Workaround** to get project.yaml updated again is to go into edit mode on the matrix I know the Super Table Block Types are used and re-save the matrix. Then the diff looks like this:
![image](https://user-images.githubusercontent.com/798156/53430937-cfeea000-39ef-11e9-83a1-6af1fa7100af.png)
(Don't mind all the changes, it's only the annoying boolean casting when using craft, mysql and project.yaml :man_facepalming:) 

### Additional info.

- Plugin version: 2.1.12
- Craft version: 3.1.14

**Comment by nettum** [comment]
For the record: It's no biggie for me to edit the matrix to get this working again, but I assume this *may* happen to others (and could become a problem if they don't realize it).

**Comment by engram-design** [comment]
This should likely be fixed in [2.1.13](https://github.com/verbb/super-table/releases/tag/2.1.13), introducing a missing migration for project config information.
