### ISSUE TITLE
Bug: Removing Assets from a Static Field removes the entire row

### ISSUE THREAD

**Issue by joshuapease** [engram-design/SuperTable#25]
I have a Super Table field that contains several asset fields. 

This Super Table field is set to be a Static Field. 

Whenever I try to remove an existing asset from the field, the entire row disappears. 

I had experienced this issue in the past using supertable. But I believe it's been fixed. 

The bug seems to still be lingering whenever the field is set to be a Static Field. 

I really love this plugin! And the Static Field option is a great idea. Nice way to combine a lot of sub-fields under one field and have those fields always be displayed.

**Comment by engram-design** [comment]
Does this only occur when you have the Layout set to Table and not Row? I can reproduce this issue for a table layout, but not for a row. Can you confirm this?

Glad you're liking the plugin :smiley:

**Comment by joshuapease** [comment]
Correct, this only seems to be an issue if my field is set to appear as a
table, and also set to a static field.

When the static field is set to be a row, the assets behave correctly.

One small detail I noticed. When I have multiple asset fields attached to
the table layout, only the last one ( far right ) causes the row to
disappear.

https://www.dropbox.com/s/1xy3p3zwqhn1xn6/Screenshot%202015-08-24%2010.04.21.png?dl=0

**Comment by engram-design** [comment]
Yep, thats what I was seeing as well. Fixed in the [latest release](https://github.com/engram-design/SuperTable/releases/tag/0.3.4)
