### ISSUE TITLE
Migrating from Craft 2 to 3.1 loses content matrix > super-table > matrix

### ISSUE THREAD

**Issue by roelvanhintum** [engram-design/SuperTable#250]
The content of the matrix > super-table (static) > matrix is missing after migration. I'm having some trouble debugging this.

- Plugin version: 2.1.13.1
- Craft version: 3.1.15

**Comment by engram-design** [comment]
What sort of content does your fields contain? Any third-party or Rich Text (Redactor now) fields? Testing with plain text fields results in no content loss on my end from Craft 2 to 3.1.

Can you confirm your field setup?

**Comment by roelvanhintum** [comment]
@engram-design i was trying to isolate the problem, turns out it was not super-table. The content is still available after the super-table update.
So it is probably something in the Craft-Migration-Manager plugin i'm using or the migration file it generated.
