### ISSUE TITLE
FR: Table Layout - 100% Column Width

### ISSUE THREAD

**Issue by richhayler** [engram-design/SuperTable#254]
### Description
In instances where the table layout is used and one of the columns should take all the available space (effectively "squashing" the other columns to their min widths to support their contained fields), it seems setting the column to 100% takes up with the full width of the table and the other columns are pushed outside of the table container.

Is there a better way to achieve this with super table? Even for a simple table with two columns, e.g. one dropdown and one single line text field (with the text field set to take up all available space)?

**Comment by engram-design** [comment]
Sorry for my confusion, but from the sounds of it, you want 100% with - but not true 100% width like its doing now (causing other fields to overflow)? In fact, it sounds something more similar to how a Flexbox layout might work?

Currently, Super Table fields use a table element, which is rather limiting, and is a longer-term goal to swap out with something nicer. I'll see if anything immediate can be done, but its on the radar.

**Comment by richhayler** [comment]
Sorry Josh for not explaining myself properly. What you articulated is correct though and what I’m after. In the native craft table field if you set a column width to 100% it doesn’t push the other table columns outside the table. Flexbox would be a good option longer term. I’ll have a look at the native table field and see what’s different.

**Comment by engram-design** [comment]
Very likely not going to happen (sorry), as we push towards a native Craft 4 solution.
