### ISSUE TITLE
Craft plugin install error - No plugin exists with the handle "super-table"

### ISSUE THREAD

**Issue by wautersj** [engram-design/SuperTable#258]
### Description
When installing the plugin from the craft plugin store, the cms starts updating composer, and right after that, throws the following error:

````
Status: Internal Server Error
Response: {"error":"No plugin exists with the handle \"super-table\"."}
````

### Additional info

- Plugin version: 2.1.17
- Craft version: 3.1.21.1

I'm left clueless of what to do next ...
I've updated composer, craft is the latest, ...

![Screenshot 2019-04-09 at 13 41 42](https://user-images.githubusercontent.com/4070167/55797640-455c8e80-5acd-11e9-893d-9de844a0e2c8.png)

![Screenshot 2019-04-09 at 14 17 52](https://user-images.githubusercontent.com/4070167/55799699-4cd26680-5ad2-11e9-96e9-df2215e39418.png)

**Comment by engram-design** [comment]
Was this a brand-new Craft install, or updating an existing Craft site? I assume other plugins have installed fine?

**Comment by wautersj** [comment]
This was a very recent install of Craft, my very first to be exact. I don't really have any other plugins except for the CKeditor plugin.

Turns out the Virtual machine I was hosting my project with, was underconfigured (max memory usage, and expire time) which, when improved, fixed a lot. 

Thanks for the fast reply!
