### ISSUE TITLE
Super Table in Matrix - Saving with missing required fields removes the rows

### ISSUE THREAD

**Issue by darylknight** [engram-design/SuperTable#259]
### Description
If you create a Super Table field inside a Matrix block with required fields, add some rows and try to save the entry with some required fields missing, all the content in the rows disappears instead of highlighting the fields that are missing content.

### Steps to reproduce

1. Create a Super Table field inside a matrix block
2. Make some fields inside the Super Table field required
3. Add some rows to the Super Table field inside an entry, but leave some of the required fields blank
4. Save the entry
5. Craft will say "Couldn't save entry" and the rows in the Super Table field will have disappeared

### Additional info

- Plugin version: 2.1.17
- Craft version: 3.1.21.1

**Comment by engram-design** [comment]
I can't seem to replicate this, but have done a screen recording just to check I'm doing it right? This is for a brand-new, unsaved entry.

https://www.dropbox.com/s/bnzbejrz7fephdl/st-required-fields.mov?dl=0

**Comment by darylknight** [comment]
Hey Josh,

Really appreciate you taking the time to record it - yeah, that's what I was doing. I currently can't replicate it on the site I was working on either, so I'm afraid I have no idea what caused or solved it! Thanks for looking in to it.
