### ISSUE TITLE
Matrix in a Supertable in a Matrix failing when saving new rows

### ISSUE THREAD

**Issue by bliswebagency** [engram-design/SuperTable#260]
### Description

Hi there,

In situations where a field is a Matrix -> supertable -> matrix, newly created nested matrix fields will sometimes be empty. Please see the attached video example: http://shared.bl.ms/mpkm3E

We've identified the problem as the wrong field name is being assigned to the fields inside the nested matrix. Please see here: http://shared.bl.ms/MmnbQz

In the screenshot above, the matrix's id is new1, but the nested field's name is given an index of new3. It is pulling the new3 from the index of the top level matrix, above the Super-table, when it should be new1.

As a temporary fix we've applied javascript that matches for Matrix -> supertable -> matrix fields, then checking if its name attribute contains the correct id from the parent matrix block's data-id attribute. If it's the incorrect value it replaces the name with the correct id and is then able to save correctly.

While this allows for simple content to be saved there are still issues with redactor fields in a nested matrix initializing correctly - which might also be related to naming/index issue.

### Steps to reproduce

1. Create field which is a matrix that contains a supertable that contains a matrix
2. Create new entry (please refer to video above)
3. Add a top level matrix row, add a supertable row within that, and a matrix row within that and populate the field
4. Add a new top level matrix row, add a supertable row within that, and a matrix row within that and populate the field
5. Save
6. The second matrix row's nested matrix field will be empty

### Additional info

- Plugin version: 2.1.17
- Craft version: 3.1.23

**Comment by engram-design** [comment]
Should be fixed in [2.1.18](https://github.com/verbb/super-table/releases/tag/2.1.18)

**Comment by bliswebagency** [comment]
Thank you! We've installed the 2.1.18 update and it's working now.
