### ISSUE TITLE
Rebuilding project config writes to `superTable.superTableBlockTypes` instead of just `superTableBlockTypes`

### ISSUE THREAD

**Issue by benface** [engram-design/SuperTable#261]
### Steps to reproduce

1. Execute the `./craft project-config/rebuild` command
2. Search for `superTable` in `project.yaml` and notice there are now two completely distinct sections with the exact same data: `superTable.superTableBlockTypes` and `superTableBlockTypes`

### Additional info

- Plugin version: 2.1.18
- Craft version: 3.1.24

**Comment by engram-design** [comment]
Should be fixed in [2.1.19](https://github.com/verbb/super-table/releases/tag/2.1.19)
