### ISSUE TITLE
Updating Craft 3.0 -> 3.1 Supertable

### ISSUE THREAD

**Issue by mark-chief** [engram-design/SuperTable#262]
### Description
I am working through my plugins and updating them to the latest available version before the 3.1 breakpoint and I've noticed in my composer.json file I have this version of Supertable installed. `dev-craft-3 as 2.0.8`, if I run composer update I get the error:

```Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - verbb/super-table dev-craft-3 requires craftcms/cms ^3.1.20 -> satisfiable by craftcms/cms[3.1.20, 3.1.20.1, 3.1.21, 3.1.21.1, 3.1.22, 3.1.23, 3.1.24, 3.2.0-alpha.1, 3.2.0-alpha.2, 3.2.0-alpha.2.1, 3.2.0-alpha.3, 3.2.0-alpha.4, 3.2.x-dev] but these conflict with your requirements or minimum-stability.
    - verbb/super-table dev-craft-3 requires craftcms/cms ^3.1.20 -> satisfiable by craftcms/cms[3.1.20, 3.1.20.1, 3.1.21, 3.1.21.1, 3.1.22, 3.1.23, 3.1.24, 3.2.0-alpha.1, 3.2.0-alpha.2, 3.2.0-alpha.2.1, 3.2.0-alpha.3, 3.2.0-alpha.4, 3.2.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for verbb/super-table dev-craft-3 as 2.0.8 -> satisfiable by verbb/super-table[dev-craft-3].
```

What version do I need to change this to to be compatible with the Craft 3.0 version before the 3.1 breakpoint safely with no data loss?

Thanks

**Comment by engram-design** [comment]
`dev-craft-3` will always require the latest version (3.1+), so its best not to use that. You should be able to just update your minimum requirement to `^2.0.0` in your composer.json for `verbb/super-table`, and it'll resolve the fetch the latest version for your requirements.

**Comment by mark-chief** [comment]
Thanks I'll give that a go.

Dont suppose you know the composer command to update just that package? `composer update` will update everything in my composer.json file right?

**Comment by mark-chief** [comment]
`composer update verbb/super-table`?

**Comment by engram-design** [comment]
`composer update verbb/super-table` does update a single package, but you wouldn't want to do that with the `dev-craft-3` constraint, as that'll just update to the latest branch.

You could remove the line altogether in your composer.json and run `composer require verbb/super-table` and it'll get the right version.

You could also set it to something 'safe' like `^2.0.0` and run `composer update verbb/super-table`

**Comment by mark-chief** [comment]
Thanks, super helpful as always.
