### ISSUE TITLE
Cloned Global Field Won't Save Information for One field

### ISSUE THREAD

**Issue by terryupton** [engram-design/SuperTable#265]
### Description
I have a super-table field called Address (address). I cloned this used field manager and renamed it to Registered Address (registeredAddress). When I added this to the global called CompanyInformation, so I have two superTable fields, it only retains and saves the information for the registeredAddress field. I completed the address and click save but it then blanks this out.

A small video here to illustrate the issue.
https://www.dropbox.com/s/mfatk7501jckv2w/Screen%20Recording%202019-05-02%20at%2011.52.57.mov?dl=0

### Steps to reproduce

1.  Create a field. 
2. Duplicte field using field manager and rename
3. Add both fields to a single Global
4. Enter the details 
5. Save

### Additional info

- Plugin version: 
Field Manager | 2.0.5
Super Table	2.1.18

- Craft version: 
Craft edition & version	Craft Pro 3.1.25

**Comment by terryupton** [comment]
Just to also add.
I have checked both fields and all the fields/rows and correct names are still there, both have the same row names etc (as cloned) . I have also tried re-saving both fields again but the same issue occurs I am afraid.

**Comment by engram-design** [comment]
I believe this is more of an issue with Field Manager, which is fixed in [2.0.6](https://github.com/verbb/field-manager/releases/tag/2.0.6).

You'll need to manually re-create your Super Table fields. Sorry about this.
