### ISSUE TITLE
Updating to craft 3, missing fields error

### ISSUE THREAD

**Issue by billymedia** [engram-design/SuperTable#266]
### Description
Updating to craft 3 and running "check content tables" is resulting in several errors where it claims that fields are missing.
e.g > ERROR: Unable to update {{%stc_55_steps}} as it contains missing fields. Please fix your missing fields first ...

How do i identify which field it thinks are missing? that way i can check as there are no red errors on the field listing page.

### Additional info

- Plugin version: 2.1.18
- Craft version:3.1.25

**Comment by engram-design** [comment]
This should be improved in [2.1.19](https://github.com/verbb/super-table/releases/tag/2.1.19), where it states the field ID that you need to manually re-save.
