### ISSUE TITLE
Installation via Composer

### ISSUE THREAD

**Issue by sidneywidmer** [engram-design/SuperTable#27]
unfortunately the installation via composer doesn't work out of the box. You would have to put the contents of the folder supertable directly in the root. Or is there another way?

**Comment by engram-design** [comment]
@sidneywidmer Yeah, I did realise that just after I did it, which kind of makes the whole thing a bit useless. Unfortunately, I prefer to keep the keep the plugin outside of the root, and have the plugin as a folder named correctly so its ready to go. This is just to save confusion for users in naming the plugin folder (I know its pretty simple - but still), but also to allow for things like the Readme, screenshots, and any additional files to be separate.

I'm not a big user of Composer, so not sure if there is indeed a better way to target a repo subdirectory. From my research, it looks like this isn't possible. With an upcoming (next year) Craft Plugin store, this will solve this.

So yeah, I'm a little torn at what the best situation for everyone is - people using Composed, and people just installing the plugin copy/paste style.

**Comment by sidneywidmer** [comment]
seems like the only way to achieve this is to add the following snippet to the main composer file (the one which requires supertable). I know it's not really nice but at least it's a working solution if someone else needs something like this (only tested on osx, but this should be easy to adapt on windows/linux)

    "scripts": {
        "post-autoload-dump": [
            "if test -d craft/plugins/supertable/supertable; then mv craft/plugins/supertable/supertable craft/plugins/_supertable && rm -rf craft/plugins/supertable && mv craft/plugins/_supertable craft/plugins/supertable; fi"
        ]
    }

Thanks for your quick response!

**Comment by thijskaspers** [comment]
+1 for this.. Composer allows us to easily update the plugin with a single console command. More and more plugins are using it, so please reconsider @engram-design ;)

**Comment by iparr** [comment]
I have another suggestion to match @sidneywidmer contribution:

```
"scripts": {
	"post-update-cmd": [
		"svn export https://github.com/engram-design/SuperTable/trunk/supertable app/craft/plugins/supertable --non-interactive --trust-server-cert --force"
	]
},
```

When `composer update` is run, it uses SVN (which is installed by default on Macs and probably most Linux distros) to put everything in the right place. I know. I don't like it either. Would love to see adoption of a different structure for all Craft plugins.

**Comment by engram-design** [comment]
Closing for now - this won't be implemented. Lets wait until the Plugin store, which will make all this meaningless (and likely work with Composer!)
