### ISSUE TITLE
Question: change supertable to matrix?

### ISSUE THREAD

**Issue by florentineprinzessinzusachsen** [engram-design/SuperTable#270]
### Description
I was wondering whether there are any best practices for programmatically changing an existing supertable (which has no matrix fields nested inside) into a matrix field?

### Additional info
- Plugin version: latest, 2.1.19
- Craft version: latest, 3.1.27

**Comment by engram-design** [comment]
It's certainly possible, as Matrix and Super Table fields are almost exactly alike, but no programatic guides as such, sorry. However, we'll be providing migration to Craft's Matrix solution in Craft 4.
