### ISSUE TITLE
Integrity constraint violation

### ISSUE THREAD

**Issue by chadcrowell** [engram-design/SuperTable#271]
### Description
I have a super table within a matrix field on a site that recently was upgraded from C2 > C3. All other super table fields on the site appear to be working. I did run the tools from the Settings tab after the upgrade. 

When I choose the matrix block and save the entry, I get the below error:

```
Integrity constraint violation – yii\db\IntegrityException

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`stemplecreek_craft`.`craft_stc_14_products`, CONSTRAINT `craft_stc_14_products_locale__siteId_fk` FOREIGN KEY (`locale__siteId`) REFERENCES `craft_sites` (`id`) ON DELETE CASCADE ON UPDATE CA)
The SQL being executed was: INSERT INTO `craft_stc_14_products` (`elementId`, `siteId`, `field_text`, `field_buttonLabel`, `dateCreated`, `dateUpdated`, `uid`) VALUES (10905, 1, NULL, NULL, '2019-05-16 22:36:41', '2019-05-16 22:36:41', 'e4bbc33a-b7cc-419a-9445-d815798a0db8')
Error Info: Array
(
    [0] => 23000
    [1] => 1452
    [2] => Cannot add or update a child row: a foreign key constraint fails (`stemplecreek_craft`.`craft_stc_14_products`, CONSTRAINT `craft_stc_14_products_locale__siteId_fk` FOREIGN KEY (`locale__siteId`) REFERENCES `craft_sites` (`id`) ON DELETE CASCADE ON UPDATE CA)
)
↵
Caused by: PDOException

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`stemplecreek_craft`.`craft_stc_14_products`, CONSTRAINT `craft_stc_14_products_locale__siteId_fk` FOREIGN KEY (`locale__siteId`) REFERENCES `craft_sites` (`id`) ON DELETE CASCADE ON UPDATE CA)

in /Users/Chad/Sites/stemple-creek/vendor/yiisoft/yii2/db/Command.php at line 1290
```

Here is my craft_sites table: https://d.pr/i/VycqDM
And the table in question: https://d.pr/i/qJPpHD

By the way, the craft_stc_14_products_locale_siteId_idx index was manually added by me a couple of days ago, and adding it seemed to solve a similar error. This time I thought I'd ask for help. 

### Additional info

- Plugin version: 2.1.19
- Craft version: 3.1.26

**Comment by engram-design** [comment]
So - there shouldn't be a `locale` column, or a `locale__siteId`, and it looks like the migration from Craft 2 didn't go so well renaming `locale` to `siteId`. In fact, I'm pretty sure that's something Craft itself does to all tables with `locale` (I'd need to double check that).

You should remove `locale` and rename `locale__siteId` to `siteId`.

**Comment by chadcrowell** [comment]
Thanks - there was already a siteId column, so I left that, removed the locale columns, and also removed the indexes that contained locale. However, when trying to add indexes back in for siteId, I looked at many other Super Tables on this site and others, and they all have 2 indexes with the same name. Sequel Pro won't allow me to add 2 with the same name even though I specify different columns. Is it OK to add the 2nd one with a different name?

This table: https://d.pr/i/EMfm2l
Other table: https://d.pr/i/BphElJ

**Comment by engram-design** [comment]
Are there any other db tables that have this issue?

There should be a total of 4 indexes on a content table. You should be able to add a unique key with multiple columns with Sequel Pro, see screenshot.

![Screen Shot 2019-05-18 at 9 41 56 am](https://user-images.githubusercontent.com/1221575/57961298-51036680-7951-11e9-99e0-9ef9fff7fd69.png)

**Comment by chadcrowell** [comment]
Thanks, I didn't realize the +/- buttons were to add more rows to the key. Good to go now on all 3 etc tables.
