### ISSUE TITLE
Invalid subpath exception

### ISSUE THREAD

**Issue by pette87** [engram-design/SuperTable#272]
### Description

![image](https://user-images.githubusercontent.com/11199719/58112038-effabd80-7bf2-11e9-9969-d569f7eee1b2.png)

![image](https://user-images.githubusercontent.com/11199719/58111964-c6da2d00-7bf2-11e9-9db9-1e381d92cade.png)

### Steps to reproduce

1. Setup a SuperTable field and in there setup a asset field e. g. for images **with subpath {owner.slug}**
2. In entry take a image in these field and save the page 
3. the error is show and the image isn't uploaded to the server

### Additional info

- Plugin version: 2.1.20
- Craft version: 3.1.27

**Comment by engram-design** [comment]
It looks like this is within a Matrix field, as per your screenshot? Can you confirm your full field setup?

If you have your field setup like Matrix > Super Table, you'll need to bubble up to the entry element. `{{ owner.slug }}` is actually going to refer to the Matrix field, which `slug` does not exist - hence the error.

You should use `{{ owner.owner.slug }}` to get the Matrix field (`owner`) and its owner, the Entry (`owner.owner`).
