### ISSUE TITLE
Failing migrations

### ISSUE THREAD

**Issue by chadcrowell** [engram-design/SuperTable#273]
### Description
C 3.1.28
ST 2.1.20
Same set of issues from [#271](https://github.com/verbb/super-table/issues/271) - but this time I can't get through them. This is a Craft 2>3 upgrade, a different site than #271. The 2>3 upgrade runs fine for Craft. I have observed that the tables in Craft that have locale columns and indexes now have siteId columns and indexes.

Installing ST through the plugin store or composer gives me this once I click the Finish Up button:
https://gist.github.com/chadcrowell/673523ff69258a3e3a256ee2f4e41f04

I have attached my db before the upgrade of ST, but after the upgrade of Craft.
[lynmar_craft-2019-05-22-9-14 PM.sql.gz](https://github.com/verbb/super-table/files/3210238/lynmar_craft-2019-05-22-9-14.PM.sql.gz)

**Comment by engram-design** [comment]
I believe this might've been related to lack of foreign keys setup on the `stc_*` tables and their siteId/locale column.

Craft should rename and column that's relating to its `locale` table (for Craft 2), and rename the column from `locale` to `local__siteId`, after which, Super Table takes care of the rest to fix this back up. These columns weren't being created, and points to either the Craft migration itself not running (in your case, it had), or the `stc_*` tables' `locale` column not being correctly tied to the `locale` table through a foreign key.

In any case, I have [pushed a fix for this](https://github.com/verbb/super-table/commit/8b4372cb09b1ed193d9c32a5cba7763de268667c), and will be in the next release.
