### ISSUE TITLE
Static Table Headings displayed awkwardly

### ISSUE THREAD

**Issue by jhealey5** [engram-design/SuperTable#279]
I've looked through existing issues but can't seem to find anything, but find it hard to believe this has not been mentioned before. This broken padding above the first heading on static super table fields displayed as a matrix drives me nuts 
![image](https://user-images.githubusercontent.com/1771431/59913962-31100880-9411-11e9-8613-b4ba61a31096.png)

Am I the only one?

**Comment by engram-design** [comment]
@jhealey5 Thanks for the reminder, will sort!
