### ISSUE TITLE
Matrix > Super Table > Matrix UI Bug

### ISSUE THREAD

**Issue by fyrebase** [engram-design/SuperTable#28]
I have a Matrix > Super Table > Matrix setup and when editing drop downs or checkboxes you can not add new options or reorder existing options. It appears the JavaScript responsible for these actions is not being applied.

It works without a problem when creating these fields though.

**Comment by engram-design** [comment]
Fixed in the [0.3.5](https://github.com/engram-design/SuperTable/releases/tag/0.3.5) release. Thanks for submitting this bug!
