### ISSUE TITLE
Implement BlockElementInterface for Craft 3.2

### ISSUE THREAD

**Issue by baileydoestech** [engram-design/SuperTable#281]
### Description
As detailed in https://github.com/craftcms/cms/issues/4507 we are seeing an exponentially growing list of jobs to `update search indexes` when upgraded to Craft 3.2. @brandonkelly suggests this is because plugins need to implement the BlockElementInterface:

> Search indexes aren’t supposed to be created for drafts and revisions, so you shouldn't be seeing all of these additional jobs lining up in the queue as a result of the draft/revision conversion, but if you have either Super Table or Neo installed, they will need to be updated to implement BlockElementInterface before Craft will actually know whether they should be considered drafts/revisions. I’ll work with the developers to get that to happen now that 3.2 is out.

### Steps to reproduce

1. Upgrade to Craft 3.2
2. Run migrations and project sync
3. Watch queue grow exponentially

**Comment by engram-design** [comment]
Should be fixed in [2.2.0](https://github.com/verbb/super-table/releases/tag/2.2.0)
