### ISSUE TITLE
Can't save any entry with a supertable field in it

### ISSUE THREAD

**Issue by ljclark** [engram-design/SuperTable#282]
### Description

On a fresh install of Craft 3.2.1, I'm unable to save any element that has a supertable field within it (entries, users etc). Video attached to show it in action. Console is throwing a fair few jquery errors referencing some craft files. 

I've removed all the plugins, and still getting the same error. 

### Steps to reproduce

1. Install Supertable
2. Create a field using supertable
3. Add it to a section/entry and try populate said entry

### Additional info

- Plugin version: 2.2.0
- Craft version: 3.2.1

![Screenshot 2019-07-14 at 12 23 51](https://user-images.githubusercontent.com/8060816/61182935-61bf1880-a632-11e9-96c3-9bc3a1fb515c.png)

[Screen Recording of error here!](https://www.dropbox.com/s/cuqaa70ke57wwo0/Screen%20Recording%202019-07-14%20at%2012.17.47.mov?dl=0)

**Comment by StudioShand** [comment]
I've just opened a new issue with exactly the same error, I'm also unable to create a new entry with a Super Table field in it (not just editing an existing entry).

**Comment by engram-design** [comment]
Sorry about that, should be fixed in [2.2.1](https://github.com/verbb/super-table/releases/tag/2.2.1)
