### ISSUE TITLE
Can't add new field or change existing ones

### ISSUE THREAD

**Issue by MrGlasspoole** [engram-design/SuperTable#284]
### Description
I have two fields in a Table Layout.
One "Plain text" and one "Button Box - Buttons".

I can't add a new field and i can't access the "Button Box" field or move them (up/down).

I cleared the Craft cache and did 'Check Content Tables' and 'Re-save Super Table Fields'.

### Additional info

- Plugin version: 2.2.1
- Craft version: 3.2.7
- Button Box: 2.0.4

**Comment by engram-design** [comment]
Can you check if there are any Javascript errors on the page when trying to edit the field?

**Comment by MrGlasspoole** [comment]
Yes there is:
```
Error: Permission denied to access property "apply" jquery.js:8465:3
    jQuery 5
    select _configurator.js:228
    init _configurator.js:76
    constructor garnish.js:768
    constructor garnish.js:40
    constructor garnish.js:40
    <anonymous> 20:2428
    jQuery 2
        e
        t
```

Found out that also matrix is not working:
https://github.com/craftcms/cms/issues/4668

**Comment by MrGlasspoole** [comment]
It was a Firefox Add-on:
https://github.com/craftcms/cms/issues/4668#issuecomment-516158044
