### ISSUE TITLE
How to achieve this layout?

### ISSUE THREAD

**Issue by MrGlasspoole** [engram-design/SuperTable#287]
Is this possible:
![Super-Table](https://user-images.githubusercontent.com/2067170/62512128-01795c00-b817-11e9-89c9-9cd1f4ce33f0.gif)

If yes i can't figure out how.
Since alt and caption can be lengthy i like to have them in a separate row.

**Comment by engram-design** [comment]
No sorry, this layout isn't possible without some CSS alterations, which you could do with the CPCSS plugin.

**Comment by engram-design** [comment]
Closing due to age.
