### ISSUE TITLE
Filter by value in Super Table field?

### ISSUE THREAD

**Issue by MrGlasspoole** [engram-design/SuperTable#290]
I can't figure out how to do it.
I have a Super Table "entryType" (Table Layout) with a checkboxes field "featuredIn" and a value "showInRandom".

This was working with a normal field:
```
{% set entries = craft.entries.section('blog').featuredIn('showInRandom').orderBy('RAND()').all() %}
{% for entry in entries|slice(0, 2) %}
  <h2>{{ entry.title }}</h2>
{% endfor %}
```

How do i do it with a Super Table?

This also doesn't do it:
```
{% set entries = craft.entries.section('blog').search('featuredIn:"showInRandom"').orderBy('RAND()').all() %}
```

**Comment by engram-design** [comment]
Searching Super Table blocks directly isn't possible, similar to Matrix, where this also isn't possible. The only real way is to add conditionals in your loop to check for the value of `featuredIn`.

**Comment by bymayo** [comment]
@engram-design How come this isn't possible? I remember being able to do this in Craft 2, but when porting sites from Craft 2 > Craft 3, this feature was lost and we had to rework quite a lot of code and do like you said, by filtering down a loop.

**Comment by KatieMFritz** [comment]
Is the search section of the docs inaccurate then? https://verbb.io/craft-plugins/super-table/docs/getting-elements/super-table-block-queries#search

**Comment by engram-design** [comment]
@bymayo I need to spin up an example, as I can't recall how this works off the top of my head, but I don't think the original question was ever possible. Correct me if I'm wrong though.

They wanted to fetch all entries where the Super Table field (`entryType`) has a checkbox field (`featuredIn`) that equals `showInRandom`. It'd have to look at all the rows for each ST field across each entry.

You'd likely be better off using a reverse-relation, where you're searching for Super Table Block elements, and fetch the owner element (in this case, an entry) and go from there. Refer to https://verbb.io/craft-plugins/super-table/docs/template-guides/available-variables#craft-superTable-getRelatedElements

@KatieMFritz That search is perfectly valid, but the original question is talking about a step above that, searching across a number of entries, and also a number of Super Table rows. Searching a Super Table field's rows is fine, and where that syntax is useful. You might have 20 blocks/rows in your field, and you want to fetch just the blocks that match a search query.

**Comment by bymayo** [comment]
@engram-design Yeah I think that is a bit more complex than what I'd imagined he wanted. My isuse previously has been searching the rows by a field value just within globals, OR just a solo entry. Below are some examples

In `Craft 2` I would have done:

```
{% for alert in alerts.globalAlerts.alertHandle(handle) %}
	<div class="notifications type-{{ alert.alertType }}">
		{{ alert.alertContent }}
	</div>
{% endfor %}
```

Then when upgrading to `Craft 3` I had to change it to:

```
{% for alert in alerts.globalAlerts.all() if alert.alertHandle == handle %}
	<div class="notifications type-{{ alert.alertType }}">
		{{ alert.alertContent }}
	</div>
{% endfor %}
```

**Comment by engram-design** [comment]
@bymayo Thanks for the example - I'd certainly say that _should_ work (just need to call `.all()`), so I'll double check this.

**Comment by engram-design** [comment]
Should be fixed in [2.3.1](https://github.com/verbb/super-table/releases/tag/2.3.1)

**Comment by bymayo** [comment]
@engram-design Does the fix work for what I need or the `.search('featuredIn:"showInRandom"')`. 

Sorry, I feel like I've hijacked this and should have been a seperare issue!

**Comment by engram-design** [comment]
@bymayo Nope, your original template code for C2 should work, ie: `{% for alert in alerts.globalAlerts.alertHandle(handle).all() %}`

**Comment by bymayo** [comment]
@engram-design Doh! 🤦‍♂Will try that.
