### ISSUE TITLE
Translation option doesn't get saved

### ISSUE THREAD

**Issue by TomDeSmet** [engram-design/SuperTable#291]
### Description
I have a Matrix field with a SuperTable inside of it and in there a simple text field.
When I set the text field to "translate for each site" and save the field, the selected option doesn't get saved and is set back to "not translatable".

Setting it to "translate for each language" does get saved.

### Additional info

- Plugin version: 2.2.1
- Craft version: 3.2.8

**Comment by colinmeinke** [comment]
I'm also seeing this with a multisite setup with Craft 3.2.9 and Super Table 2.2.1. If I create a new Super Table field, with one Plain Text field set to "Translatable by Site", when I go back to edit the field the Translation Method is set to "Not translatable". In reality the field's `translationMethod` value _is_ set to `site`, so it _does_ work as expected in terms of content editing.

**Comment by TomDeSmet** [comment]
I didn't take a peep in the database but I can say that it didn't work for me in the CP. No translations were visible.

**Comment by matthewmrotter** [comment]
We're also having this issue on our site after upgrading to 3.2.10 & Super Table 2.2.1

**Comment by bjornbjorn** [comment]
We also ran into this after upgrading to 2.2.1.

**Comment by xposedbones** [comment]
Same issue here with `Craft 3.3.0.1` and Supertable 2.2.1

**Comment by mkuma443** [comment]
Since the option value of /vendor/verbb/super-table/src/templates/settings.html is "app", it needs to be changed to "site".

**Comment by engram-design** [comment]
Fixed in [2.3.0](https://github.com/verbb/super-table/releases/tag/2.3.0).
