### ISSUE TITLE
supertable field not saving, causing memory/backend crash.

### ISSUE THREAD

**Issue by wihodges** [engram-design/SuperTable#292]
### Description
Ok so super strange issue, where all entries with supertable field no longer save.  When save button is pushed craft backend goes down causing 504 timeout. I'm not sure what is the cause of this, I recently updated Craft to latest version.  

The issue is happening on local valet and production. I don't think it's a memory problem even though the 'PHP Fatal Error' says: Allowed memory size of 268435456 bytes exhausted (tried to allocate 528384 bytes) in /home/repopath/craftcms/cms/src/elements/db/ElementQuery.php on line 2073. I also don't see any clear log entry erroring. I think it's causing a massive spike in resources. The closest related issue I could find is https://github.com/craftcms/cms/issues/4459#issuecomment-506842073 but looks like that was solved. 

The only thing I can narrow down is that it's only affected by supertable field being present on entry. 

Also strange is I have another site that leverages Supertable plugin and updated to latest version of craft and it's working just fine. So really not clear, what is going on. 

### Steps to reproduce

1. Open entry with supertable field. 
2. Make a change and try to save.

### Additional info

- Plugin version: 2.2.1
- Craft version: 3.2.9

**Comment by wihodges** [comment]
Ok so gets a bit stranger, I finally narrowed it down to another plugin, Activity Log, in conjunction with supertable. When enabled Activity log seems to crush the backend. So not sure why as I have Activity log and Supertable working together in another site and they seem to work fine. Not sure why other entries work without supertable...

**Comment by engram-design** [comment]
@wihodges Thanks for this, I've not tried Activity Log, but will look into it, and if there's anything I can do
