### ISSUE TITLE
Updating Craft & Super Table broke my database

### ISSUE THREAD

**Issue by pieterbeulque** [engram-design/SuperTable#293]
### Description

I can fix the tables using the provided tool, but when I trigger _Resave fields_, it throws this error:

```
Unknown column `content.field_${fieldname}`
```

with fieldname being the fields I had in my Super Table.

### Additional info

- Plugin version: 2.2.1
- Craft version: 3.2.9

**Comment by jan-dh** [comment]
Have the exact same issue. Bumping a website from 2.6 -> 3.2.1. I have about 4K tasks in queue all by supertable with errors like this:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'supertableblocks.ownerSiteId' in 'field list'
The SQL being executed was: SELECT `elements`.`id`, `elements`.`fieldLayoutId`, `elements`.`uid`, `elements`.`enabled`, `elements`.`archived`, `elements`.`dateCreated`, `elements`.`dateUpdated`, `elements_sites`.`slug`, `elements_sites`.`siteId`, `elements_sites`.`uri`, `elements_sites`.`enabled` AS `enabledForSite`, `supertableblocks`.`fieldId`, `supertableblocks`.`ownerId`, `supertableblocks`.`ownerSiteId`, `supertableblocks`.`typeId`, `supertableblocks`.`sortOrder`, `content`.`id` AS `contentId`, `content`.`field_time`, `content`.`field_voormiddag`, `content`.`field_namiddag`, `content`.`field_avond`
```

**Comment by jan-dh** [comment]
I fixed this by manually adding the ownerSiteId in the database, no more errors.

**Comment by pieterbeulque** [comment]
@jan-dh Can confirm that adding the correct column to the database also fixed my issues, but that's quite sketchy to do on a production website.

**Comment by engram-design** [comment]
Can I ask what version you were upgrading from @pieterbeulque ? It seems like a native Craft migration didn't kick in correctly, which should be adding the ownerSiteId column.

@jan-dh I'll look into this from 2.6.

**Comment by wallacio** [comment]
Same is happening here, although I can't be sure what the upgrade path of this install was. Looks like that column is dropped as part of a migration:

[https://github.com/verbb/super-table/blob/dbe5395bcad2320fbe67a85ea441cadd2e0d7150/src/migrations/m190714_000000_propagation_method.php](url)

**Comment by engram-design** [comment]
@wallacio Its correctly dropped as its no longer needed, but seems to cause issues when upgrading from certain older versions. Still looking into it.

**Comment by benjaminkohl** [comment]
Did this ever get resolved or is there a safe workaround I can use during a site upgrade process? I am running into this error in over 40K queue jobs in a local upgrade from 2.1.21 to 2.5.1.

I see above that the column got dropped in a migration yet something is clearly still trying to reference it in a query.

**Comment by bjornbjorn** [comment]
Not sure, but I think these are stale jobs from before / during the upgrade or something. I had a lot of these (ownerSiteId not found) after upgrading from craft from 3.0 to 3.6.6 (together with SuperTable). So I clicked around in admin and made some edits in the sections where SuperTable was used and everything seemed to work, so I cancelled all the jobs to clear out the error log. None of these errors re-appeared after that, so it seems whatever was referencing ownerSiteId wasn't the latest SuperTable.
