### ISSUE TITLE
[Feature Request]: Allow dynamic number of columns

### ISSUE THREAD

**Issue by furioursus** [engram-design/SuperTable#294]
### Description
Would be great if there was some way we could allow our staff/authors to choose how many columns they need for a table. We need the ability to use a rich text editor in our cells, but sometimes staff need two columns for a table and other times they need 7, or anywhere inbetween. I can manually create each specific table, but that seems like a lot of wasted effort if the cells are all the same except they have one additional column each time.

**Comment by engram-design** [comment]
Very likely not going to happen (sorry), as we push towards a native Craft 4 solution.
