### ISSUE TITLE
Can't query super-table in graphQL

### ISSUE THREAD

**Issue by arjankruithof** [engram-design/SuperTable#295]
### Description

When querying a super-table field in the GrapQL API in the Craft admin. The result is 'null' and typeOf 'string' instead of showing the fields and children of the field.

### Additional info

- Plugin version: 2.2.1
- Craft version: 3.3.0.1

**Comment by pandastein** [comment]
Same issue here :/

**Comment by engram-design** [comment]
Not yet tested with Craft 3.3 and native GraphQL - I'll look into it!

**Comment by engram-design** [comment]
Added in [2.3.0](https://github.com/verbb/super-table/releases/tag/2.3.0). The following should get you going:

```
{
  entries (section: "mySection") {
    superTableFieldHandle {
      ...on superTableFieldHandle_BlockType {
        fieldHandle
      }
    }
  }
}
```

**Comment by pandastein** [comment]
Thank you for the support
