### ISSUE TITLE
Example to eager load an asset inside a matrix->supertable->matrix->blockType ?

### ISSUE THREAD

**Issue by skramstad** [engram-design/SuperTable#296]
### Description
I'm trying to figure out how to eager load an asset inside a matrix->superTable->matrix-blockType. Is it posible and is there an example I can have a look at?

- Plugin version: 2.2.1
- Craft version: 3.3.0.1

**Comment by engram-design** [comment]
At the moment, its not possible to eager-load complex field setups, such as this. This covers:
Super Table > Matrix > Field
Matrix > Super Table > Matrix > Field
Matrix > Super Table > Field

**Comment by skramstad** [comment]
@engram-design Thank you for the info.

**Comment by seandelaney** [comment]
@engram-design 

is eager loading Matrix > Super Table > Field possible or still not possible?

**Comment by joshuapease** [comment]
Hi There! I wanted to check and see if eager loading still has this limitation.

I've done a few tests recently and it seems like eager loading is working with a combination of `Supertable > Matrix > Supertable > Asset Field`

**Comment by engram-design** [comment]
I believe eager-loading should work with Super Table > Matrix > Super Table, but not Matrix > Super Table > Matrix. I'll need to double check this though!
