### ISSUE TITLE
show row number/count when creating entries?

### ISSUE THREAD

**Issue by MrGlasspoole** [engram-design/SuperTable#299]
Is it possible to show the row number/count in front of the rows?
This is how it was in ExpressionEngine:
![8XF53](https://user-images.githubusercontent.com/2067170/64722766-69cef380-d4cf-11e9-91ca-56fec24b4573.jpg)

**Comment by engram-design** [comment]
Not currently possible, but will add it as a feature request

**Comment by MrGlasspoole** [comment]
Thanks.
In my entries I insert the images like "%%image1%%", "%%image2%%"...
The number is the row.
If i see the row number it makes it a lot easier.

**Comment by engram-design** [comment]
Very likely not going to happen (sorry), as we push towards a native Craft 4 solution.
