### ISSUE TITLE
The "Use this field’s values as search keywords?" setting should be checked by default.

### ISSUE THREAD

**Issue by jsunsawyer** [engram-design/SuperTable#301]
### Description
The `Use this field’s values as search keywords?` field option is checked by default when adding standard Craft fields.

I noticed that fields added within a Super Table field were not adding these by default. This inconsistency makes it likely to overlook this setting.

Here's a screenshot of what you get when adding a new Plain Text field in a Super Table field.
![Screen Shot 2019-09-15 at 11 46 17 AM](https://user-images.githubusercontent.com/1007191/64926172-41851480-d7af-11e9-89a1-02330986e26a.png)

### Additional info

- Plugin version: 2.3.0
- Craft version: 3.3.3

**Comment by engram-design** [comment]
Should be fixed in [2.3.1](https://github.com/verbb/super-table/releases/tag/2.3.1)

**Comment by darylknight** [comment]
Can we undo this? Craft has this off by default now.

**Comment by engram-design** [comment]
@darylknight Ugh, that'd be right - should've left it alone 😅

Updated in [2.6.4](https://github.com/verbb/super-table/releases/tag/2.6.4)
