### ISSUE TITLE
Search if Super Table Field Has Rows

### ISSUE THREAD

**Issue by kmgdevelopment** [engram-design/SuperTable#306]
I have a section with a super table field, and I only want to display entries in that section if the super table field has rows (so basically a "not empty" search). How do I do this? I tried using the `*` and the `:notempty:` search parameters but neither worked.

```
{% set entries = craft.entries({
  section: 'mySection',
  superTableField: ':notempty:'
}).all %}
```

**Comment by engram-design** [comment]
Currently the only way to find entries that have Super Table rows is with the search param:

{% set entries = craft.entries({
  section: 'mySection',
  search: 'superTableField:*',
}).all %}
