### ISSUE TITLE
Run "fix-content-tables" as a queue job

### ISSUE THREAD

**Issue by timkelty** [engram-design/SuperTable#308]
I'm unable to run the "fix-content-tables", because I get a timeout from nginx. This should run as a job so it can be long-running/in the background.

**Comment by engram-design** [comment]
Not really sure I want this to run in a queue, specifically because otherwise we can't really show feedback to the user.

I'll look at adding this as a console command, which should help for this sort of thing

**Comment by engram-design** [comment]
Super Table has now reached its end of life, and we'll be sticking with bug/security fixes from here on out. More in the [announcement](https://verbb.io/blog/so-long-super-table).
