### ISSUE TITLE
Static field containing no values returns errors as a null value when trying to access table field in templates

### ISSUE THREAD

**Issue by johndwells** [engram-design/SuperTable#31]
I have SuperTable field configured to be a single "static" row, and the table itself has 2 simple text fields.  In some entries, both values of this field can be empty.

When that is the case, my templates error if I try to access either of these fields on the first row. The error suggest that the first row is null:

`Impossible to access an attribute ("table_field_name") on a null variable`

However, if I `dump()` my SuperTable field's first row, I see a Craft\SuperTable_BlockModel.  If I `dump()` the SuperTable field itself, I get a Craft\ElementCriteriaModel.

The upshot of all of this is that I cannot avoid template errors if a client hasn't filled out any fields of a static SuperTable, because I can't work out a conditional to account for this scenario.

Ideally my preference would be that `supertable_field_name | length` returns 0, just as if it were a non-static table (with or without a limit of 1 row).  This would be, to me, more consistent template behaviour.

Thanks!
John

**Comment by engram-design** [comment]
One way to get around this is to use something like the below:

```
{% for entry in craft.entries.section('news') %}
	{% for row in entry.superTableStatic %}
		{{ row.field1 }}
	{% endfor %}
{% endfor %}
```
or
```
{% for entry in craft.entries.section('news') %}
	{% if entry.superTableStatic | length %}
		{{ entry.superTableStatic[0].field1 }}
	{% endif %}
{% endfor %}
```

However, using the `0` index is a bit of a pain, and I might rework things to supersede the need to use this. A static ST field actually returns a collection of rows, even though there will only ever be one. Instead, a static ST field should return just the first row, so you can directly access the row fields.

**Comment by johndwells** [comment]
Thanks for the loop tip, I'll see if those can tide me over for the time being!

**Comment by engram-design** [comment]
This has (finally) made it into the [0.4.3 release](https://github.com/engram-design/SuperTable/releases/tag/0.4.3). You can now access fields directly without having to loop or use an `0` index. The above example can be written as:

```
{% for entry in craft.entries.section('news') %}
    {{ entry.superTableStatic.field1 }}
{% endfor %}
```
