### ISSUE TITLE
Check/Fix Tables Returns Twig Error

### ISSUE THREAD

**Issue by kmgdevelopment** [engram-design/SuperTable#310]
### Description

When trying to access `/actions/super-table/plugin/check-content-tables` or `/actions/super-table/plugin/fix-content-tables`, the URL returns a Twig error:

> Unable to find the template “super-table/plugin-settings”.

This appears to be a UI issue only, as `fix-content-tables` appears to do its job correctly before returning the twig error (I assume it's supposed to point to a confirmation page of some kind). 

### Additional info

- Plugin version: 2.3.0
- Craft version: 3.3.12

**Comment by engram-design** [comment]
Are you trying to access these URLs directly? If so, the error message is technically correct, as these should be run through the plugin's settings page, but I've fixed this in [2.3.1](https://github.com/verbb/super-table/releases/tag/2.3.1)
