### ISSUE TITLE
Problem Updating 2.1.16 to 2.3.0 in Craft 3.3.15

### ISSUE THREAD

**Issue by richardegil** [engram-design/SuperTable#313]
### Description
Can't seem to get passed the update process on a dated version of both Craft and the plugin. I was able to update Craft from 3.1.18 to 3.3.15 but now when I update Super Table I am getting a failed migration message about missing foreignKeys. Also, I am getting a  "... supertableblocktypes' doesn't exist The SQL being executed was: SELECT * FROM `supertableblocktypes`" when I try to use the Check Content Tables/Re-save Tables utility in the plugin settings page before doing the update.

Any help is greatly appreciated. I have searched other issues, but can't seem to find something simillar.

### Additional info

- Plugin version: 2.1.16
- Craft version: 3.3.15

**Comment by richardegil** [comment]
Can anyone provide some guidance?

**Comment by engram-design** [comment]
Can you provide a bit more detail on the exact errors you're getting, such as screenshots, or stack trace output?

**Comment by richardegil** [comment]
@engram-design I was to resolve this by uninstalling and reinstalling, luckily I didn't have any data loss.
