### ISSUE TITLE
Display Issue with Verbb Field Manager Plugin

### ISSUE THREAD

**Issue by AncientAzem** [engram-design/SuperTable#316]
### Description
When used in conjunction with the Field Manager plugin, other items in the super table are displayed in the background of the modal. A simple fix would be to add the following CSS:
```
.settings-hidden {
    display: none;
}
```

### Steps to reproduce

1. Install the [Verbb Field Manager plugin](https://plugins.craftcms.com/field-manager)
2. Edit any super table you have in your field and toggle between each value in the table.

### Additional info

- Plugin version: 2.3.1
- Craft version: 3.3.17

**Comment by engram-design** [comment]
Fixed in [2.3.2](https://github.com/verbb/super-table/releases/tag/2.3.2)
