### ISSUE TITLE
Setting minRows/maxRows leads to "SuperTable block is missing its owner ID"

### ISSUE THREAD

**Issue by andersaloof** [engram-design/SuperTable#317]
### Description
I am currently using a SuperTable field inside a matrix, and when I specify min/maxRows, I get the error "SuperTable block is missing its owner ID" when I try to edit an entry using this matrix.

### Steps to reproduce

1. Specify minRows/maxRows on a supertable field inside a matrix and save
2. Go to entry using this matrix and get error
3. Go back to settings and clear minRows/maxRows on the same supertable and save
5. Go to entry using matrix and error is gone

### Additional info

- Plugin version: 2.3.1
- Craft version: 3.3.16.3

**Comment by engram-design** [comment]
Though my testing I seem to be able to set these values okay, in a variety of different field setups.

It might be a few things - your PHP max_input_vars setting (if its a large field) - re-saving the field doesn't help? Have you run the content table checker/fixer?

Editing anything else on the Super Table field doesn't throw this error?
