### ISSUE TITLE
Invalid SuperTable block ID: 1

### ISSUE THREAD

**Issue by granitibrahimi** [engram-design/SuperTable#320]
### Description
After we updated to the newest version 2.3.1 when we try to update a page which has SuperTable fields it is throwing an issue: 

yii\base\InvalidConfigException: Invalid SuperTable block ID: 1 in /vendor/verbb/super-table/src/elements/SuperTableBlockElement.php:250

### Steps to reproduce
POST Request from error log:

$_POST = [
    'CRAFT_CSRF_TOKEN' => '••••••••••••••••••••••••••'
    'action' => 'entries/save-entry'
    'redirect' =>'7a586fa6b2064ba38fce3f7f51d73ad4b1957d05cccf5eae2d7a0dentries/test'
    'siteId' => '2'
    'sectionId' => '5'
    'entryId' => '123'
    'title' => 'TEST'
    'fields' => [
        'color' => '#00b74f'
        'titleIcon' => [
            0 => '63'
        ]
        'tagIcon' => [
            0 => '65'
        ]
        'bigIcon' => [
            0 => '67'
        ]
        'topImage' => [
            0 => '6121'
        ]
        'topTitle' => ''
        'overviewTitle' => '--'
        'overviewContent' => '--'
        'content1Title' => '--'
        'content1' => '--'
        'content2Title' => '--'
        'content2' => '--'
        'projectsCount' => [
            'locale' => 'en-US'
            'value' => '8'
        ]
        'ourPartnerTitle' => '--'
        'ourPartnerDescription' => ''
        'ourPartnerSpeakerLocationsTitle' => '--'
        'blocks' => [
            2009 => [
                'type' => '2'
                'fields' => [
                    'blockTitle' => '--'
                    'blockDescription' => '--'
                    'blockButtonTitle' => '--'
                    'blockButtonLink' => '--'
                ]
            ]
            2010 => [
                'type' => '2'
                'fields' => [
                    'blockTitle' => '--'
                    'blockDescription' => '--'
                    'blockButtonTitle' => '--'
                    'blockButtonLink' => '--'
                ]
            ]
        ]
        'insertNewsletter' => ''
        'metaTitle' => ''
        'metaDescription' => ''
        'metaAuthor' => ''
        'metaKeywords' => ''
    ]
    'typeId' => '5'
    'slug' => 'test'
    'author' => [
        0 => '1'
    ]
    'postDate' => [
        'date' => '9/17/2019'
        'timezone' => 'Europe/Berlin'
        'time' => '11:20 AM'
    ]
    'expiryDate' => [
        'date' => ''
        'timezone' => 'Europe/Berlin'
        'time' => ''
    ]
    'enabled' => '1'
    'enabledForSite' => '1'
]

### Additional info

- Plugin version: 2.3.1
- Craft version: 3.3.18.2

**Comment by engram-design** [comment]
Have you run any of the Content Table Checker/Fixer utilities, and were there any issues?

**Comment by granitibrahimi** [comment]
@engram-design yes we have tried and there it says no errors found!

**Comment by engram-design** [comment]
Re-saving the Super Table field doesn't help? Can you also inspect the `supertableblocks` database table and check if any rows have a null value for the `typeId` column?

**Comment by granitibrahimi** [comment]
@engram-design no unfortunately not. We tried the re-save all SuperTable fields and also on `supertableblocks` there is not any row with null value for `typeId` column!

Thanks

**Comment by engram-design** [comment]
So sounds like the blocktype has just disappeared. The quickest way is to re-create it in your database (just make sure it has an ID of 1). But re-saving the field should do this.

However, if you go to edit the Super Table field in question (not just re-save it with the utility), it should no longer have fields, because its missing its field layout. It might be worth checking to see if you have a backup with this `supertableblocks` row still there.

**Comment by granitibrahimi** [comment]
I had to insert `blocktype` and also had to update to null `fieldlayouts.dateDeleted` for the specific `fieldlayout` from an old version of database and now it is working ok.

Thanks
