### ISSUE TITLE
Issue with Supertable inside Matrix - Craft 3.4 RC2

### ISSUE THREAD

**Issue by bliswebagency** [engram-design/SuperTable#323]
### Description

The issue seems to happen when you are using a Supertable inside a Matrix.

Initially when you create an entry, things works fine. However, once you edit an existing entry, problems arise.

Effectively, if you add new elements to the Supertable, they don't get saved. It looks like nothing has changed.

Worse; if you change content within an existing element inside the Supertable, it gets wiped.

I assume this relates to how RC2 is handling Draft entries.

### Steps to reproduce

I made a video:
http://shared.bl.ms/UjYJjn

### Additional info

- Plugin version: 2.3.3
- Craft version: 3.4 RC2

**Comment by engram-design** [comment]
Yep, so we're still testing for 3.4 - you're best to use the 3.4 branch.

Update your composer.json file to use `feature/craft-3.4-dev as 2.4.0-RC1`, then run `composer update`

**Comment by bliswebagency** [comment]
Thanks. Just switched to 2.4.0-RC1 but it doesn't seem to have fixed anything. Assume this is something you guys are across?

**Comment by rsgd** [comment]
Unfortunately we are facing the exact same behavior with Craft 3.4.0.2 and Plugin Version 2.4.0

However our setup is a little more complicated than described in the initial issue. We are going one level deeper and using a Matrix inside a Supertable inside a Matrix. So I am not quite sure if it is still the same issue.

Thanks!

**Comment by engram-design** [comment]
Should be fixed in [2.4.1](https://github.com/verbb/super-table/releases/tag/2.4.1)

**Comment by rsgd** [comment]
Thanks, much appreciated!
