### ISSUE TITLE
adding mutation support for CraftQL

### ISSUE THREAD

**Issue by jamieSymso** [engram-design/SuperTable#325]
### Description

please add the compatibility to allow mutations via CraftQL. It would be a really big step for headless cms.

thanks.

**Comment by engram-design** [comment]
Will look into this - I would be prioritising native GraphQL support, but sounds mutations arent possible at the moment?

**Comment by jamieSymso** [comment]
That's right. Native GraphQL support is planned for the 4.0 release. At the moment mutations are only possible with CraftQL.

**Comment by engram-design** [comment]
Going to close this, as there's no plans to add support for CraftQL, sorry. Native GraphQL mutations are possible.
