### ISSUE TITLE
CSS bug with Static field checked

### ISSUE THREAD

**Issue by stephanedemotte** [engram-design/SuperTable#329]
### Description
CSS BUG
<img width="1019" alt="Screen Shot 2020-02-01 at 12 31 53 PM" src="https://user-images.githubusercontent.com/2158130/73596351-645e5e00-44ef-11ea-9b70-49c460e82bf5.png">

### Steps to reproduce

1. Create a super table field "Static field" checked

### Additional info

- Plugin version: 2.4.2
- Craft version: 3.4.2

**Comment by engram-design** [comment]
Fixed in [2.4.3](https://github.com/verbb/super-table/releases/tag/2.4.3)
