### ISSUE TITLE
Update from 0.3.4 to 0.3.5 fails

### ISSUE THREAD

**Issue by superflausch** [engram-design/SuperTable#33]
Hi,

I just tried to update to your latest release as we also faced the issue it fixes. Unfortunately the DB update/migration fails somehow and craft does an automatic rollback.

Not sure what I can provide you to help. Maybe a DB dump.

Cheers,

Pascal.

**Comment by engram-design** [comment]
Are you able to get in contact through Slack? We can get things sorted through there.

**Comment by engram-design** [comment]
Thanks for raising this issue, which we resolved over Slack. For future users, please read [0.3.4-0.3.5 notes](https://github.com/engram-design/SuperTable#updating-from-034-to-035)
