### ISSUE TITLE
Can't add SuperTable to Globals set

### ISSUE THREAD

**Issue by xavianaxw** [engram-design/SuperTable#331]
### Description

I have a SuperTable field to add a CTA block to my globals but I keep getting a "Couldn't save global set" error.

Here's the setup of my field.

```
heading - PlainText
page - Entries
```

### Steps to reproduce

1. Create a field with the setup as mentioned above
2. Create a global set
3. Add SuperTable field to the global set
4. Click save

### Additional info

- Plugin version: `2.3.3`
- Craft version: `Craft Pro 3.3.20.1`

**Comment by engram-design** [comment]
Are you able to check your `storage/logs/web.log` file? Search for `[error]` to see if there's some more information on the issue.

**Comment by xavianaxw** [comment]
Hey Josh. I tried editing another Global set and it seemed to work now. I assumed it was probably another error causing the prompt. Gonna close this for now since it's not a SuperTable problem.
