### ISSUE TITLE
GraphQL Scoping Issue

### ISSUE THREAD

**Issue by MarcHartwig13** [engram-design/SuperTable#332]
### Description

I have a setup of `Matrix Block > Super Table` 

I have multiple matrix blocks and if I have two different super tables by the same handle in two different matrix blocks then the graphQL for the second block (or possibly second super table) created returns the supertable fields of the first.

Seems like the fields aren't being scoped to the matrix block they're in.

### Steps to reproduce

1. Create a Matrix Field
2. Create two distinctly named blocks.
3. Add a super table to each block using the same handle for each super table.
4. Add unique fields to each super table.
5. graphQL output for each block will only return the fields from one supertable (presumably the first created)

This may be related to: #327 

### Work Around

If you make the handles unique, then the fields will come through the graphQL correctly.

### Additional info

- Plugin version: 2.4.4
- Craft version: 3.4.3

**Comment by mildlygeeky** [comment]
@MarcHartwig13 - are you still having this issue? We've also run into this issue and are wondering if you ever found a resolution to this (running latest Super Table and Craft)

**Comment by JayBox325** [comment]
This is still an issue I'm encountering. I have resolved it for now by using @MarcHartwig13's 'work around' solution.
