### ISSUE TITLE
Can't update dropdowns after update

### ISSUE THREAD

**Issue by umkasanki** [engram-design/SuperTable#333]
### Description
Can't add new options (or remove old) into the dropdown field after update. 

![изображение](https://user-images.githubusercontent.com/496132/74353801-7c758d80-4dcb-11ea-9dbf-b6a762dd8604.png)

Buttons don't work.
After changing the screen size, the buttons start working again.

### Steps to reproduce

1. Update Craft
2. Update SuperTable plugin

### Additional info

- Plugin version: 2.4.4
- Craft version: Pro 3.4.5

**Comment by engram-design** [comment]
Are you able to look in the Dev Tools (If using Chrome), and see if there are any Console or Javascript errors on this page? Locally, these seem fine to me.

Can you also advise what browser?

Also, advise if you're using it in combination with a Matrix field?

**Comment by umkasanki** [comment]
1. Yes, I checked the console. There were no errors. 
2. Firefox latest. 
3. Just supertable > dropdown, without matrix

**Comment by engram-design** [comment]
Hmm, can't seem to immediately replicate the issue. I'm wondering if it might be another plugin? Can you provide a list of plugins and versions installed? (Utilities > System Report)

**Comment by umkasanki** [comment]
Sure
![изображение](https://user-images.githubusercontent.com/496132/74584092-693b0b80-4fdf-11ea-9458-24c2dfe13042.png)

**Comment by dletsche** [comment]
A colleague encountered a similar issue and I was able to replicate as well.

Here's a quick video demo: https://drive.google.com/file/d/1NaOK74AVqJHgArEAdcmqmIgR-824uof4/view. 

That was a super table with a table field. Besides the gear not working, other buttons also had issues:

![Screen Shot 2020-03-02 at 1 24 42 PM](https://user-images.githubusercontent.com/915784/75709998-5ab04d80-5c89-11ea-8fb5-4cab89362edb.png)

I'm using Version 80.0.3987.122 of Chrome for MacOS 10.15.3. No errors in the console. 

Here's a screenshot of the system report: 

![image](https://user-images.githubusercontent.com/915784/75709571-8c74e480-5c88-11ea-9771-81484ca7f158.png)

Hope that's helpful.

**Comment by engram-design** [comment]
Thanks for the video @dletsche just still can't replicate it in all browsers. Good pick-up on the resizing behaviour.

Was this an existing field you were editing, or a new one? Refreshing the page did nothing? Clearing caches?

**Comment by oscaralexander** [comment]
Running into the same issue for a Dropdown field. The "+ Add an option" link doesn't respond anymore when updating (i.e. after the first save). Running no other plugins, so conflicting plugins are ruled out.

![image](https://user-images.githubusercontent.com/1172527/78639878-fe0b0880-78ae-11ea-8919-1f940f86c89d.png)

**Comment by engram-design** [comment]
Wondering if anyone would be able to literally zip up their project folder, and their database and send through (I'm on Discord - handle `crawf`). I just can't seem to replicate it on a number of environments and setups.

**Comment by oscaralexander** [comment]
@engram-design I'm not on Discord but would be happy to email it, my project is only a few hours in so still very clean. I'm running it on MAMP. One issue I've found with MAMP so far is that, even though I've added it to my `PATH`, it says it can't execute `mysqldump` when attempting to fix tables or re-save fields.

**Comment by oscaralexander** [comment]
Wow. Weirdest thing. When I checked the Inspector for errors, it resized to preset iPhone X dimensions, and when I resized back to full-width, the "+ Add an option" suddenly worked. Even simply resizing the browser window works (as @dletsche pointed out in his video). It seems triggering a resize event properly initializes the UI for adding dropdown options.

**Comment by engram-design** [comment]
@oscaralexander Can you shoot it through to web at verbb.io I'll see if I can replicate it

**Comment by dletsche** [comment]
@engram-design - I think I may have some more helpful information. Here’s another video: https://drive.google.com/open?id=1Nrn2fm0SulkjyhbIePgG2_dt5azlXLIA. I’ll send you a copy of the site via email or Discord.

**Comment by engram-design** [comment]
Fixed in [2.4.8](https://github.com/verbb/super-table/releases/tag/2.4.8)
