### ISSUE TITLE
When editing a deeply nested field type, neither `Matrix nor `Super Table` are shown as options.

### ISSUE THREAD

**Issue by Tamriel** [engram-design/SuperTable#334]
### Steps to reproduce

1. Create a field with type `Matrix`
2. Add a block with type `Super Table`
3. Add a field with type `Matrix`. The types of that field are limited, I cannot choose `Matrix nor `Super Table`.

### Additional info

- Plugin version: 2.4.4
- Craft version: 3.4.5

![2020-02-16-173221_1920x1200_scrot](https://user-images.githubusercontent.com/5037153/74608567-6ffe7700-50e2-11ea-9d8d-b275ee3418da.png)

**Comment by engram-design** [comment]
This is correct behaviour - you cannot have a Super Table > Matrix > Super Table field combination, nor a Super Table > Matrix > Matrix.

**Comment by Tamriel** [comment]
Well, on the [features page](https://verbb.io/craft-plugins/super-table/features) it says 'A solution for Matrix-in-Matrix'. So that is possible only for two levels of nesting, not more?

**Comment by engram-design** [comment]
The only nesting option you have for 3-levels deep is Matrix > Super Table > Matrix. Anything more, and your best bet it to check out [Neo](https://plugins.craftcms.com/neo)

**Comment by Tamriel** [comment]
Thanks for the clarification!
