### ISSUE TITLE
Class 'verbb\supertable\variables\Craft' not found

### ISSUE THREAD

**Issue by gmhenderson** [engram-design/SuperTable#335]
### Description
After updating to the latest version of Craft and Supertable, I get:

```
Class 'verbb\supertable\variables\Craft' not found
```

when using `craft.superTable.blocks()` in a Twig template. Adding `use Craft;` at the top of `src/variables/SuperTableVariable.php` seems to fix.

### Steps to reproduce

1. Update to latest Craft/Supertable.
2. Use `craft.superTable.blocks({ ownerId: null, fieldId: null })` in a template.

### Additional info

- Plugin version: 2.4.5
- Craft version: 3.4.8

**Comment by engram-design** [comment]
Fixed in [2.4.6](https://github.com/verbb/super-table/releases/tag/2.4.6)
