### ISSUE TITLE
Number fields are misaligned when rendered

### ISSUE THREAD

**Issue by jishi** [engram-design/SuperTable#337]
### Description
If you have a table with mixed plain text and number fields, they don't align with eachother (or in the table cell).

### Steps to reproduce

1. Create a super table with mixed plain text and number columns.
2. Add a row

### Additional info

- Plugin version: 2.3.3
- Craft version: 3.3.15
- Edge 80 on Windows 10 (Chromium based), same on Chrome 80.

![image](https://user-images.githubusercontent.com/3165475/75465667-3e5e9900-5989-11ea-9a2d-4bacacadff16.png)

**Comment by engram-design** [comment]
Fixed in [2.4.6](https://github.com/verbb/super-table/releases/tag/2.4.6)
