### ISSUE TITLE
[Feature Request] Ability to add tabs to blocks

### ISSUE THREAD

**Issue by sparkadvocacy** [engram-design/SuperTable#338]
Would really streamline the editing experience for users if we could define tabs that could contain fields. For example you could have tabs on blocks for Content fields or Settings fields or Styling fields etc. - where the name and number of tabs could be arbitrary. Similar to what the plugin "Spoon" does for matrix fields.

Great plugin, and many thanks!

**Comment by engram-design** [comment]
Very likely not going to happen (sorry), as we push towards a native Craft 4 solution.
