### ISSUE TITLE
JSON Element API querying issue with super-table field

### ISSUE THREAD

**Issue by tsawitzki** [engram-design/SuperTable#339]
### Description

In my headless Craft setup I use Super Table to build individual timetables/shift plans for employees within the CP which I want to query via Craft’s Element API. 
The table columns consist of "Weekday" (Dropdown with all weekdays), "Shift start" (Time picker) and "Shift end" (Time picker).
Editors are allowed to add as many rows to the table as they wish.
The whole Super Table field has the handle "shifts", while the three columns within are called "weekdays", "shiftstart" and "shiftend"

- When I query `'weekdays' => $entry->shifts->weekdays` within my `element-api.php` file, I only get the first weekday of each employee within the JSON structure though. I was hoping I’d get a nested structure of all weekdays/entries?

- What do I have to do to have a nested JSON structure returned that contains all weekdays with each according "shiftstart"/shiftend"? 

### Steps to reproduce

This is my current `element-api.php` file:

`<?php

  use craft\elements\Entry;
  use craft\elements\Asset;
  use craft\helpers\UrlHelper;

  return [
      'endpoints' => [
          'sellers.json' => function() {
              return [
                  'elementType' => Entry::class,
                  'criteria' => ['section' => 'sellers'],
                  'transformer' => function(Entry $entry) {
                      return [
                          'title' => $entry->title,
                          'age' => $entry->age,
                          'dog' => $entry->dog,
                          'sellerId' => $entry->sellerid,
                          'message' => $entry->message,
                          'photo' => $entry->photo->one()->getUrl('jpegCroppedSquare200px'),
                          'locationLat' => $entry->location->lat,
                          'locationLng' => $entry->location->lng,
                          'locationAddressStreet' => $entry->location->parts->address,
                          'locationText' => $entry->locationtext,
                          'weekdays' => $entry->shifts->weekdays,
                      ];
                  },
                  'pretty' => true,
                  'paginate' => false,
              ];
          },

      ]
  ];

?>`

### Additional info

- Plugin version: 2.4.4
- Craft version: 3.4.5

**Comment by engram-design** [comment]
So by calling `$entry->shifts->weekdays`, you're actually treating it like a Static Super Table, in that it'll get the first block in the field, and then fetching the `weekdays` field.

Breaking it down, using `$entry->shifts` will return a Super Table Block query. You'll likely want to use `$entry->shifts->all()` to actually fetch all the Block elements from that query.

Next, if you want to return an array of just the `weekdays` values, you'll have to build an array for that.

```
$weekdays = [];

foreach($entry->shifts->all() as $shift) {
    $weekdays[] = $shift->weekday;
}

...
'weekdays' => $weekdays,
...
```

If you didn't care too much about getting just the weekdays values, you could return all the Super Table blocks:
```
...
'weekdays' => $entry->shifts->all(),
...
```
