### ISSUE TITLE
Plain text value not output to template after updating

### ISSUE THREAD

**Issue by mackenziep** [engram-design/SuperTable#343]
### Description

After updating from Craft 3.0.x, a particular SuperTable field is updating in the admin, but the value isn't being output in the frontend templates as expected. I ran the table fixer after updating, and it fixed some stuff if I remember correctly... When I run it now, there are still a few issues - just a few orphan "...is not a Super Table field" messages as discussed [here](https://github.com/verbb/super-table/issues/336), and a few "...has inconsistent field settings in its project config" messages, but for unrelated fields. 

I'm pretty sure that the correct values are in the DB, but since updating this template code returns the `image.width` value even when `options['maxWidth']` is set (`options` being the SuperTable field):

`style="max-width: {{options['maxWidth'] ?? (image.width ~ 'px')}};"`

It's strange because everything works as expected in my local environment, but not in production. I looked in the production log files, but there was nothing relevant as far as I could tell. There is however a massive `[yii\db\Command::query] SELECT` output that fills the entire queue.log file. I think it's a SQL query, but I'm definitely more of a frontend dev, so this is fairly baffling to me - not sure if it's related. 

### Steps to reproduce

1. Create a Matrix field
2. Create a block type called "Image"
3. Add a SuperTable field called "Options"
4. Add a Plain Text field called "Max-Width" (handle: "maxWidth")
5. Use the block on an entry, setting a value of '80%' for the maxWidth field

Expected template output: `style="max-width: 80%;"`
Actual template output: `style="max-width: 2000px;"` (which is the image width)

Any insight on what might be going on here would be greatly appreciated. Until now, I've never had any issues at all with this lovely plugin =) 

Thank you!

### Additional info

- The SuperTable field is nested within a Matrix field
- The SuperTable field is of the "Static" type
- The value is not output on preexisting entries, nor new entries
- I'm _not_ using the new project config thing

- Plugin version: 2.3.3
- Craft version: 3.3.20.1 (pro)

**EDIT:** I tried hitting the "Re-save Fields" button in the fixer (locally) and now everything is broken - admin and frontend. It's returning this error: `SQLSTATE[42S22]: Column not found: 1054 Unknown column 'content.field_criteria' in 'field list'`

**Comment by engram-design** [comment]
Not sure if you've gotten things back to normal, given the timeframe?

Its pretty hard to tell the whole picture without checking out your Super Table setup, and the front-end templates. Wondering if you'd be available to screenshare, or provide some level of access to debug further? If you're on the Craft Discord, feel free to get in touch and we can set up some time? My handle is `crawf`.

**Comment by engram-design** [comment]
Closing due to age.
