### ISSUE TITLE
Unable to delete a super table field with a large DB

### ISSUE THREAD

**Issue by timkelty** [engram-design/SuperTable#344]
I have a very large DB (~500k elements), and I'm trying to delete a Supertable field, and am unable to.

Here's what I've tried:

- Normal way, via CP (times out, not surprised: https://github.com/craftcms/cms/issues/5758)
- via CLI command, using `Craft::$app->fields->deleteField`: never timed out, but it churned on it for a good 20 mins before I gave up.
- Manually removing fields/blocks from project.yaml, then running `craft project-config/sync`: Same as above…never throws an error, but its been hung on trying to process that for over an hour now.

Any idea what could be so intensive about this? There are tons of elements in this app…would it try to loop through everything for some reason before it deleted the field?

**Comment by engram-design** [comment]
Hmmm, hard to say, but it shouldn't be doing anything to the elements, but judging from your issue with Craft core, this may not be a specific Super Table issue, if saving other items are similarly effected by this. Will see what a little bit of profiling can do.

**Comment by engram-design** [comment]
Soooo, I'm going to chalk this one up to a Craft core issue, as from my testing, I'm not sure if there's a _whole_ lot I can do about it at the field level...
