### ISSUE TITLE
Error in Project Config Sync about a ST MySQL table not existing

### ISSUE THREAD

**Issue by proimage** [engram-design/SuperTable#348]
### Description
Been developing locally, and created a supertable field (originally called "Two Squares" `twoSquares`, then renamed to just "Squares" `squares`) with a number of subfields. Committed, pushed, pulled down on stage, `composer install`ed, and then tried to `./craft project-config/sync`, only to get this error:

```
Applying changes from project.yaml ... error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ijmde_c3_s1.craft_stc_squares' doesn't exist
The SQL being executed was: ALTER TABLE `craft_stc_squares` ADD `field_text` text
```

### Steps to reproduce

1. No
2. Idea

### Additional info

- Plugin version: Super Table 2.4.4
- Craft version: Craft CMS 3.4.5

**Comment by engram-design** [comment]
Closing due to age (sorry for my delay), but not quite sure what's happened here, and it's probably been too long since your issue to follow up on things like if the `twoSquares` content table existed.
