### ISSUE TITLE
Dropdown Optgroup causes an issue with CraftQL querying

### ISSUE THREAD

**Issue by simeon-smith** [engram-design/SuperTable#349]
### Description

When you have a field that follows this structure:

Matrix Block > Super Table > Dropdown

Or with this structure:

Super Table > Dropdown

And you have an Optgroup in the dropdown it doesn't generate the correct GraphQL Schema for CraftQL. It appears to work fine for native GraphQL.

### Steps to reproduce

1. Make sure you have CraftQL.
2. Create a Super Table field.
3. Give it a Dropdown subfield
4. Check optgroup for one of the options.
5. Assign the field to a section.
6. Go to the CraftQL explorer by clicking on CraftQL on the left menu.
7. Search for the field handle.
8. It should not show up.
9. If you add another field to the Super Table field it should then show up with that other field as an option but not the Dropdown.
10. If you remove the optgroup then it will show up.

### Additional info

- Plugin version: 2.4.6
- Craft version: 3.4.10.1
- CraftQL version: 1.3.4

**Comment by engram-design** [comment]
Can you provide the query you're using? I've just tested both a Matrix and a Super Table field with a single dropdown field, containing optgroups, using the following:

```
{
    entries (section: "superTableTesting") {
        title

        ... on superTableTesting_superTableTesting_Entry {
            matrixOptgroup {
                ... on matrixOptgroup_dropdown_BlockType {
                    dropdown
                }
            }

            superTableOptgroup {
                ... on superTableOptgroup_BlockType {
                    dropdown
                }
            }
        }
    }
}
```

All field handles were showing up correctly as I typed them. Granted, I'm using GraphQL, not CraftQL - I just noticed your comment.

I feel like they're much the same, but we don't specifically support the CraftQL plugin in favour of native GraphQL.

**Comment by simeon-smith** [comment]
The issue is specifically with CraftQL. 

> And you have an Optgroup in the dropdown it doesn't generate the correct GraphQL Schema for CraftQL. It appears to work fine for native GraphQL.

I had opened an issue with them as well: https://github.com/markhuot/craftql/issues/332

I agree that native GraphQL seems the better choice if you only have the bandwidth to support one. But I have some plugins that don't have native support yet.

**Comment by engram-design** [comment]
Going to close this, as there's no plans to add support for CraftQL, sorry.
