### ISSUE TITLE
getContentTable() must be of the type string, null returned

### ISSUE THREAD

**Issue by pieterjandebruyne** [engram-design/SuperTable#350]
### Description

I upgraded Craft 2.6.2991 with supertable@1.0.5 to Craft CMS 3.4.8 with supertable@2.4.5
Some supertables with text-image field have their text removed. If I try to save the entry after re-entering the text I get this error:

`TypeError: Return value of verbb\supertable\elements\SuperTableBlockElement::getContentTable() must be of the type string, null returned in /Users/pieterjandb/Sites/mysite-dev/vendor/verbb/super-table/src/elements/SuperTableBlockElement.php:310`

Output of "http://mysite.test/index.php?p=craft/actions/super-table/plugin/check-content-tables":
`> ERROR: Super Table field #10 is missing its content table in settings ...
> ERROR: Super Table field #20 is missing its content table in settings ...
> ERROR: Super Table field #65 is missing its content table in settings ...
> ERROR: Super Table field #73 is missing its content table in settings ...
> ERROR: #10 has inconsistent field settings in its project config ...
> ERROR: #20 has inconsistent field settings in its project config ...
> ERROR: #65 has inconsistent field settings in its project config ...
> ERROR: #73 has inconsistent field settings in its project config ...
> ERROR: #78 has inconsistent field settings in its project config ...
> ERROR: #85 has inconsistent field settings in its project config ...
> ERROR: #91 has inconsistent field settings in its project config ...
> ERROR: #94 has inconsistent field settings in its project config ...
> ERROR: #97 has inconsistent field settings in its project config ...
> ERROR: #126 has inconsistent field settings in its project config ...
> ERROR: #133 has inconsistent field settings in its project config ...
> ERROR: #147 has inconsistent field settings in its project config ...
> ERROR: #155 has inconsistent field settings in its project config ...`

Fix Content Tables also gives a server error because mysqldump is not available in it's location..

`sh: mysqldump: command not found in /Users/pieterjandb/Sites/mysite-dev/vendor/craftcms/cms/src/db/Connection.php:611`

### Additional info

I upgraded Craft 2.6.2991 with supertable@1.0.5 to Craft CMS 3.4.8 with supertable@2.4.5

**Comment by engram-design** [comment]
MySQL backups are taken before you perform these fixes, and it sounds like it was unable to find the `mysqldump` command. Fixing that should help (which is probably a good idea to have that working in any case)

**Comment by Chrisedmo** [comment]
I also have this. I'm migrating a site from 2.9 to the latest.. I can confirm craft can the sql backups and running the `mysqldump` in my terminal works... ?
