### ISSUE TITLE
[FR] Compatibility with 3.4 Change Tracking

### ISSUE THREAD

**Issue by brettburwell** [engram-design/SuperTable#351]
The change tracking feature introduced in Craft 3.4 is super nifty, but it looks like it's not currently supported by Super Table. Just curious if this might be on the road map?

**Comment by engram-design** [comment]
Not sure I follow - we're mimicking the behaviour with Matrix, in that it'll show if the field's content has changed. Refer to https://d.pr/free/i/JFRcVd

But, maybe you mean each individual fields should show change tracking? Currently (and in that screenshot), I suppose you know _something_ in the Super Table (or Matrix) field has changed, but not what specifically.

**Comment by brettburwell** [comment]
Hi Josh. Thanks for the reply. 

I was absolutely overestimating how sophisticated the new change tracking feature was—and wrongly assumed that the individual Super Table fields would show change tracking too. 

It'd be awesome if that were the case, but if Craft's native Matrix field doesn't support this I certainly wouldn't expect Super Table to. 

Sorry to bother you!

**Comment by engram-design** [comment]
Never a bother! I'd certainly encourage a FR to the Craft Github repo for this.
