### ISSUE TITLE
Column heading text overlapping into other columns

### ISSUE THREAD

**Issue by bkmorse** [engram-design/SuperTable#352]
### Description
Column names are overlapping other column names

Looked fine when using super table for craft v2 (see image), it would break to a new line

### Steps to reproduce

Create a super table with 10 columns w/ 4+ word column names

### Additional info

super table 2.4.4
craft cms 

How it looks in craft v3.4.5
![Screen Shot 2020-04-01 at 12 33 11 PM](https://user-images.githubusercontent.com/84529/78162913-93248200-7415-11ea-99e8-6dfcab2e61b0.png)

See how it would break long column headings into new lines to fit within column in craft v2
![Screen Shot 2020-04-01 at 12 35 55 PM](https://user-images.githubusercontent.com/84529/78162914-93248200-7415-11ea-8fca-ddb60d1fabfc.png)

**Comment by engram-design** [comment]
Fixed in [2.4.7](https://github.com/verbb/super-table/releases/tag/2.4.7)
