### ISSUE TITLE
GraphQL: Fetching images in a matrix field within a super table field fails

### ISSUE THREAD

**Issue by peirix** [engram-design/SuperTable#354]
### Description
When trying to fetch assets in a matrix field within a super table field the array is always empty.

### Steps to reproduce

1. Create a super table field
2. Create a matrix field within it
3. Create a block with an asset field
4. Try to fetch those images from Graph QL

### Additional info

- Plugin version: 2.4.9
- Craft version: 3.4.17

I also filed an issue with Craft CMS because I'm not sure if this is a bug in super table, or the graphql. So feel free to close this if it's outside your domain.

**Comment by engram-design** [comment]
Just following up on this, like @andris-sevcenko has mentioned I can't seem to replicate this [either](https://github.com/craftcms/cms/issues/5998#issuecomment-623906996).

Out of interest, is the Super Table field a static field?

**Comment by peirix** [comment]
Thanks for following up. That's super weird. And I tried installing a new Craft now, at version 3.4.19 and can't replicate it any longer myself. But me and my coworker tried it multiple times with 3.4.17 and got the same result each time. So I guess it's sorted now? Don't know.

And no, it wasn't a static field.

**Comment by smcyr** [comment]
I have the same error on my end, the Graphql query returns an empty asset array with a Matrix inside a SuperTable.

**Comment by smcyr** [comment]
3.5.11 seems to have fixed the issue:
https://github.com/craftcms/cms/blob/develop/CHANGELOG.md#3511---2020-09-18
