### ISSUE TITLE
Unable to save a Super Table field’s settings

### ISSUE THREAD

**Issue by kaspar-allenbach** [engram-design/SuperTable#355]
### Description

I have a site which has super table fields but for unknown reasons the plugin wasn't installed on the production environment.

Now I installed the plugin on my local machine and everything was fine. Then I pushed it via project.yaml and now this error happens.

Error message:

> Status: Internal Server Error
> 
> Antwort: {"error":"Unable to save a Super Table field’s settings without knowing its content table: "}

Now what?

### Steps to reproduce

1. install plugin
2. ¯\_(ツ)_/¯

### Additional info

- Plugin version: 2.1.21
- Craft version: 3.1.23

**Comment by kaspar-allenbach** [comment]
So i was able to get the craft page up and running againt trough `./craft project-config/rebuild`

But now I can't  save any entries with supertable field:

> [error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Setting unknown property: verbb\supertable\records\SuperTableBlockRecord::ownerSiteId in //app/vendor/yiisoft/yii2/base/Component.php:209

**Comment by kaspar-allenbach** [comment]
i updated everything and now I get:

> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1651' for key 'craft_supertablecontent_4_celltable_elementId_locale_unq_idx'
> The SQL being executed was: INSERT INTO `craft_stc_4_celltable`
I then tried with the [FixFKs plugin](https://github.com/craftcms/cms/issues/3134).

But that doesn't help

**Comment by engram-design** [comment]
Have you run the content table checker/fixers? That's pretty important when going from Craft 2 > Craft 3, but can also fix other issues.

**Comment by engram-design** [comment]
Closing due to age.
