### ISSUE TITLE
Move getRelatedElementsQuery logic to modifyElementsQuery

### ISSUE THREAD

**Issue by Anubarak** [engram-design/SuperTable#356]
### Description
The syntax of Craft 3.4 allows us for relation fields to filter for related elements like
```PHP
Entry::find()->myRelationField($foo)->all();
```
Have you ever considered this behavior for your custom field just with only the full syntax instead of the short one?

```
Entry::find()->mySuperTableField(['field' => 'entriesFieldInSuperTable', 'element' => $foo])->all();
```

Your [modifyElementsQuery](https://github.com/verbb/super-table/blob/craft-3/src/fields/SuperTableField.php#L539) could then implement the logic from your [Service ](https://github.com/verbb/super-table/blob/craft-3/src/services/SuperTableService.php#L1065)

```php
public function modifyElementsQuery(ElementQueryInterface $query, $value)
{
    // ....
    // ...insert the existing :empty: :notempty: logic  
    // ....
    if(is_array($value) && isset($value['field']){
        $superTableFieldHandle = $value['field'];
        $superTableField = Craft::$app->fields->getFieldByHandle($superTableFieldHandle);
        $superTableBlockTypes = $this->getBlockTypesByFieldId($superTableField->id);
        $superTableBlockType = $superTableBlockTypes[0];
        
        // Loop the fields on the block type and save the first one that matches our handle
        $fieldId = false;
        foreach ($superTableBlockType->getFields() as $field) {
            if ($field->handle === $superTableBlockFieldHandle) {
                $fieldId = $field->id;
                break;
            }
        }
        
        // Check we got something and update the relatedTo criteria for our next elements call
        if ($fieldId) {
            $params['relatedTo']['field'] = $fieldId;
        } else {
            return false;
        }
        
        // Create an element query to find Super Table Blocks
        $blockQuery = SuperTableBlockElement::find();
        
        $blockCriteria = [
            'relatedTo' => $params['relatedTo']
        ];
        
        // Check for site param add to blockCriteria
        if (isset($params['site'])) {
            $blockCriteria['site'] = $params['site'];
        }
        
        Craft::configure($blockQuery, $blockCriteria);
        
        // Get the Super Table Blocks that are related to that field and criteria
        $elementIds = $blockQuery->select('ownerId')->column();

        // in the end only search for those elements
        $query->andWhere(['elements.id' => $elementIds]);
    }
}
```
Maybe it's just me, but I like that syntax much more instead of the current one
I would be fine with a custom event to implement it on my own as well 👍

**Comment by Anubarak** [comment]
Any thoughts on this?

**Comment by engram-design** [comment]
This was first implemented as part of a PR, so I'm largely unfamiliar with the code to be honest. I'll look at it properly at some stage.

**Comment by Anubarak** [comment]
I see, thanks for your answer. It's basically just moving the code from one place to another one.
The project luckily hasn't started where I have to query for many super table relations but this syntax would be much more convenient. Otherwise I would have to create a custom behavior and execute it there.

**Comment by engram-design** [comment]
The reason for this function (as I recall) was that it wasn't possible to query relations in the manner that you're suggesting. Particularly as in the past there were numerous Matrix-only conditionals in the Craft relations code, which just won't work the same way for Super Table. I guess that's changed in 3.4+, but not going to blindly move something that seems harmless without diving into it.

Your comment about syntax threw me a little, thinking that it needs to be changed - that's all. But if this is really down to syntactic sugar, and not preventing functionality, it's pretty low on my list when there are 3.5 compatibility changes to prioritise.

**Comment by engram-design** [comment]
Shelving this as I don't have the time to fully test this, and we're heading towards Craft 4 updates that will deem Super Table no longer required.

If for whatever reason you'd like this implemented in the short-term, and you've tested it out on your end, a PR is certainly more than welcome. But as I've mentioned, the work might not be worth the effort 🙂

**Comment by Anubarak** [comment]
@engram-design Alright, thank you for your answer.
Do you have more information about the release of Craft 4? 
When it's likely to be released within the next 6 months I'll maybe skip that too and wait until then.

**Comment by engram-design** [comment]
No information sorry, I would estimate the next 6-12 months at least.

FYI, I did start to look at it, I just don't (currently) have the available time to test it, as given the install base of Super Table, I don't want to change existing behaviour.
