### ISSUE TITLE
2.1.12 - 2.1.13 Update issue

### ISSUE THREAD

**Issue by bfjare** [engram-design/SuperTable#358]
Everything is updated to craft 3.4.20 but I can get super table past 2.1.12.

This is the error I get.

`yii\base\ErrorException: Undefined index:

Migration: verbb\supertable\migrations\m190227_000000_fix_project_config

Output:

Exception: Undefined index: (/Users/primeinc/Local Sites/montana-science-center/app/vendor/verbb/super-table/src/migrations/m190227_000000_fix_project_config.php:54)
#0 /Users/primeinc/Local Sites/montana-science-center/app/vendor/craftcms/cms/src/web/ErrorHandler.php(74): craft\web\ErrorHandler->handleError()
#1 /Users/primeinc/Local Sites/montana-science-center/app/vendor/verbb/super-table/src/migrations/m190227_000000_fix_project_config.php(54): craft\web\ErrorHandler->handleError()
#2 /Users/primeinc/Local Sites/montana-science-center/app/vendor/craftcms/cms/src/db/Migration.php(52): verbb\supertable\migrations\m190227_000000_fix_project_config->safeUp()
#3 /Users/primeinc/Local Sites/montana-science-center/app/vendor/craftcms/cms/src/db/MigrationManager.php(233): verbb\supertable\migrations\m190227_000000_fix_project_config->up()
#4 /Users/primeinc/Local Sites/montana-science-center/app/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp()
#5 /Users/primeinc/Local Sites/montana-science-center/app/vendor/craftcms/cms/src/services/Updates.php(233): craft\db\MigrationManager->up()
#6 /Users/primeinc/Local Sites/montana-science-center/app/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(510): craft\services\Updates->runMigrations()
#7 /Users/primeinc/Local Sites/montana-science-center/app/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\UpdaterController->runMigrations()
#8 /Users/primeinc/Local Sites/montana-science-center/app/vendor/yiisoft/yii2/base/InlineAction.php(57): craft\controllers\UpdaterController->actionMigrate()
#9 /Users/primeinc/Local Sites/montana-science-center/app/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/Users/primeinc/Local Sites/montana-science-center/app/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#10 /Users/primeinc/Local Sites/montana-science-center/app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#11 /Users/primeinc/Local Sites/montana-science-center/app/vendor/craftcms/cms/src/web/Controller.php(178): craft\controllers\UpdaterController->runAction()
#12 /Users/primeinc/Local Sites/montana-science-center/app/vendor/yiisoft/yii2/base/Module.php(528): craft\controllers\UpdaterController->runAction()
#13 /Users/primeinc/Local Sites/montana-science-center/app/vendor/craftcms/cms/src/web/Application.php(291): craft\web\Application->runAction()
#14 /Users/primeinc/Local Sites/montana-science-center/app/vendor/craftcms/cms/src/web/Application.php(646): craft\web\Application->runAction()
#15 /Users/primeinc/Local Sites/montana-science-center/app/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic()
#16 /Users/primeinc/Local Sites/montana-science-center/app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#17 /Users/primeinc/Local Sites/montana-science-center/app/public/index.php(21): craft\web\Application->run()
#18 {main}`

**Comment by bfjare** [comment]
When I run the table checker this is the error I get in the web.log

`2020-06-05 10:20:42 [-][1][9138e8946efa1dbb48a6250d9e372c46][error][TypeError] TypeError: Argument 1 passed to craft\services\Fields::getLayoutById() must be of the type int, null given, called in ....`

**Comment by engram-design** [comment]
Just waiting for a resolution on some other urgent Super Table issues, but this will be fixed in the next release, shortly

**Comment by engram-design** [comment]
Should be fixed in [2.5.1](https://github.com/verbb/super-table/releases/tag/2.5.1)
