### ISSUE TITLE
Eager loading the owner

### ISSUE THREAD

**Issue by billythekid** [engram-design/SuperTable#360]
Is it possible to eager load the owner in the block query?

I'm presuming it's not and that it's related to [this eager loading limitation](https://github.com/craftcms/cms/issues/1820#issuecomment-479188472) but figured it was worth asking.

Cheers

**Comment by engram-design** [comment]
Nope, sorry we're in the same boat as Craft's Matrix. No plans to look at this outside of Matrix's own solution.
