### ISSUE TITLE
Content is being deleted after adding a matrix block with Super Table with minimum rows in Live Preview

### ISSUE THREAD

**Issue by darylknight** [engram-design/SuperTable#361]
This is a really odd one. I've now seen the issue on two separate sites so I'm filing an issue about it with what info I have (I originally filed this on Craft, but it looks like it's caused by Super Table).

In the attached video, you can see:

1. Clicking Preview
2. Scrolling through the preview section, showing all matrix blocks
3. Scrolling through the editor, showing all matrix blocks
4. Adding a new matrix block to the bottom of the page
5. All the other blocks are still in the editor on the left, but they disappear from the Preview on the right
6. When I close preview, all the matrix blocks are still there in the CMS
7. Click publish. All the blocks except the one I just added are deleted

![ezgif-2-02a08c0e29fb](https://user-images.githubusercontent.com/1250017/83148527-c0ce3480-a101-11ea-9318-4736fb8d7f7f.gif)

I've narrowed this down to a really specific set of circumstances:

- It only happens when I add a matrix block with a super table field in it.
- It only happens when using Live Preview
- It only happens if that Super Table field is set to have a minimum number of rows. In my case, I'm using a Super Table block which allows either 1 or 2 columns, with a Redactor field in each. If the default number of rows is blank, it works fine. If I set the minimum number of rows to 1 or 2, it does what happens in the video.

In case it's code related, here's my template for that block:

```
{% switch block.textColumns|length %}
   {% case 1 %}{% set classes = 'col-12' %}
   {% case 2 %}{% set classes = 'col-12 col-lg-6' %}
   {% default %}{% set classes = 'col-12' %}
{% endswitch %}

{% for col in block.textColumns.all() %}
<div class="{{ classes }}">
   {{ col.text }}
</div>
{% endfor %}
```

### Additional info

- Craft version: 3.4.20
- PHP version: 7.4
- Database driver & version: MySQL

**Comment by engram-design** [comment]
I'll get a demo setup shortly. Out of interest, does it happen even if your template is a completely empty page? Just want to rule out templating.

EDIT: I can replicate this - digging in...

**Comment by darylknight** [comment]
Thanks Josh! Looks like Brandon just marked it as fixed here https://github.com/craftcms/cms/issues/6154.

**Comment by engram-design** [comment]
Yeah that was a tricky one, all credit to @brandonkelly for fixing it!
