### ISSUE TITLE
Row layout issue

### ISSUE THREAD

**Issue by GuiguiCucu** [engram-design/SuperTable#362]
### Description

I'm having a layout issue while adding a super-table block into an entry.
It seems that the grid layout of the super-table is broken. 
FYI I'm using a super-table block into a Neo field.
Once the entry is saved, the block displays normally.

Broken block :
![image](https://user-images.githubusercontent.com/3327842/83265652-123df880-a1c2-11ea-86c9-7db3ab0accd1.png)

Block once the entry is saved :
![image](https://user-images.githubusercontent.com/3327842/83265727-31d52100-a1c2-11ea-9df7-0b6ac1dcd9f4.png)

It happens only with the row layout. All works fine with matrix layout or table layout.

Thanks in advance.

### Additional info

- Plugin version: 2.4.9
- Neo version: 2.7.12
- Craft version: 3.4.21

**Comment by engram-design** [comment]
Can't seem to replicate this, which is odd. https://d.pr/free/v/NvBGnW

What browser/version are you using? Cleared all caches?

**Comment by GuiguiCucu** [comment]
Yes my cache was all cleared. I use Chrome 83, the latest version.
For now i reverted to the plugin version 2.4.6, before the CSS grid refacto.

**Comment by engram-design** [comment]
I haven't been able to replicate this exact bug, but I've fixed a few other CSS-grid related layout issues that might've fixed this.

To get the fix early, change your `verbb/super-table` requirement in composer.json to:

```
"require": {
  "verbb/super-table": "dev-craft-3 as 2.5.1",
  "...": "..."
}
```

Then run `composer update`

**Comment by engram-design** [comment]
Closing due to age.
