### ISSUE TITLE
Redactor within a super table within a matrix spits out no html

### ISSUE THREAD

**Issue by steveDL** [engram-design/SuperTable#363]
### Description
I don't know if this is an issue for you guys or the reactor repo but when using redactor inside of a supertable within a matrix there is no markup output. If you inspect the data in the browser, that comes from the redactor field then there is no HTML such as paragraph tags being output from the field.

I am using the same redactor field and the same config file in the surrounding matrix and not within the nested super table and this is outputting <p> tags as normal.

### Steps to reproduce

1. Create matrix
2. Create supertable inside matrix
3. Create redactor field

### Additional info

- Plugin version:
- Craft version:

**Comment by engram-design** [comment]
Can you clarify what you mean by no "markup output" - as in, the Redactor field just doesn't show? If so, I'm not seeing any issue with a few different field tests.

![Screen Shot 2020-05-30 at 3 39 17 pm](https://user-images.githubusercontent.com/1221575/83320527-c8214980-a28b-11ea-971d-90840b183841.png)

Cleared all the caches? Does redactor work in just Matrix, or just Super Table? Does it also work on its own?

**Comment by steveDL** [comment]
Sorry I wasn't very clear. What I mean is that if you inspect the data, in the browser, that comes from the redactor field then there is no HTML such as paragraph tags being output from the field.

I am using the same redactor field and the same config file in the surrounding matrix and not within the nested super table and this is outputting `<p>` tags as normal.  

I am using graphQL and nuxtjs.

**Comment by engram-design** [comment]
Would you be able to post a screenshot of what you're seeing? HTML seems to appear all okay on my end

**Comment by engram-design** [comment]
Closing due to age.
