### ISSUE TITLE
Super table with matrix field inside, empty on save

### ISSUE THREAD

**Issue by webburo-spring** [engram-design/SuperTable#367]
We have a super table field with a matrix field inside. When we have more than one matrix field added on a antry, and we are saving the entry, all of the content of the super table is empty.

Craft version: 3.4.23

**Comment by aminembarki** [comment]
same issue

**Comment by engram-design** [comment]
Are you on a multi-site install per chance?

When you mention more than one Matrix field added on any entry, just wanted to clarify its multiple Matrix + Super Table fields - not multiple Matrix blocks?

**Comment by engram-design** [comment]
Can you give [2.5.2](https://github.com/verbb/super-table/releases/tag/2.5.2) a go to see if this fixes things?

**Comment by hassanmah** [comment]
I have the same issue

Supertable: 2.5.2
Craft: 3.4.30

**Comment by engram-design** [comment]
@hassanmah Is your install a multi-site?

Are you in the same boat as @webburo-spring where its multiple fields being an issue? If so, wondering if you can send a screenshot through of the entry in question so I can try and replicate.

**Comment by hassanmah** [comment]
@engram-design no it's just a single site set up.

It's on when I have a matrix within a supertable within a matrix.

I'm away from my desk for a few days but I'll try to explain the issue.

I have a matrix block called 'Two col', with that is a super table call 'Col', 'Col' contains a matrix called 'button'

It is button that isn't saving it's content.

It is also not updating when in live preview

**Comment by hassanmah** [comment]
@engram-design it looks like this issue is linked to the Supertable plugin too https://github.com/craftcms/cms/issues/6480 seems like same issue

**Comment by engram-design** [comment]
@hassanmah Thanks for the reference. I cannot replicate this behaviour though, so wondering if you might be able to post a short screen recording illustrating the issue? It goes without saying to make sure you're also on the latest Super Table and Craft versions. Hopefully I can try to reproduce this.

See [2.6.0](https://github.com/verbb/super-table/releases/tag/2.6.0)

**Comment by andyharris** [comment]
[Save issue.mp4.zip](https://github.com/verbb/super-table/files/5059062/Save.issue.mp4.zip)

Here's a screen recording of the issue Hassan is describing above.

**Comment by engram-design** [comment]
Thanks for the video @andyharris I'm going to be super-annoying as mention that it probably doesn't contain a critical bit of information, which is the loading spinner at the top of the page (next to the buttons in live preview and revisions dropdown when not). If it's not showing this loading spinner, something is going on and not triggering a re-save of the draft when you make your changes.

Rather than get you to create another video, can you confirm what the loader spinner does in these instances, and if there's any time that it doesn't appear?

**Comment by oscarpett** [comment]
Yes the loading spinner works in preview and the tick mark appears after it. I've attached a shorter screen recording.
When the preview is closed, the tick mark and draft is also generated. When opening the preview it also spins and creates the draft. At the moment we have this issue across two separate sites and the steps to replicate are exactly the same.

Edit: It's also worth noting that editing any other fields like then main title for the block etc works as expected. As soon as the Super Table is touched, the issue appears. Scenarios include: Matrix > Super Table or Matrix > Super Table > Matrix.

[save v2.mp4.zip](https://github.com/verbb/super-table/files/5060950/save.v2.mp4.zip)

**Comment by andersaloof** [comment]
@engram-design I've referenced this issue on an issue I assume is related (https://github.com/craftcms/cms/issues/6553), the only difference is that I have a super table inside a matrix and not the other way around. I can send you a database dump, composer files and instructions if that helps you debug the issue?

**Comment by andyharris** [comment]
@engram-design Has this helped at all - we're using this setup on a couple of client projects and it's causing us some big headaches. I know the plugin is free so support isn't a given so I apologise for asking!

**Comment by engram-design** [comment]
Still working on this, as It's a bit complicated, and starting to get beyond my abilities. I have however isolated this to only when editing a saved entry. For instance, if you edit the entry, save and then refresh the page, you'll be editing a draft. Content seems to be saving correctly in this case when continuing to edit the draft.

I believe this is due to the delta updates, but reaching out to @brandonkelly for some assistance on this...

**Comment by hassanmah** [comment]
@engram-design 

You can use [this](https://drive.google.com/file/d/1nG-oyzhg1P5ENmgQX53Y1wE0_0tyUGx0/view?usp=sharing) clean craft build with two block you can use to replicate the issue. Along with the sql backup.

Let me know if you have any question

Thanks, 
Hassan

**Comment by engram-design** [comment]
Thanks, no issues with replicating the issue, just working on fixing it...

**Comment by brandonkelly** [comment]
This ended up being a Craft bug, and has now been fixed for the next release! (craftcms/cms#6480)

**Comment by engram-design** [comment]
Thanks @brandonkelly amazing as always!

**Comment by andyharris** [comment]
Thanks all, it's hugely appreciated as always.

**Comment by engram-design** [comment]
FYI, just awaiting a Craft release for this fix to be applied - https://github.com/craftcms/cms/issues/6480
