### ISSUE TITLE
Class 'verbb\supertable\fields\Locale' not found

### ISSUE THREAD

**Issue by iamtompickering** [engram-design/SuperTable#373]
### Description
I am running into the following error in the CMS when trying to view pages with a super table field on them: 

```
Class 'verbb\supertable\fields\Locale' not found
```

<img width="1270" alt="Screenshot 2020-07-30 at 12 53 19" src="https://user-images.githubusercontent.com/6592882/88919812-aaf50100-d263-11ea-8d34-2acb32a54150.png">

I had this same issue on another site which was running plugin version 2.5.2 and craft version 3.4.29.1, and to fix it I reverted the plugin back to 2.5.0. 

But on my other site, I am running plugin version 2.5.3 and craft version 3.4.30. If I rollback the plugin version on this site to 2.5.0, I get the following error: 

```
Setting unknown property: verbb\supertable\fields\SuperTableField::placeholderKey
```

These sites are running multiple sites (languages) and the initial error seems to be linked with the propagation method that is set on the super table field. 

### Additional info

- Plugin version: 2.5.3
- Craft version: 3.4.30

**Comment by engram-design** [comment]
Should already be fixed in [2.5.4](https://github.com/verbb/super-table/releases/tag/2.5.4)
