### ISSUE TITLE
Unstyled/Invisible Layout

### ISSUE THREAD

**Issue by pixelmachine** [engram-design/SuperTable#376]
Sometimes when nesting a Matrix or using Super Table (usually in static mode) to group some fields, it would be nice if Super Table didn't add any UI. You end up with very similar block titles and UI nesting:

```
Matrix block: List
-- Super Table: List items
---- Text field: List item
```
This is functionally equivalent to:
```
Matrix block: List
-- Text field: List item
-- Text field: List item
```

**What's your proposed solution?**
Adding an additional layout with a hidden label and no styling allows the developer the power of Super Table without the extra UI overhead for the content author.

I've tested this with good results using Super Table's table layout and simply setting the following six styles on the table:

```sass
.superTable-table {
  border: 0
  margin: 0
  box-shadow: initial
  thead {
    display: none
  }
  td {
    background: transparent
    padding: 0
  }
}
```

![Screen Shot 2020-08-07 at 13 10 49](https://user-images.githubusercontent.com/1082223/89670976-1d8f5d80-d8b0-11ea-9535-887555c895c8.png)

- **List** is a Matrix block
- **List items** is a Matrix inside a unstyled/invisible Super Table
- **Text** and **Page link** are Matrix blocks inside **List items**

**Comment by engram-design** [comment]
You could probably achieve this with [cp-css](https://plugins.craftcms.com/cp-css). I'm very much pairing back adding new features with native nested Matrix support coming in the next few Craft versions.

**Comment by pixelmachine** [comment]
You can indeed achieve this with cp-css – that's how I setup the above screenshot. Obviously that has limitations like being applied to all instances or specific instances using an ID or handle in the CSS. Neither particularly friendly.

That said, your hesitance is understandable, let me see if I can work up some non-Matrix based examples to see if it's still worth considering.

**Comment by engram-design** [comment]
Very likely not going to happen (sorry), as we push towards a native Craft 4 solution.
