### ISSUE TITLE
Invalid argument supplied for foreach() PHP Warning in SuperTable 2.6.0 Update

### ISSUE THREAD

**Issue by lexislav** [engram-design/SuperTable#377]
**Description**
After updating to 2.6.0, I am getting PHP warning in some templates:

1. in /Users/lexislav/Websites/koma-family.cz/vendor/verbb/super-table/src/elements/db/SuperTableBlockQuery.php at line 407
398399400401402403404405406407408409410411412413414415416 
    /**
     * @inheritdoc
     */
    protected function cacheTags(): array
    {
        $tags = [];
        // If both the field and owner are set, then only tag the combos
        if ($this->fieldId && $this->ownerId) {
            foreach ($this->fieldId as $fieldId) {
                foreach ($this->ownerId as $ownerId) {
                    $tags[] = "field-owner:$fieldId-$ownerId";
                }
            }
        } else {
            if ($this->fieldId) {
                foreach ($this->fieldId as $fieldId) {
                    $tags[] = "field:$fieldId";
                }

**Additional info**
- Plugin version: 2.6.0
- Craft version: 3.5.2
- Multi-site: Yes

**Comment by engram-design** [comment]
Should be fixed in [2.6.0.1](https://github.com/verbb/super-table/releases/tag/2.6.0.1)
