### ISSUE TITLE
Class 'verbb\\supertable\\fields\\SuperTableInputType' not found since Craft Core last update 

### ISSUE THREAD

**Issue by yingban** [engram-design/SuperTable#378]
**Description**
Hi,
I just updated Craft to the last version 3.5.2, and I got the following error 
`Class 'verbb\\supertable\\fields\\SuperTableInputType' not found`
when I try to perform a GraphQL query or rebuild the config for the CP

**Additional info**
- Plugin version: 2.6.0
- Craft version: Craft Pro 3.5.2
- Multi-site: No

Thank you for your help

**Comment by engram-design** [comment]
Should be fixed in [2.6.0.1](https://github.com/verbb/super-table/releases/tag/2.6.0.1)
