### ISSUE TITLE
'verbb\supertable\helpers\SuperTable' not found

### ISSUE THREAD

**Issue by dgtlcrftrs** [engram-design/SuperTable#379]
I'm trying to rebuild the project.yml (latest version of craft 3.5.2 and sper-table)

https://github.com/verbb/super-table/blob/1f6919a1dff6f2e0476ee117097a08a4e040ba7d/src/helpers/ProjectConfigData.php#L20

**Comment by engram-design** [comment]
Fixed in [2.6.0.3](https://github.com/verbb/super-table/releases/tag/2.6.0.3)
