### ISSUE TITLE
Field instructions displaying in duplicate locations with Craft 3.5

### ISSUE THREAD

**Issue by TheFunkyMonk** [engram-design/SuperTable#381]
**Description**

With Craft 3.5, Super Table fields that contain fields with instructions are duplicating the instructions as both an info icon tooltip as well as inline above the field content (happening in both Row and Table layout).

**Steps to reproduce**
1. Create a Super Table field containing another field with Instructions for the field.
2. View field in entry
**Expected Result**: Instructions are displayed behind a tooltip as in previous versions of Super Table.
**Actual Result**: Instructions are displayed both behind a tooltip and duplicated inside the field content.

**Additional info**
- Plugin version: 2.6.1
- Craft version: 3.5.5
- Multi-site: No

![Screen Shot 2020-08-19 at 3 47 58 PM](https://user-images.githubusercontent.com/1728770/90697503-6beb1780-e233-11ea-9ff3-01c3f4b13dd7.png)

**Comment by engram-design** [comment]
Fixed in [2.6.2](https://github.com/verbb/super-table/releases/tag/2.6.2)
