### ISSUE TITLE
SuperTable label field

### ISSUE THREAD

**Issue by 1stevengrant** [engram-design/SuperTable#383]
I'm currently upgrading from Craft 2 > 3 and it seems the label field isn't available?

Any alternatives to use?

**Comment by engram-design** [comment]
Yep, it was never really meant to be in there to begin with sorry.

Seems like this might be reasonable - https://plugins.craftcms.com/read-only, https://plugins.craftcms.com/incognito-field, https://plugins.craftcms.com/readonly

**Comment by 1stevengrant** [comment]
Super, thank you
