### ISSUE TITLE
Matrix Field Layout styling bug

### ISSUE THREAD

**Issue by bymayo** [engram-design/SuperTable#384]
**Description**

When I create a SuperTable and have it set to Matrix Field Layout style and also Static field, the drag/tick header is a bit misaligned:

![Screenshot 2020-09-17 at 14 00 53](https://user-images.githubusercontent.com/522877/93473709-3e56c400-f8ee-11ea-94d5-30002fdaad91.png)

**Additional info**
- Plugin version: 2.6.2
- Craft version: 3.5.10.1
- Multi-site: No

**Comment by engram-design** [comment]
Fixed in [2.6.3](https://github.com/verbb/super-table/releases/tag/2.6.3)
