### ISSUE TITLE
Matrix -> Supertable -> Matrix - cannot add new block

### ISSUE THREAD

**Issue by nevsie** [engram-design/SuperTable#386]
I Have a pre Craft 3.5 site, which i just updated. Along with Supertable to latest:
Craft CMS  3.5.11.1
Super Table  2.6.2

As per title i have a matrix -> supertable -> matrix setup.
I can save new blocks in the first matrix, the next supertable, but the third matrix will not let me add them. 

I have tried different fields, names, etc. But no joy.
Running the check on table content i get:
> ERROR: #19 has inconsistent field settings in its project config ...

I run the fix, but the field can still not be added. 
And then the error in the check table comes back again.
The fix shows the message:
> Super Table field #19 has content table {{%stc_9_columns}} ...

Any help is appreciated. N

**Comment by icreatestuff** [comment]
I'm experiencing the same thing, also on:

- Craft 3.5.11.1
- Super Table 2.6.2

**Comment by userAW** [comment]
I'm also experiencing the same thing, Craft 3.5.11, 2.6.2

Any updates on when this will be resolved? Thank you.

**Comment by engram-design** [comment]
From my testing this seems to have been caused in Craft https://github.com/craftcms/cms/commit/dc8bdee51cde6091b302a3b87841e27576a218f1

Investigating further.

**Comment by engram-design** [comment]
This should be fixed in Craft https://github.com/craftcms/cms/commit/abe38c873565015955047cea923d15a5231dd988

To get the fix early, change your `craftcms/cms` requirement in `composer.json` to:

```
"require": {
  "craftcms/cms": "dev-develop as 3.5.11.1",
  "...": "..."
}
```

Then run `composer update`.

**Comment by userAW** [comment]
Thank you, Josh.
