### ISSUE TITLE
Project config required options

### ISSUE THREAD

**Issue by iamtompickering** [engram-design/SuperTable#387]
**Description**
On a couple of projects using project config, I have noticed that some of the changes are just required values being changed from `'0'` to `false`. It only seems to be happening on super table fields from what I can see. 

It doesn't seem to be causing any issues, but thought it would be worth logging as it may be a minor bug.  

**Additional info**
- Plugin version: 2.6.1
- Craft version: 3.5.5
- Multi-site: No

<img width="1272" alt="Screenshot 2020-10-09 at 11 35 29" src="https://user-images.githubusercontent.com/6592882/95573576-8ff0fb00-0a23-11eb-9b75-b8a278664f6b.png">

**Comment by engram-design** [comment]
I've noticed this as well, but might be related to Craft itself - https://github.com/craftcms/cms/issues/6979

We actually call `Craft::$app->getFields()->createFieldConfig($field)` for each of the nested field in a Super Table block, so I don't think it'll be specific to Super Table.

**Comment by engram-design** [comment]
This is a Craft core issue, and fixed in Craft 3.6+ due to updated to the Project Config handler, and PHP version to allow type checks easier. This means across the board, you won't be getting these issues.
