### ISSUE TITLE
Add show field handles in CP

### ISSUE THREAD

**Issue by juban** [engram-design/SuperTable#388]
**What are you trying to do?**
Latest Craft CMS 3.5 introduced a handy "Show field handle" feature in CP with copy capabilities.
Turning on that feature does not show the according field handle item for Super Table sub-fields

**What's your proposed solution?**
It would be really nice to have the field handle shown for Super Table fields as for other native fields for a better DX.

**Comment by nstcactus** [comment]
I'd love that as well. Bonus points for supporting the CP field inspect plugin : open the field settings when the handle is clicked.

**Comment by engram-design** [comment]
Very likely not going to happen (sorry), as we push towards a native Craft 4 solution.
