### ISSUE TITLE
Icon Picker field dropdown being cut off

### ISSUE THREAD

**Issue by iamtompickering** [engram-design/SuperTable#389]
**Description**

<img width="652" alt="Screenshot_2020-10-19_at_4 34 06_PM" src="https://user-images.githubusercontent.com/6592882/98100916-72c81480-1e89-11eb-83cb-48db3f401955.png">

**Additional info**
- Plugin version: 2.5.4
- Craft version: 3.4.30
- Multi-site: Yes or No

**Comment by engram-design** [comment]
I can't seem to replicate this with Icon Picker 1.1.9, using any of the Super Table layouts:

![Screen Shot 2020-11-28 at 4 47 25 pm](https://user-images.githubusercontent.com/1221575/100494808-6b024400-3199-11eb-911f-c912bbccba42.png)
