### ISSUE TITLE
Unable to delete a Super Table field within a Matrix in Safari

### ISSUE THREAD

**Issue by darylknight** [engram-design/SuperTable#391]
**Description**

I'm editing a field with this structure:

```
Matrix
> Super Table
```

In Chrome, I can delete the sub-fields in the Super Table field just fine (text/image/heading) but in Safari, the red delete button doesn't do anything.

**Additional info**
- Plugin version: 2.6.3
- Craft version: 3.5.15.1
- Multi-site: No

**Comment by engram-design** [comment]
Can't replicate this with with Safari 14. Can you confirm your version number and OS? It would also be helpful to get a screenshot of your full field settings just in case that's a factor.

Just to be clear, are you talking about deleting the nested Super Table field itself, or the sub-fields inside it. I can do both, but your request seems to refer to both?

**Comment by darylknight** [comment]
I think we just close this - I can't replicate it anymore either (and I can't remember which site I was working on). Thanks for checking it though.
