### ISSUE TITLE
Hyphen in GraphQL type name causing issues

### ISSUE THREAD

**Issue by Tam** [engram-design/SuperTable#393]
**Description**
The hyphen in the block type name is causing issues with some GraphQL parsers, since they are not valid for use in type names.

https://github.com/verbb/super-table/blob/2505291b879f559ce6ba8a96ebd1fd8f75ba2b22/src/models/SuperTableBlockTypeModel.php#L103

**Additional info**
- Plugin version: 2.6.3
- Craft version: 3.5.15.1
- Multi-site: Yes

**Additional context**
Tested using the JS GraphQL plugin for WebStorm.

**Comment by engram-design** [comment]
Updated in [2.6.4](https://github.com/verbb/super-table/releases/tag/2.6.4) - I believe and underscore should be valid, correct?
