### ISSUE TITLE
Wrong return type hint?

### ISSUE THREAD

**Issue by rostockahoi** [engram-design/SuperTable#394]
https://github.com/verbb/super-table/blob/d1e7b06082aebb67750e0793eaa7f0e5a868107e/src/services/SuperTableService.php#L1041

Hi there,
shouldn't this return type hint be some of
`* @return ElementQuery` or
`* @return ElementQueryInterface`?

I just had trouble with autocompletion in my IDE. Looks like somehow `ElementCriteriaModel` made to the Craft 3 version of the plugin. I think this is a class from Craft 2 times.

**Comment by rostockahoi** [comment]
If I am right I - not 100% sure - I could create a PR.

**Comment by engram-design** [comment]
Yep, totally correct here! Should be updated in [2.6.4](https://github.com/verbb/super-table/releases/tag/2.6.4)
