### ISSUE TITLE
Null values and fixing loop

### ISSUE THREAD

**Issue by alanski66** [engram-design/SuperTable#395]
**Description**
NUll fields returned from supertable.
> ERROR: #60 has inconsistent field settings in its project config ...

**Steps to reproduce**
1. Add matrix field tabs
2.Add supertable field tabs
3. Add fields for tabs

**Additional info**
- Plugin : 2.6.4
- Craft version: Craft Solo 3.5.16
- Multi-site:  No

**Additional context**
Migration from Craft 2 to Craft 3
Local dev Laravel Valet

I can loop thru the matrix block but dumping the block shows null field values despite having edited and saved the content

I have used Supertable alot but not come across this before.

Fixing content tables results in 
> ERROR: #60 has inconsistent field settings in its project config ...
Which when saved just repeats for field 59 and 60.
Syncing project config doesnt help just ends up in a loop for these fields......

Error Log shows no errors

**Comment by penguyen1** [comment]
also having this issue. seems to be coming from the most recent updates since i've never came across these issues before until recently.

**Comment by engram-design** [comment]
I can't replicate this behaviour.

If someone here uses [Field Manager](https://plugins.craftcms.com/field-manager), it'd be great to get an export of the field they're using so I can try to replicate on my end.

**Comment by engram-design** [comment]
Refer to https://github.com/verbb/super-table/issues/399#issuecomment-768015110

I've just fixed this by implementing Craft 3.5.16's functionality in [2.6.6](https://github.com/verbb/super-table/releases/tag/2.6.6), which should restore the behaviour you're used to and fix this issue.

As for the content table checker-loop, this will be addressed in Craft 3.6+ where Project Config changes are more reliable.
