### ISSUE TITLE
"Couldn't Save Field"

### ISSUE THREAD

**Issue by dustinhansen** [engram-design/SuperTable#4]
My Super Table field saves fine with no column data but as soon as I add any sort of column, no matter what options I put in it I get a "Couldn't Save Field" error message.

Using Craft Pro 2.3.2644, Super Table 0.2.7

**Comment by dustinhansen** [comment]
I see now that this is because I was using "Title" as the name of the field, which is apparently a protected word. This will get resolved with the better error handling that is on the roadmap already.

**Comment by engram-design** [comment]
@dustinhansen Yep, that'll do it! Glad you noticed better error handling is on the roadmap, at the moment there is little to no validation around reserved handles for columns. Just working through the visual feedback, especially for fields in Matrix in a Super Table
