### ISSUE TITLE
Display Category with a link

### ISSUE THREAD

**Issue by martinsmith** [engram-design/SuperTable#40]
Hi there... I'm trying to output a category defined in SuperTable but also link to that category on the front end.

![image](https://cloud.githubusercontent.com/assets/5725864/10690686/5573a420-797b-11e5-813f-967caed8c68c.png)

I'm sorry for not being too good with templating but I currently have this which is giving me the specialism title but not the category??

        {% for row in entry.specialisms %}
                <li>{{ row.specialismTitle }}<a href="{{ category.url }}">{{ row.spicialismLink }}</a></li>
        {% endfor %} 

Any help appreciated thanks

Martin

**Comment by martinsmith** [comment]
Sorry, I worked it out

            {% for category in row.spicialismLink %}
                <a href="{{ category.url }}">{{ row.specialismTitle }}</a>
            {% endfor %}

Thanks

**Comment by engram-design** [comment]
Hey @martinsmith sorry for not responding. Because Categories is an element, it'll always return a collection of elements. This is why you'd loop through these options (as you have done), or using something like `{{ row.spicialismLink.first.url }}`.

**Comment by martinsmith** [comment]
Hi there!  thanks for your response.  I've just discovered {{ category.url }} will only link to the top level category page?  In the 'spicialismLink' field I have selected a sub-category but on the front end it only provides the url to the parent??

Any ideas?

**Comment by engram-design** [comment]
Have you double-checked it is the right category using `{{ category.title }}`?

**Comment by martinsmith** [comment]
Hi,  {{ category.title }} just pulls back the top level.  :/

**Comment by engram-design** [comment]
I'm pretty sure that a category field will always include the top level category - thats not a Super Table thing, have a look at the below:

![screen shot 2015-10-24 at 8 41 37 am](https://cloud.githubusercontent.com/assets/1221575/10705623/151cd8f0-7a2b-11e5-8d08-e3f606d6af9a.png)

**Comment by bossanova808** [comment]
Categories in Craft are really taxonomies, i.e. hierarchical structures.  If you don't want the parent-child style relationship, you probably just want a more general relations approach.

However you can of course specify e.g. the level you want when retrieving the category..e.g. something like

```
{% set categories = craft.categories.group( segment_1 ~ 'Categories').level(2) %}
```

**Comment by martinsmith** [comment]
Thanks bossanova808, unfortunately there will be a mix of levels so I can't be that specific in the template.

So...

Parent
------ Child
------ Child 2
------ Child 3

There is no way I can select, show and link to Child 2 category page?

Thanks

**Comment by martinsmith** [comment]
Hi again... sorry, i'm thinking of another way around this and instead of using categories i'm going for related entries.  Now all I need is the template syntax to output a related entry field from a SuperTable row?

![image](https://cloud.githubusercontent.com/assets/5725864/10736347/57e950a2-7c04-11e5-90b0-5946769e5a80.png)

**Comment by martinsmith** [comment]
Sorry, i've got it..

      <ul>
        {% for row in entry.specialisms %}
        <li><a href="{{ row.linkToPage.first().url }}">{{ row.specialismTitle }}</a></li>
        {% endfor %}  
      </ul>
