### ISSUE TITLE
Issue with gatsby-source-craft / Gatsby Helper plugin

### ISSUE THREAD

**Issue by alexhillel** [engram-design/SuperTable#401]
I'm having an issue with a couple of projects when using gatsby-source-craft and Gatsby Helper together with Super Table. I submitted a bug report to Andris who reported it was Super Table causing the issue. I'm just wondering if it's on the radar to be fixed?

Andris said the following:

So, this is because SuperTable plugin is not implementing some stuff. I've let Josh know about this, but, meanwhile, you can just drop this code anywhere that gets executed - might be your custom plugin, maybe a custom module:

```
  \yii\base\Event::on(\craft\gatsbyhelper\services\Deltas::class, \craft\gatsbyhelper\services\Deltas::EVENT_REGISTER_IGNORED_TYPES, function(\craft\gatsbyhelper\events\RegisterIgnoredTypesEvent $event) {
      $event->types[] = \verbb\supertable\elements\SuperTableBlockElement::class;
  });
```

Obviously, you'll want to simplify the class names by using the use statement, but that makes it a less copy-paste-able code block :)

For reference - https://github.com/craftcms/gatsby-helper/blob/main/src/services/Deltas.php#L52. This is an event plugins can tap in to tell Gatsby which elements will only be updated as part of other element updates.

**Comment by engram-design** [comment]
Should be fixed in [2.6.7](https://github.com/verbb/super-table/releases/tag/2.6.7)
