### ISSUE TITLE
SuperTable: -> "Check Content Tables" and "Re-save Fields" overwrite each other

### ISSUE THREAD

**Issue by LeoWie93** [engram-design/SuperTable#404]
**Description**
I'm tried using the tools from this plugin to clean up my project-config and found this issue.

Inside the settings using the "Super Table" Tools
These two steps always fix/overwrite each other:

1. Check Content Tables:
- [Craft CP output before usage](https://user-images.githubusercontent.com/29427760/110125648-d6c10200-7dc3-11eb-9120-54470be08f0a.png)
- [Craft CP output after usage](https://user-images.githubusercontent.com/29427760/110124851-e55ae980-7dc2-11eb-87f0-21a8cb932dac.png)

2. Re-save Fields: [Craft CP result](https://user-images.githubusercontent.com/29427760/110124914-fe639a80-7dc2-11eb-946e-335b1d1d43fb.png)
- But changes these normal matrix block  types: [image](https://user-images.githubusercontent.com/29427760/110125088-3834a100-7dc3-11eb-988f-5f0be07ed0ce.png)
- By doing this to them: [image](https://user-images.githubusercontent.com/29427760/110125153-4be00780-7dc3-11eb-8fe8-6ed90d7fc6e7.png)

Using them one after the other they always overwrite each others changes.

**Additional info**
- Plugin version: 2.6.7
- Craft version: 3.6.8
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
Fixed in [2.6.8](https://github.com/verbb/super-table/releases/tag/2.6.8)
