### ISSUE TITLE
SuperTable and related entries

### ISSUE THREAD

**Issue by martinsmith** [engram-design/SuperTable#41]
I'm trying to pull through content based on items within a SuperTable entries field.

After searching around I currently have this:

{% set individuals = craft.entries({section: 'barristers', relatedTo: { targetElement: entry, field: 'specialisms.linkToPage'}}) %}
{% for entry in individuals %}
  {{ entry.title }}
But it's not pulling anything through?

Any help appreciated

Thanks

**Comment by engram-design** [comment]
Solution posted on http://craftcms.stackexchange.com/questions/12122/supertable-and-related-entries/12123#12123

**Comment by martinsmith** [comment]
Wonderful thank you.  Apologies for posting in two places but the clock is ticking on this project :/
