### ISSUE TITLE
Field organization

### ISSUE THREAD

**Issue by TomDeSmet** [engram-design/SuperTable#410]
**What are you trying to do?**
I'm using the Matrix layout for Super Table fields and it would be nice if we could organize the fields a bit better.
I was thinking about Matrix Mate or Spoon functionalities. Putting the different fields in different tabs inside the Super Table field.

**Comment by engram-design** [comment]
Very likely not going to happen (sorry), as we wait for the path to Craft 4 and Matrix improvements natively.
