### ISSUE TITLE
Hard delete blocks that are not required anymore

### ISSUE THREAD

**Issue by nesh-ram** [engram-design/SuperTable#411]
**What are you trying to do?**
A description of what you want to happen.
Hard delete blocks and field value when draft auto save is turned on in CMS

**What's your proposed solution?**
A description of how you think this could be solved, including any alternatives that you considered.
Consider using hard delete true when deleting blocks

SuperTableService::_deleteOtherBlocks
        /** @var Element $owner */
        $deleteBlocks = SuperTableBlockElement::find()
            ->anyStatus()
            ->ownerId($owner->id)
            ->fieldId($field->id)
            ->siteId($owner->siteId)
            ->andWhere(['not', ['elements.id' => $except]])
            ->all();

        $elementsService = Craft::$app->getElements();

        foreach ($deleteBlocks as $deleteBlock) {
            $elementsService->deleteElement($deleteBlock, true);
        }

**Additional context**
1. Soft deleted block records are increasing over time due to soft delete.
2. Can't we simply update the existing block? Why should old blocks be soft deleted and create new block?

**Comment by engram-design** [comment]
I'll look into this further, but I will comment that we are following what Matrix does, for the time being, so we're largely taking their lead as to why this is the way it is.
