### ISSUE TITLE
Documemtation request: How to update existing supertable data

### ISSUE THREAD

**Issue by anchovy** [engram-design/SuperTable#412]
Be great if we can get an example of how to update/modify data from an existing suber-table field.
I've seen the documentation on how to [add a new supertable row](https://verbb.io/craft-plugins/super-table/docs/template-guides/php-example) but for the life of me I can't work out how to modify the data from an existing supertable row.

**Comment by engram-design** [comment]
Just added some docs for this. You can use delta updates to simplify the entire process, so you don't need to fetch the content for existing blocks. This is achieved through `sortOrder` properties.

https://verbb.io/craft-plugins/super-table/docs/template-guides/php-example#updating-existing-field-content

The same thing can also be done with Matrix - FYI https://github.com/craftcms/cms/issues/5717#issuecomment-591058311
