### ISSUE TITLE
"Add row above" option on an existing row

### ISSUE THREAD

**Issue by jayhlee** [engram-design/SuperTable#415]
**What are you trying to do?**
I'd like to add a row above an existing row, just like how you can select the "gear" icon on a matrix block and "Add <block> above."

**What's your proposed solution?**
When the Field Layout is set to "Matrix Layout," a "gear" icon shows, just like a Matrix block. However, only Collapse and Delete options are available. Including "Add row above" to the option list would be great.

**Additional context**
When there's a lot of rows, trying to add a new row and dragging/dropping it to the first row can get challenging.

**Comment by jsunsawyer** [comment]
This would be "super" beneficial to us for a specific project.

We have a map component on a page with a bunch of locations, each location being a block in a super table field.

The order of the locations matter, so when a user has to add a new location, it goes to the end, then they have to drag it clear up past any other locations.

Basically, it'd be nice if the "matrix" view of super table behaves just like matrix fields do now.

**Comment by engram-design** [comment]
Super Table has now reached its end of life, and we'll be sticking with bug/security fixes from here on out. More in the [announcement](https://verbb.io/blog/so-long-super-table).
