### ISSUE TITLE
Bug/Freq id fields for Super Table matrix fields missing for GraphQL mutations

### ISSUE THREAD

**Issue by humandevs** [engram-design/SuperTable#416]
Not quite sure if this is a limitation of Super Table or a Craft issue, so have cross-posted this bug to https://github.com/craftcms/cms/issues/9092 as a CraftCMS issue as well.

We're trying to update matrix blocks nested inside a super table matrix block via GraphQL, but in the GraphQL mutation the id field for the matrix block appears to be missing when it is nested inside a super table matrix block.

The Graphiql interface shows the id and sortOrder fields for matrix fields, but the id field is missing for nested matrix fields inside a Super Table matrix field.

As an example, take a nested matrix field inside a Super Table Matrix field, where the outside matrix is a list of article steps, and the inside matrix is a list of content blocks within that step:
![![image](https://user-images.githubusercontent.com/57273245/123548333-38153400-d719-11eb-8b40-6904080207b0.png)](https://user-images.githubusercontent.com/57273245/123548328-30ee2600-d719-11eb-85da-8442d7c47e92.png)

For a normal non-nested matrix field (in this example, an article that only has one step and thus is not nested within a Super Table matrix field), to update a block you would pass in the id of the matrix itself, the sortOrder of the blocks, and a list of blocks you want to update, like this:
![image](https://user-images.githubusercontent.com/57273245/123548333-38153400-d719-11eb-8b40-6904080207b0.png)

This will successfully update just that one block inside the matrix field, keeping the existing blocks in place.

For a nested matrix field, you would need to specify the outside matrix id and sortOrder (in addition to the inside id and sortOrder like with a normal matrix field), but the outer Super Table matrix id doesn't show as available to use for the mutation (there's no id under the parent 'blocks' node, only for the 'blocks' inside the nested 'blocks' node):
![image](https://user-images.githubusercontent.com/57273245/123548373-64c94b80-d719-11eb-9609-3f4a1ed81c79.png)

I'm not sure if this is a bug, or simply a limitation of the current GraphQL implementation that does not support the custom field types supplied by Super Table. In either case, we're looking for some way to be able to mutate a nested matrix field. Maybe in this case we need to provide the entire Super Table 'blocks' value, and specify each item as a new block, E.G. 'new:1', 'new:2' etc?

Steps to reproduce
Create a super table matrix that contains a normal matrix field
Open the graphiql UI interface and create a new mutation
Try to update a matrix field's block that is nested within the super table matrix block.
Additional info
Craft version: 3.6.17
PHP version: 7.4
Database driver & version:
Plugins & versions: Super Table 2.6.8

**Comment by humandevs** [comment]
FYI for anyone else who runs into this, according to Pixel & Tonic, this is probably because SuperTable doesn't yet support updating blocks by their ID! Here's the cross-posted bug:
https://github.com/craftcms/cms/issues/9092#issuecomment-874646560

**Comment by engram-design** [comment]
Should be added for the next version. To get the fix early, change your `verbb/super-table` requirement in `composer.json` to:

```
"require": {
  "verbb/super-table": "dev-craft-3 as 2.6.8",
  "...": "..."
}
```

Then run `composer update`.

Let me know if there's still issues though!

**Comment by humandevs** [comment]
Horray `id`s can be specified now, and GraphQL no longer throws errors!

Unfortunately, the mutation seems to do a whole lot of nothing still.  I'm assuming I'm just missing something in the mind-bending world of nested tables.

Here's a working mutation again with a single level matrix field mutation of a single block (no super table involved):
```mutation MyMutation($articleId: ID = "", $siteId: Int = 10, $blockSortOrder: [QueryArgument] = "", $textBlockId: ID = "", $textBlockParagraph: String = "") {
  save_articles_articleLongform_Entry(id: $articleId, siteId: $siteId, topicArticleContentBuilder: {sortOrder: $blockSortOrder, blocks: {textBlock: {paragraph: $textBlockParagraph, id: $textBlockId}}}) {
    id
    siteId
    topicArticleContentBuilder {
      ... on topicArticleContentBuilder_textBlock_BlockType {
        id
        paragraph
        typeHandle
      }
      ... on topicArticleContentBuilder_textPlusImageBlock_BlockType {
        id
        image {
          url
          title
        }
        sortOrder
        typeHandle
        paragraph
      }
    }
  }
}
```

And the query variables to make it work:
```{
 "articleId": "815",
 "siteId": 1,
 "blockSortOrder": ["816","818"],
 "textBlockId": "816",
 "textBlockParagraph": "Test Changed 2<ol><li><em>Ball-in-the-Box</em> at FLP</li><li><a href=\"http://craft-digiguide.test/glossary/6879\">\nReference Lock</a> indicator</li><li>Transmitter battery strength and pitch angle</li><li>Horizontal distance between transmitter and FLP</li><li><a href=\"http://craft-digiguide.test/glossary/1864\">\nPredicted depth</a> of transmitter</li></ol><p>The predicted depth is the depth the transmitter is calculated to be at when it reaches the FLP if it continues on its current path.</p>\n<p>In this example, if the drill head travels an additional 3'8\" (1.12 m) at -0.6% pitch, it will be directly below the locator at 2'8\" (0.81 m).</p>"
}
```

Here's the result of running that query (it successfully updates the paragraph field to include "Test Changed 2" at the beginning of the block:
![image](https://user-images.githubusercontent.com/57273245/124760253-677c2b80-dee5-11eb-9ef3-472513ac9672.png)


And here's what I would think would be needed to mutate a matrix block nested inside a Super Table matrix:
```mutation MyMutation($articleId: ID = "", $stepBuilderSortOrder: [QueryArgument] = "", $siteId: Int = 10, $stepBuilderId: ID = "", $blockSortOrder: [QueryArgument] = "", $textBlockId: ID = "", $textBlockParagraph: String = "") {
  save_articles_articleWithSteps_Entry(
    id: $articleId, 
    topicArticleStepBuilder: {
      sortOrder: $stepBuilderSortOrder, blocks: {
        topicArticleStepBuilder_0: {
          id: $stepBuilderId, step: {
            sortOrder: $blockSortOrder, blocks: {
              textBlock: {
                id: $textBlockId, paragraph: $textBlockParagraph
              }
            }
          }
        }
      }
  	}, 
    siteId: $siteId) {
    id
    userTitle
    siteId
    topicArticleStepBuilder {
      ... on topicArticleStepBuilder_BlockType {
        id
        sortOrder
        step {
          ... on step_textBlock_BlockType {
            id
            paragraph
            title
            sortOrder
            typeHandle
          }
          ... on step_calloutBlock_BlockType {
            id
            sortOrder
            typeHandle
            typeId
          }          
        }
      }
    }
  }
}
```

And the query variables to make it (in theory?) work:
```
{
  "articleId": "790",
  "siteId": 1,
  "stepBuilderSortOrder": ["791","794","796","798","800"],
  "stepBuilderId": "791",
  "blockSortOrder": ["861","793"],
  "textBlockId": "861",
  "textBlockParagraph": "Changed via GQL step"
}
```

However, no change seems to be made:
![image](https://user-images.githubusercontent.com/57273245/124761671-e3c33e80-dee6-11eb-8d13-0831e53c3c1e.png)

@andris-sevcenko seemed to imply in this issue that mutation of blocks via `id` was a newly created option. Is there some other way I'm missing where I can modify the nested matrix block without specifying the `id` of the outer matrix? This would be preferable, because `id`s of blocks seem to not be immutable (for example, when a version of the entry is reverted they seem to change).

**Comment by andris-sevcenko** [comment]
> Is there some other way I'm missing where I can modify the nested matrix block without specifying the id of the outer matrix? This would be preferable, because ids of blocks seem to not be immutable (for example, when a version of the entry is reverted they seem to change).

It's not possible currently, no, because there are no Matrix Block specific mutations - adding that would add some overhead regarding permission checks.

Also, wouldn't the id of the inner block change too, in this case, still forcing you to query Craft for the ID, anyway?

**Comment by humandevs** [comment]
So I bought a test Craft Pro license and spun up a clean test install of 3.6.17 and dev-craft-3 of Super Table, and the addition of the `id` field does magically fix mutations for Super Table "Table Layout" (column) fields, but they are still (as shown above) broken for Super Table "Matrix" fields.

Here's the example database with just two entry types, a Super Table "Table Layout" (column) field, and a similar Super Table "Matrix" field, each with two sample rows of data and the query to display them all:
![image](https://user-images.githubusercontent.com/57273245/124859763-4c510080-df65-11eb-9408-a749706be010.png)

And here's an example of a working mutation of that Super Table "Table Layout" (column) field:
![image](https://user-images.githubusercontent.com/57273245/124858381-c7fd7e00-df62-11eb-9637-447efbac0cb9.png)

And here's a similar example of a Super Table Matrix field where the update simply does nothing:
![image](https://user-images.githubusercontent.com/57273245/124859470-dba9e400-df64-11eb-8df1-2d2d90b58963.png)

Is there anything I can do to get more information for this? I would suspect this is due to the GQL thinking it should be mutating the entry itself, but it's actually supposed to be mutating a referenced (matrix) field, which it doesn't really understand should be updated. I guess my next sanity check would be rewriting this query as an Element query in Twig or PHP, to make sure it works there, too.

Here's the pertinent web.log log where the SQL is actually happening, but I'm not quite sure how to trace this through the plugin and craft to figure out which is dropping the ball:
```2021-07-07 20:57:14 [-][1][-][profile end][yii\db\Command::query] SELECT
    `kcu`.`CONSTRAINT_NAME` AS `constraint_name`,
    `kcu`.`COLUMN_NAME` AS `column_name`,
    `kcu`.`REFERENCED_TABLE_NAME` AS `referenced_table_name`,
    `kcu`.`REFERENCED_COLUMN_NAME` AS `referenced_column_name`,
    `rc`.`DELETE_RULE`,
    `rc`.`UPDATE_RULE`
FROM `information_schema`.`REFERENTIAL_CONSTRAINTS` AS `rc`
JOIN `information_schema`.`KEY_COLUMN_USAGE` AS `kcu` ON
    (
        `kcu`.`CONSTRAINT_CATALOG` = `rc`.`CONSTRAINT_CATALOG` OR
        (`kcu`.`CONSTRAINT_CATALOG` IS NULL AND `rc`.`CONSTRAINT_CATALOG` IS NULL)
    ) AND
    `kcu`.`CONSTRAINT_SCHEMA` = `rc`.`CONSTRAINT_SCHEMA` AND
    `kcu`.`CONSTRAINT_NAME` = `rc`.`CONSTRAINT_NAME`
WHERE `rc`.`CONSTRAINT_SCHEMA` = database() AND `kcu`.`TABLE_SCHEMA` = database()
AND `rc`.`TABLE_NAME` = 'matrixcontent_step' AND `kcu`.`TABLE_NAME` = 'matrixcontent_step'
2021-07-07 20:57:14 [-][1][-][info][yii\db\Command::execute] INSERT INTO `matrixcontent_step` (`elementId`, `siteId`, `field_textBlock_paragraph`, `dateCreated`, `dateUpdated`, `uid`) VALUES (48, 1, 'Test step-by-step step 1 text block 1', '2021-07-08 03:57:14', '2021-07-08 03:57:14', 'afd45b6c-69db-473b-b6f6-cc3deb368163')
2021-07-07 20:57:14 [-][1][-][profile begin][yii\db\Command::execute] INSERT INTO `matrixcontent_step` (`elementId`, `siteId`, `field_textBlock_paragraph`, `dateCreated`, `dateUpdated`, `uid`) VALUES (48, 1, 'Test step-by-step step 1 text block 1', '2021-07-08 03:57:14', '2021-07-08 03:57:14', 'afd45b6c-69db-473b-b6f6-cc3deb368163')
2021-07-07 20:57:14 [-][1][-][profile end][yii\db\Command::execute] INSERT INTO `matrixcontent_step` (`elementId`, `siteId`, `field_textBlock_paragraph`, `dateCreated`, `dateUpdated`, `uid`) VALUES (48, 1, 'Test step-by-step step 1 text block 1', '2021-07-08 03:57:14', '2021-07-08 03:57:14', 'afd45b6c-69db-473b-b6f6-cc3deb368163')
```

@andris-sevcenko I've sent the test database .sql, composer.lock and composer.json over to support@craftcms.com, just in case that helps.


For reference, here is the working mutation on a Super Table "Table Layout" (column) field:
```
mutation MyMutation($entryId: ID = "", $sortOrder: [QueryArgument] = "", $textBlock: String = "", $blockId: ID = "") {
  save_articles_articleTestSuperTable_Entry(testArticleSuperTableBuilder: {
    sortOrder: $sortOrder, blocks: {
      testArticleSuperTableBuilder_0: {
        id: $blockId, textBlock: $textBlock
      }
    }
  }, 
  id: $entryId) {
    id
    testArticleSuperTableBuilder {
      ... on testArticleSuperTableBuilder_BlockType {
        id
        textBlock
        typeId
        sortOrder
      }
    }
  }
}

Mutation variables:
{
  "entryId": "16",
  "sortOrder": [
    "17",
    "18"
  ],
  "blockId": "17",
  "textBlock": "Changed via GQL 2 - Test Super Table Table textBlock Text 1"
}
```

And the similar mutation for a Super Table Matrix field, which is not working:
```
mutation MyMutation($entryId: ID = "", $outsideBlockSortOrder: [QueryArgument] = "", $outsideBlockId: ID = "", $insideBlockSortOrder: [QueryArgument] = "", $insideBlockId: ID = "", $insideBlockParagraph: String = "") {
  save_articles_articleWithSteps_Entry(id: $entryId, topicArticleStepBuilder: {
    sortOrder: $outsideBlockSortOrder, blocks: {
      topicArticleStepBuilder_0: {
        id: $outsideBlockId, step: {
          sortOrder: $insideBlockSortOrder, blocks: {
            textBlock: {
              id: $insideBlockId, paragraph: $insideBlockParagraph
            }
          }
        }
      }
    }
  }
  ) {
    id
    topicArticleStepBuilder {
      ... on topicArticleStepBuilder_BlockType {
        id
        sortOrder
        step {
          ... on step_textBlock_BlockType {
            id
            paragraph
            sortOrder
            typeHandle
          }
        }
      }
    }
  }
}

Mutation Variables:
{
  "entryId": "13",
  "outsideBlockSortOrder": ["23","26"],
  "outsideBlockId": "13",
  "insideBlockSortOrder": ["24","25"],
  "insideBlockId": "24",
  "insideBlockParagraph": "Changed via GQL - Test Super Table Matrix textBlock Paragraph 1"
}
```

Thanks again for everyone's helpful input!

**Comment by andris-sevcenko** [comment]
This can be closed. The original issue is resolved and the new issue (nested matrix fields inside super table are impossible to update via mutation) should be tracked over hre: https://github.com/craftcms/cms/issues/9139
