### ISSUE TITLE
Instructions icon opens two tooltips

### ISSUE THREAD

**Issue by Joorren** [engram-design/SuperTable#418]
**Description**
When adding instructions to a field and clicking it in the entry editor, it will open two tooltip modals behind each other, making you have to close it twice.

https://user-images.githubusercontent.com/22602428/124250367-1e168f80-db25-11eb-9869-d09db1da98e0.mov

<img width="805" alt="Screenshot 2021-07-02 at 10 48 19" src="https://user-images.githubusercontent.com/22602428/124250370-1fe05300-db25-11eb-9973-12ee91631f7f.png">

**Steps to reproduce**
1. Add instructions to a field inside a super table block
2. Click on the instructions icon in the entry editor
3. Watch it open two modals

**Additional info**
- Plugin version: 2.6.8 (latest)
- Craft version: 3.6.17 (latest)
- Multi-site: Yes

**Additional context**

**Comment by engram-design** [comment]
Can't replicate this immediately. Are you mixing any other fields like Matrix or Neo?

**Comment by Joorren** [comment]
I cannot seem to replicate it either with just a field inside a Supertable field.
The video is recorded on a field inside a Supertable field inside a Matrix field.

**Comment by engram-design** [comment]
Can't seem to replicate this with any combination of Matrix/Super Table fields on Craft 3.7.19
