### ISSUE TITLE
Project-config apply: Setting unknown property: verbb\supertable\fields\SuperTableField::allowSelfRelations

### ISSUE THREAD

**Issue by cookie10codes** [engram-design/SuperTable#419]
**Description**
We opened a feature on our project and added a super field in, when we want to merge with develop and try to project-config apply, we get

```
- updating matrixBlockTypes.9e682a2f-b0d4-478b-8b06-549c218b8357.fields.35981b2e-d04e-4366-939a-c0673263711a.settings ... 
  - updating matrixBlockTypes.9e682a2f-b0d4-478b-8b06-549c218b8357 ... 
error: Setting unknown property: verbb\supertable\fields\SuperTableField::allowSelfRelations

    - updating meta.__names__.4fca56b3-7d94-48e0-be90-0bcfa39ed388 ... done
````

**Additional info**
- Plugin version: 2.6.8
- Craft version: Craft Pro 3.7.0-beta.5 --> we're working on the 3.7.0, but it's releasing in about one or two weeks
- Multi-site: No

**Comment by engram-design** [comment]
I would chalk this up to the 3.7.0-beta version, as it's not something I can replicate. But `allowSelfRelations` is only a property available to relations fields, so it sounds like this field has either been switched from an element select field to a Super Table, or something else has gone wrong...
