### ISSUE TITLE
'title' should be a reserved word that is not allowed when creating a SuperTable field

### ISSUE THREAD

**Issue by mildlygeeky** [engram-design/SuperTable#42]
Wasn't thinking, and used 'title' as the name for a SuperTable field and received the following:

Internal Server Error
CDbCommand failed to execute the SQL statement: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'title' in 'field list'

Sounds like it needs to be a reserved word?

**Comment by engram-design** [comment]
Might be a little late to respond, but did this happen to be for a Super Table field in a Matrix field? There are known issues with field validation in that case, but it works as expected on its own. Closing for now, but please let me know if you're still having issues.

**Comment by mildlygeeky** [comment]
Hey Josh,

Very likely was - good to know!
