### ISSUE TITLE
Collapsed fields in a super table re-open after save

### ISSUE THREAD

**Issue by jsunsawyer** [engram-design/SuperTable#420]
**Description**
We have a huge list of locations that populate a map in a matrix field (as a component that uses a super table field).

This list can grow to be very long, and it's desired that each item is collapsed within it to be easier to manage.

Since there's no way to quickly collapse all children, we really need the collapsed state to save for these to not take up too much space when editing content, or to re-order items.

If things could be updated so that the collapse behavior worked similar to matrix blocks (both in terms of saving the collapsed state and allowing multiple items to be collapsed at once – selecting all via **CMD + A** on a checkbox), it'd be greatly appreciated.

**Additional info**
- Plugin version: 2.6.8
- Craft version: ~~7.3.1~~ 3.7.1

**Comment by evanwarner** [comment]
Yep, I'm having this same problem and it didn't used to be this way. I'm guessing something in the Craft UI changed in ~3.7 which is causing this.

**Comment by engram-design** [comment]
I suppose this is when using the Matrix style layout, as opposed to Row and Table (which don't have collapse capabilities)? Can you confirm your field layout structure, as I can't quite tell if you're mixing Matrix, Super Table fields, and what layouts they are.

**Comment by jsunsawyer** [comment]
@engram-design My structure is as follows:

Matrix
- Super Table (Matrix layout)
-- Fields (3x plain text and 1x table)

Components (matrix) > Map (block) > Locations (super table field) > Location Fields

**Comment by evanwarner** [comment]
Yes, Matrix layout mode. This happens on both top-level ST fields and ones nested inside a Matrix block.

**Comment by engram-design** [comment]
Right - so I was testing this straight away, and the collapse behaviour (surprisingly) works for standalone Super Table (Matrix layout) fields, so thought it must be in combination with Matrix fields themselves. I'll have to investigate further, likely try to add proper collapse support.

**Comment by evanwarner** [comment]
Confirmed fixed in Super Table v2.7.0.
