### ISSUE TITLE
Super Table migrations Failed Craft 2 > Craft 3

### ISSUE THREAD

**Issue by Chrisedmo** [engram-design/SuperTable#428]
Im updating an old site from Craft 2 > Craft 3. I hit some hiccups along the way and realised that by disabling Supertable, it can get the site mostly migrated across. 

However when I enable supertable, I get the 'Database needs updating' page. And this fails, and when trying to run `./craft migrate/all` 

It fails on this step: `{{%supertablecontent_3_tabgroupcontent}} -> {{%stc_3_tabgroupcontent}}`

The message is: 
```     > rename table {{%supertablecontent_3_tabgroupcontent}} to {{%stc_3_tabgroupcontent}} ...Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'craft_stc_3_tabgroupcontent' already exists
The SQL being executed was: RENAME TABLE `craft_supertablecontent_3_tabgroupcontent` TO `craft_stc_3_tabgroupcontent` (... vendor/yiisoft/yii2/db/Schema.php:678) 
```

**Additional info**
- Plugin version: 2.6.8
- Craft version: 3.7.11
- Multi-site: No

**Comment by engram-design** [comment]
Is that the entire error? Are you running MySQL and if so, what version?

**Comment by Chrisedmo** [comment]
Heya - I'm running MariaDB and it's Ver 15.1.

There was a little more to the error. It was saying that the new columns existed already? But in the end, I worked out I also had a problem with Craft not being able to perform mysqldump, so I could not use your tool to update and resave the fields. 

In the end, I found this excellent plugin: https://packagist.org/packages/samhernandez/craft-db-paths and then re-imported my old SQL database from my craft 2 install and then ran the craft migrations again, then the supertable settings migration too and it all works now. 

Thanks.

**Comment by engram-design** [comment]
Wasn't aware of that plugin, but glad you managed to get it sorted! Be sure to run all the content table fixer and re-save field helpers. There's some annoying transitional things from Craft 2 > 3 that can only be done after a full update.
