### ISSUE TITLE
"Collapse ALL/Expand ALL" feature for super table

### ISSUE THREAD

**Issue by 919Studios** [engram-design/SuperTable#429]
FIRST OFF, Super Table is a badass tool - you have done a fantastic job developing it 👍🏻  I have a _small_ feature request below that would be **VERY much appreciated**.  Thank you and have a nice day! 😊

-Johnnie

-----
**WHAT ARE YOU TRYING TO DO?**

*Collapse* multiple suptertable row items at once.  Sometimes,. I need to *Expand* all the rows at once.

**EXAMPLE:**  Currently, If you had a super table set to matrix layout, then created 16 rows of content, you will need to click the gear icon, then click *Collapse* for **EVERY**… **SINGLE**… **ONE**. 🥵 ![aintNobodyGotTimeForThat](https://user-images.githubusercontent.com/20955174/132124598-1a57e9a4-cb93-46d7-96f3-ccfddb85537f.gif)

------
**WHAT'S YOUR PROPOSED SOLUTION?**

When we click the gear icon with a key modifier held, a **_COLLAPSE ALL SUPER TABLE ROW ITEMS_** event would be triggered. **AKA: holding option+click on the gear icon would collapse all currently expanded super table rows.**

------
**ADDITIONAL CONTEXT**

**Comment by seandelaney** [comment]
+1 for this.  I have a client who is constantly asking if they can toggle all rows at once.

**Comment by engram-design** [comment]
Super Table has now reached its end of life, and we'll be sticking with bug/security fixes from here on out. More in the [announcement](https://verbb.io/blog/so-long-super-table).
