### ISSUE TITLE
Content lost for other site groups on save

### ISSUE THREAD

**Issue by benoitblancquaert** [engram-design/SuperTable#436]
**Description**

I have a multi-language/site Craft CMS setup where the home page uses a field for the page hero. It's a static Super Table field that has the following propagation method: "Save blocks to other sites in the same site group". The fields in it are translated (translation method: "Translate for each site").

But unfortunately this doesn't work as it should. The Super Table field is completely cleared for all other site groups after editing the index section in a site group.

A video to clarify the issue: https://www.loom.com/share/098d0fc13a8843b8ae9d2d0d1f639bb3

Any chance this is a bug in one of the latest versions of Super Table?

**Steps to reproduce**

1. Edit Super Table field (name 'Hero', handle 'fieldHero') and save index entry in site group "A" in language/site "English". (0:00 - 0:25 in Loom video)
2. Check the content of the entry in site group "A", but of the language/site "Dutch".
3. Everything is working as it should. Both languages have their own content. (0:25 - 0:45)
4. Now edit the same entry but in a site/language of another group ("B, C, D, ...") and save it. (0:45 - 1:00)
5. Go back to one of the sites in site group "A" and you will see that the field is empty. (1:00 - 1:20)

**Additional info**

- Plugin version: 2.6.8
- Craft version: 3.7.21
- Multi-site: Yes

**Comment by jing-liu-anne** [comment]
I have the same problem but it doesn't happen every time.
