### ISSUE TITLE
Any guidance on the underlying grid?

### ISSUE THREAD

**Issue by vilav** [engram-design/SuperTable#44]
Hi There,

Is there  a way to alter the grid framework of SuperTable? Tring to integrate a flexbox based grid like (flexboxgrid.com).

Thanks
Vilav

**Comment by engram-design** [comment]
Not really sure I understand what you're after. If you're looking to build anything on the front end, you've got full control over how to present your data - just like any field in Craft. Other than that, there's no grid framework in use to alter.

**Comment by engram-design** [comment]
Closing for the moment - please respond with clarification on your issue and we'll revisit. Thanks!
