### ISSUE TITLE
Show excerpt of content collapsed row just like in matrix field

### ISSUE THREAD

**Issue by pixeldeluxe** [engram-design/SuperTable#447]
**What are you trying to do?**
When I double click on a table row block in Super Table, the row collapses. But then you cannot see what content is filled in behind this row.

**What's your proposed solution?**
Just like in the Craft Matrix field there's a solution where you see an excerpt of the content within the row/block. It's not very user friendly to see a lot of empty rows. Thanks in advance!

**Additional context**

![Screenshot 2022-01-06 at 14 18 46](https://user-images.githubusercontent.com/524849/148388831-47dca466-0f4e-414e-833d-2519d5a73aea.png)

**Comment by gregorterrill** [comment]
Super Table used to show the preview text here but it looks like a recent change in Craft broke it. Probably the same issue as #439 which has a proposed solution.

**Comment by engram-design** [comment]
Fixed in [3.0.3](https://github.com/verbb/super-table/releases/tag/3.0.3)
