### ISSUE TITLE
Supporting a custom field type?

### ISSUE THREAD

**Issue by cmalven** [engram-design/SuperTable#45]
We've created a field type plugin that we'd like to be able to use through SuperTable? We can add the field to Super Table, but when we save the entry, SuperTable doesn't retain the value of the custom field type (which is a `<select>` element). Is there anything we need to do to make our custom field type work with SuperTable?

`PropertyData_PropertyFieldType.php`

```php
<?php
namespace Craft;

class PropertyData_PropertyFieldType extends BaseFieldType
{
    public function getName() {
        return Craft::t('Property');
    }

    public function getInputHtml($name, $value) {
        return craft()->templates->render('propertydata/property/select', array(
            'name'  => $name,
            'value' => $value
        ));
    }
}
```

`select.html`

```php
<select name="{{ name }}">
    <option value="">None</option>
    {% for property in craft.propertyData.allProperties %}
        <option value="{{ property.slug }}">{{ property.name }}</option>
    {% endfor %}
</select>
```

**Comment by engram-design** [comment]
There isn't anything special you need to do to have a fieldtype support being in a Super Table field. I'll have a look at this and get back to you.

**Comment by cmalven** [comment]
Hey, don't worry about this it was our mistake.

**Comment by engram-design** [comment]
Ah! Thanks for letting me know :smiley:
