### ISSUE TITLE
Migration to craft-4 failure

### ISSUE THREAD

**Issue by zsavajji** [engram-design/SuperTable#454]
Hi, 
thank you for your VERY fast update to craft-4 ! 
I was hoping to try the beta but i get stuck after running the migrations with this error: 

`yii\base\UnknownPropertyException: Setting unknown property: verbb\supertable\fields\SuperTableField::placeholderKey in /Users/zsavajji/projects/MAMP/www/api-test/vendor/yiisoft/yii2/base/Component.php:209`

I am just going to report this to help you check out every possible upgrade path, i'm not actively migrating my project, since i need some plugins which are (As of today) not available, so i did not try to further debug this issue.

Thank you :)

**Steps to reproduce**
1. Update to craft-4
2. Run migrations
3. Enter admin

**Additional info**
- Plugin version: 3.0.0-beta.1
- Craft version: 4.0.0-beta.1
- Multi-site: Yes

**Additional context**

**Comment by engram-design** [comment]
Should be fixed in [3.0.0-beta.2](https://github.com/verbb/super-table/releases/tag/3.0.0-beta.2)
