### ISSUE TITLE
Craft 4 beta: Cannot install supertable plugin

### ISSUE THREAD

**Issue by Antimated** [engram-design/SuperTable#456]
**Description**
As the title describes: The "Super table" plugin cannot be installed and produces the following error on installation attempt:

```
Migration Error: An error occurred while executing the "verbb\supertable\migrations\Install migration: SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'ownerId' doesn't exist in table
The SQL being executed was: ALTER TABLE supertableblocks ADD INDEX idx_tpmspvuqxomsvwqlgecewgyyfdemqfvawbge (ownerId)
```

**Steps to reproduce**
1. Install the latest version of craft 3 and upgrade to craft 4.0.0-beta.1
2. Try and install Super table from the plugin store

**Additional info**
- Plugin version: Seems to be `3.0.0-beta.2` as the plugin store displays
- Craft version: 4.0.0-beta.1
- Multi-site: No

**Additional context**
Screenshot of plugin store (which displays 3.0.0-beta.2) plugin version:
![Screenshot 2022-03-15 at 14 11 47](https://user-images.githubusercontent.com/2869409/158385059-6833009f-9d2d-4723-a8a9-23d4d8cbbc07.png)

**Comment by engram-design** [comment]
Should be fixed in [3.0.0-beta.3](https://github.com/verbb/super-table/releases/tag/3.0.0-beta.3)
