### ISSUE TITLE
Newbie qst:: Updating attributes of a row of a supertable?

### ISSUE THREAD

**Issue by bhuvidya** [engram-design/SuperTable#46]
hi there. i am iterating over the rows of a supertable in a consolecommand handler. i may need to update some fields of a given row, and then save that data back to the db.

for example, `stockistList` is a supertable ina global set named `stockists`:

```
    public function actionUpdateLatLng()
    {   
        $stockistList = craft()->globals->getSetByHandle('stockists')->stockistList;
        foreach ($stockistList as $s) {
            if ($s->lat == 0 || $s->lng == 0) {
                echo("NO GEOCODE...\n");
            } else {
                echo("LEAVE ALONE...\n");
                continue;
            }   
        
            printf("    -> geocoding %s...", $s->address);
            if (!$geocode = craft()->googleMaps_geocode->geocode($s->address)) {
                echo("ERROR GEOCODING...\n");
                continue;
            }
    
            printf("using %f, %f\n", $geocode->lat, $geocode->lng);

            // so how do i update the lat/lng fields of this row of the table??????
            // what i have below is wrong, of course
            $s->setAttribute('lat', $geocode->lat);
            $s->setAttribute('lng', $geocode->lng);
            craft()->superTable->saveBlock($s);
        }
    }
```

i am a newbie to craft, and am still trying to master the model/record thing....

cheers!

**Comment by engram-design** [comment]
The main difference here is that you're wanting to update the content of a Super Table field, which is different than the model/record for the field (that would refer to the actual block definition).

If I'm reading what you're trying to do correctly, you have a `googleMaps_geocode` field in your `stockistList` Super Table field, which is in a Global set. What's more, you'll want to be saving the Global Sets content.

I think what you're after is something along the lines of:

```
$globalSet = craft()->globals->getSetByHandle('stockists');
$stockistListBlocks = $globalSet->stockistList;

foreach ($stockistListBlocks as $key => $block) {
    $blockTypeId = $block->type->id;

    $content['stockistList']['new'.$blockTypeId] = array(
        'type' => $blockTypeId,
        'enabled' => true,
        'fields' => array(
            'plainTextFieldHandle' => 'Some text'
        ),
    );

    $globalSet->setContentFromPost($content);
    craft()->globals->saveContent($globalSet);
}
```

Obviously thats a simplified solution, but its works for adding new rows with a plain text field. Let me know if thats off the mark!

**Comment by bhuvidya** [comment]
hi there @engram-design! thx so much for replying. yes you pretty much got what i am trying to do, except that i have `lat` and `lng` fields in the supertable, and `googleMaps_geocode` is the googlemaps service i wrote to frontend the googlemaps api for my app. it will just do things like geocode addreses etc.

i am still a newbie to craft, it's model/record abstractions, and the way to read and update data from plugin code (the online docs are a bit lacking in this area). i took your code and played with it. now correct me if i'm wrong, but as it stands that code actually sets the *entire content* of the `stockistList` supertable to whatever is in the `$content` array, basically overriding whatever content is currently in the table. the rows of the table seem to be created as new rows, with any fields not explicitly set in the `fields` array set to their default values. (and, if i use `['new'.$blockTypeId]` as the 2nd dimension index the content array ends up with only one row for stockistList as the blockTypeId is the same for each row of the table)

what i need to do is slightly different. i need to take existing rows of the table, and update the `lat` and `lng` fields to newly caluclated values. i managed to find something that works. the key was to use `$block->setContent()->setAttribute()` instead of `$block->setAttribute()`. and then follow that with `craft()->superTable->saveBlock($block)` to actually save the block.

```
    public function actionUpdateLatLng()
    {   
        $stockistList = craft()->globals->getSetByHandle('stockists')->stockistList;
        foreach ($stockistList as $block) {
            if ($block->lat == 0 || $block->lng == 0) {
                echo("NO GEOCODE...\n");
            } else {
                echo("LEAVE ALONE...\n");
                continue;
            }   

            printf("    -> geocoding %s...", $block->address);
            if (!$geocode = craft()->googleMaps_geocode->geocode($block->address)) {
                echo("ERROR GEOCODING...\n");
                continue;
            }

            printf("using %f, %f\n", $geocode->lat, $geocode->lng);

            $block->getContent()->setAttribute('lat', $geocode->lat);
            $block->getContent()->setAttribute('lng', $geocode->lng);
            craft()->superTable->saveBlock($block);
        }
    }
```

**Comment by engram-design** [comment]
Sure, glad you came to a solution. It was more something to get you started, as I don't know all the ins-and-outs of your situation :smiley: Ideally, you'd grab the fields data first, loop through each block content, building an array to save back to the global, changing the stuff as necessary. I'm also not sure if you need to handle adding new blocks, or just editing existing ones.

In any case, glad thats working for you at the moment!

**Comment by bhuvidya** [comment]
thx for all your help, here and on slack, and thx for writing supertable in the first place!

**Comment by engram-design** [comment]
No worries - sounds like you solved it on your own in the end! :smiley:

**Comment by bhuvidya** [comment]
yes and no. the moral support is v helpful! and you also showed me a postContent technique i didn't know about before which i will be needing to use in the near future when seeding another craft database with data from an old system. so double thanks!
