### ISSUE TITLE
Compatibility issue regarding ElementHelper::isOutdated()

### ISSUE THREAD

**Issue by ray-001** [engram-design/SuperTable#460]
**Description**
When running Craft CMS 3.7.0 to 3.7.11 in combination with verbb/super-table 2.7.0 or 2.7.1 an error may occur during saving.

In verbb/super-table/src/services/SuperTableService.php in mergeCanonicalChanges at line 1060.  The function ElementHelper::isOutdated is available since Craft CMS 3.7.12 (https://github.com/craftcms/cms/blob/56c6717a0f1bda48e6863b3e0ea0c03913857800/src/helpers/ElementHelper.php#L488-L505) 

**Steps to reproduce**
1. Have an entry with (multiple) superblocks and save it
2. Reopen entry, change some content in the blocks, add and remove one of the block and resave it.

**Additional info**
- Plugin version: 2.7.1
- Craft version: 3.7.8
- Multi-site: Yes

**Comment by engram-design** [comment]
Should be fixed in [2.7.2](https://github.com/verbb/super-table/releases/tag/2.7.2)
