### ISSUE TITLE
SuperTable in Matrix Field error when querying with GraphQL (Craft 4)

### ISSUE THREAD

**Issue by robinbeatty** [engram-design/SuperTable#462]
**Description**
Getting an error when querying a SuperTable field nested within a Matrix field with GraphQL:

Query:
```
query entryQuery($section: [String], $slug: [String]) {
  entry(section: $section, slug: $slug) {
    ... on packages_package_Entry {
      components {
        ... on components_component_BlockType {
          id
          componentFeatures {
            ... on componentFeatures_BlockType {
              id
            }
          }
        }
      }
    }
  }
}
```

Returns error:
```
verbb\supertable\gql\resolvers\elements\SuperTableBlock::prepareQuery(): Return value must be of type craft\elements\db\ElementQuery, Illuminate\Support\Collection returned
```

I know it's early days with the beta edition for Craft 4, but thought it would be useful to point it out – unless there's something I'm doing wrong?

**Additional info**
- Plugin version: 3.0.0-beta.3
- Craft version: 4.0.0.1
- Multi-site: No

**Comment by diluno** [comment]
I get this error even when it's not in a matrix field. Is there an update or maybe a workaround?

**Comment by engram-design** [comment]
Fixed for the next release. To get the fix early, change your `verbb/super-table` requirement in `composer.json` to:

```
"require": {
  "verbb/super-table": "dev-craft-4 as 3.0.0-beta.3",
  "...": "..."
}
```

Then run `composer update`.
