### ISSUE TITLE
Craft 4: Check Content Tables is broken

### ISSUE THREAD

**Issue by darylknight** [engram-design/SuperTable#466]
**Description**
Go to Settings > Super Table > Check Content Tables.

![image](https://user-images.githubusercontent.com/1250017/168279649-c9ea91a1-fea1-4517-8061-af896b90c26d.png)

**Additional info**
- Plugin version: 3.0.0-beta.3
- Craft version: 4.0.2
- Multi-site: No

**Comment by engram-design** [comment]
Fixed for the next release. To get the fix early, change your `verbb/super-table` requirement in `composer.json` to:

```
"require": {
  "verbb/super-table": "dev-craft-4 as 3.0.0-beta.3",
  "...": "..."
}
```

Then run `composer update`.

**Comment by darylknight** [comment]
Thank you :)
