### ISSUE TITLE
[Craft 4] Changes in sort order is reset when applying a draft

### ISSUE THREAD

**Issue by mmikkel** [engram-design/SuperTable#468]
**Description**

When applying a draft, the new order for existing SuperTable rows are reset to their prior values (i.e. the order the rows were in for the current entry). This seems to affect all SuperTable layout modes. Also seems to affect both standalone SuperTable fields, and ST fields embedded in Matrix.

**Steps to reproduce**
1. Add some rows to a SuperTable field, and save the entry (i.e. apply the provisional draft)
2. Re-order the rows, wait for the provisional draft to save, and then save the entry again (i.e. apply the provisional draft again)
3. Note that the new order for the rows has been reset

**Additional info**
- Plugin version: 3.0.0-beta.5
- Craft version: 4.0.4
- Multi-site: No

**Additional context**

**Comment by billmn** [comment]
Yep, same here

**Comment by engram-design** [comment]
Fixed via https://github.com/verbb/super-table/pull/477
