### ISSUE TITLE
Error when trying to add a SuperTable field to a Matrix in Craft 2.5

### ISSUE THREAD

**Issue by mmc501** [engram-design/SuperTable#47]
I get the following error:

[08-Dec-2015 09:03:39 UTC] PHP Parse error:  syntax error, unexpected '[' in /nfs/c11/h05/mnt/205970/domains/domainname.com/craft/plugins/supertable/services/SuperTableService.php on line 851

**Comment by engram-design** [comment]
Any chance you're on PHP 5.3? I'll have a look into this further if not, but that error does make me think its an issue with array dereferencing

**Comment by mmc501** [comment]
Ah - will check that will the Hosting now.



Sent from my iPhone

On 8 Dec 2015, at 09:21, Josh Crawford <notifications@github.com<mailto:notifications@github.com>> wrote:


Any chance you're on PHP 5.3? I'll have a look into this further if not, but that error does make me think its an issue with array dereferencing

-

**Comment by mmc501** [comment]
Yep that was the issue – updated and that has resolved the problem!
Thanks Josh!
