### ISSUE TITLE
Pre-populate fields

### ISSUE THREAD

**Issue by carolineboeykens** [engram-design/SuperTable#479]
Is there a possibility to pre-populate fields in a SuperTable block?
We would like to pre-fill the author and date field so that it is the current user and the current date (but you still need the option to change it)

![Screenshot 2022-06-13 at 12 51 17](https://user-images.githubusercontent.com/42932673/173338556-58c1499f-99f1-4d43-8358-1dea97212781.png)

I tried to write it in JS but failed. Do you have a suggestion of can you make it possible somehow?

**Comment by murtaugh** [comment]
Here to thumbs up this suggestion — default values would be amazing.

**Comment by engram-design** [comment]
There's no way to set default values for fields, but that's an interesting idea. Typically default values would be set on the field itself, but we'd have to do some extra work to have them set at the Super Table field level.

**Comment by engram-design** [comment]
Super Table has now reached its end of life, and we'll be sticking with bug/security fixes from here on out. More in the [announcement](https://verbb.io/blog/so-long-super-table).
