### ISSUE TITLE
[4.x]: SuperTableService::saveField $query can be instance of Collection

### ISSUE THREAD

**Issue by Anubarak** [engram-design/SuperTable#481]
### Describe the bug

Talking about this one https://github.com/verbb/super-table/blob/craft-3/src/services/SuperTableService.php#L756
It's basically the same as https://github.com/craftcms/cms/issues/11670

`$query` can be instance of a `Collection` instead of just a Query now. It would be awesome if you could apply the same fix as Brandon did [here](https://github.com/craftcms/cms/commit/49d462035695369e4313da9d038553b340641cb5)

### Steps to reproduce

1.  Eager Load an Element with a Supertable field
2.  see your Code breaks because `getFieldValue` can now return an instance of `Collection` instead of a `Query`

### Craft CMS version

4.x

### Plugin version

3.0.0-beta.6

### Multi-site?

no

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/super-table/releases/tag/3.0.0)
