### ISSUE TITLE
Craft 4:  Field Settings not saved

### ISSUE THREAD

**Issue by mark-chief** [engram-design/SuperTable#483]
### Describe the bug

My example is in a Matrix > Supertable > Matrix > Redactor scenario.

The field has already been saved, but making further edits to the redactor config e.g. adding a field label, or toggling HTML purify checkbox, does not save. Upon return, it has not saved.

Craft 4.2.4

### Steps to reproduce

1. Create Matrix > Supertable > Matrix > redactor set up
2. Save
3. Got back and make changes to the redactor field i.e HTML purify checkbox, or add a label
4. Save
5. Go back and settings are not saved
6. 

### Craft CMS version

4.2.4

### Plugin version

3.0.1

### Multi-site?

No

### Additional context
This is not limited to a redactor field settings, no further settings are saved. E.g. if i try and create another field within, it is not saved.

_No response_

**Comment by DenyEs** [comment]
I have the same issue on Supertable 3.0.1 and Craft 4.2.4

I have an existing Supertable block with a matrix field inside, when I add a new block after an update and save it, then return back to check on it, it's gone, like I've never created it.

Craft CMS Version:
4.2.4

Plugin Version
3.0.1

Multi-site?
Yes

**Comment by mark-chief** [comment]
@DenyEs FYI I also raised an issue with craft as I wasn't sure who it would fall to. Their support are looking in to it as they  are able replicate the issue on their end too. I believe Brandon is busy working on Dot All conf. so may be a delay!

RE: https://github.com/craftcms/cms/issues/11938

**Comment by DenyEs** [comment]
@mark-chief Cheers for letting me know :) I hold off from updating Craft as well as Supertable unfortunately, at least for now until this is fixed.

**Comment by DenyEs** [comment]
I have just done some more tests and Craft 4.2.4 with Supertable 3.0.0 works fine. The issue starts happening after an update to Supertable 3.0.1, after that update, no new fields are being saved if you add a new matrix block inside of a supertable block, adding a field in a supertable itself seems to be saving fine

**Comment by alterator** [comment]
> Craft 4.2.4 with Supertable 3.0.0 works fine.

+1 to this. I was pulling my hair getting to the bottom of this. Downgraded to Supertable 3.0.0 leaving Craft at 4.2.5 but that wasn't enough on its own. Needed to downgrade both.

**Comment by stuible** [comment]
Currently running into this on Craft 4.2.5.1 and Supertable 3.0.1

**Comment by DTesch-Level-R** [comment]
Currently also running into this on Craft 4.2.5.1 and Supertable 3.0.1.

**Comment by padmedia** [comment]
+1 also experiencing this issue Matrix > Supertable > Matrix > (when adding more than one Block Type)

Supertable 3.0.1
Craft: 4.2.5.2

**Comment by engram-design** [comment]
Fixed in [3.0.2](https://github.com/verbb/super-table/releases/tag/3.0.2)

**Comment by DenyEs** [comment]
Thanks Josh! 😊

**Comment by remoflury** [comment]
I observed the problem, but as @engram-design said, it was fixed in supertable 3.0.2. and it worked for me.

but now the problem reoccured. I'm using craft 4.2.7 and supertable 3.02. 
Anyone else experiencing this issue with those versions?
