### ISSUE TITLE
Value of type bool is not callable

### ISSUE THREAD

**Issue by iamtompickering** [engram-design/SuperTable#491]
### Describe the bug

I've just updated Craft to 4.3.1 and also Super Table to 3.0.4. Since updating, I'm hitting the following error when trying to save entries.

![CleanShot 2022-11-01 at 09 50 03](https://user-images.githubusercontent.com/6592882/199206748-f4d79f6c-4a76-4f01-89ce-32d8e78f5371.png)

### Steps to reproduce

1. Update to Craft 4.3.1 and Super Table 3.0.4
2. Save an entry with a Super Table included as a field

### Craft CMS version

4.3.1

### Plugin version

3.0.4

### Multi-site?

No

**Comment by garycrane** [comment]
Same here. I've reverted to 3.0.3 for the time being.

**Comment by engram-design** [comment]
Should be fixed in [3.0.5](https://github.com/verbb/super-table/releases/tag/3.0.5)

**Comment by garycrane** [comment]
Thanks Josh. That's working for me now.
