### ISSUE TITLE
Craft v4 migration issue on Postgres

### ISSUE THREAD

**Issue by davola** [engram-design/SuperTable#495]
### Describe the bug

When migrating from craft 3 to craft 4 with postgres database, the migration fails.

The migration `m220308_100000_owners_table` when moving `supertableblocks` to newer `supertableblocks_owners` tables only works on  MYSQL and fails on POSTGRES.

You have already merged a fix for that in this [commit](https://github.com/verbb/super-table/commit/837e7ac8cb4ef69ede3aa2aff8891bcbc41668f1) BUT you forgot to add a new release TAG in order for us to be able to get the feature.

So far I can use this fix by setting `dev-craft-4` as the version, but it should be great to move this to a new `3.0.6` version instead.

### Steps to reproduce

1. migrate from craft 3 to craft 4 on a postgres DB

### Craft CMS version

4

### Plugin version

3.0.5

### Multi-site?

yes

**Comment by davola** [comment]
Hey @engram-design , can you please release v 3.0.6 with the latest [PR merge](https://github.com/verbb/super-table/commit/837e7ac8cb4ef69ede3aa2aff8891bcbc41668f1)  you did last week?
I will really appreciated. 🙏

**Comment by devinpitcher** [comment]
Yes, please! We are currently locked onto that commit in `composer.json` but would love to be able to move back to a proper version instead.

**Comment by engram-design** [comment]
Fixed in [3.0.6](https://github.com/verbb/super-table/releases/tag/3.0.6)
