### ISSUE TITLE
Return type error in `getRelatedElementsQuery()`

### ISSUE THREAD

**Issue by ReedBe** [engram-design/SuperTable#497]
### Describe the bug

The `getRelatedElementsQuery()` method in the `Service` class has a return type of `SuperTableBlockQuery`, but the `elementType` parameter allows you to specify a different element type, such as `craft\elements\Entry`. However, if you specify a different element type, the method will still return a `SuperTableBlockQuery` object, which can cause a return type error when the method is called.

So the example provided in the documentation do not work 
https://verbb.io/craft-plugins/super-table/docs/template-guides/available-variables#craft-superTable-getRelatedElements

To fix this issue, I think the return type of the `getRelatedElementsQuery()` method must be changed to `ElementQueryInterface`, which will allow the method to return a query object for any type specified by the `elementType` parameter.

Same error when using `SuperTableVariable` method `getRelatedElements`

### Steps to reproduce

1. Call the `getRelatedElementsQuery()` function with a `elementType` parameter that specifies a different element type, such as `craft\elements\Entry`.
```
{% set elements = craft.superTable.getRelatedElements({
  relatedTo: {
      targetElement: entry,
      field: 'superTableFieldHandle.columnHandle',
  },
  elementType: 'craft\\elements\\Entry',
}).all() %}
```
2. Observe return type error.

### Craft CMS version

4.3.4

### Plugin version

3.0.6

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed in [3.0.7](https://github.com/verbb/super-table/releases/tag/3.0.7)
