### ISSUE TITLE
linkit config locale dropdowns fail

### ISSUE THREAD

**Issue by marionnewlevant** [engram-design/SuperTable#50]
I have a site with multiple locales. Created a linkit field in a supertable, and when I configure the field (gear icon), the *Which locale do you want to select entry in?* and *Which locale do you want to select category in?* dropdowns appear as raw html
![screen shot 2016-01-15 at 10 34 46 am](https://cloud.githubusercontent.com/assets/695477/12361546/a41bb9d4-bb73-11e5-9ef9-9e3c38a65cf4.png)

**Comment by engram-design** [comment]
I don't believe this is an issue with Super Table, as my testing has found this to be an issue with a standalone Linkit field. Please refer to [this pull request](https://github.com/fruitstudios/LinkIt/pull/23) in the Linkit repository, and encourage the author to incorporate it!
