### ISSUE TITLE
Nested supertable title bars overlapping in matrix field

### ISSUE THREAD

**Issue by knufri** [engram-design/SuperTable#508]
### Describe the bug

Hello,

when using a super-table field with matrix layout within a matrix field the title bars overlapping and don't respect the margins. Here is a screenshot of the layout bug:

<img width="1302" alt="Bildschirm­foto 2023-03-06 um 16 07 24" src="https://user-images.githubusercontent.com/2785206/223149506-52dd6b81-e147-4a51-be9a-c6c693dc3c96.png">

Seems like it is caused by a dynamic inline style. I'm not sure if it's the plugin or possibly a craft bug.
Here is an example of an element with the height set in absolute pixel:
```html
<div class="superTableMatrix matrixblock collapsed" data-id="8409" data-type="partner" style="height: 16px;">
```

### Steps to reproduce

1. Add a super-table field with matrix layout within a matrix field
2. Add some items, collapse them and then you see the missing space between the items

### Craft CMS version

4.3.10

### Plugin version

3.0.7

### Multi-site?

No

**Comment by evanwarner** [comment]
Hah, this 👆 is me accidentally creating a PR to my own repo last week then wondering why I couldn't follow up on it here. 🤦‍♂️
