### ISSUE TITLE
Reserved word for dropdown handle

### ISSUE THREAD

**Issue by bkmorse** [engram-design/SuperTable#51]
I created a dropdown field as one of my supertable fields and used the word "type" as the handle of that dropdown handle within the supertable. 

It would be helpful to reject that name because it is a reserved word.

**Comment by engram-design** [comment]
I'm not 100% sure, but just from my own testing with different fields, I don't believe `type` is a reserved handle? For instance, I've created a Plain Text field with that handle, a Table field with one of the columns called type, and along with a Super Table and Matrix field.

Validation is in place to ensure reserved works are respected - much the same way Matrix works.

**Comment by engram-design** [comment]
Closing as I don't believe `type` is a reserved handle (see http://craftcms.stackexchange.com/questions/13936/list-of-reserved-field-handles).

**Comment by kmgdevelopment** [comment]
`type` is indeed a reserved handle. I got the same error when trying to create a Super Table field with the handle of `type`. Changing the handle to `theType` fixed the error.

**Comment by engram-design** [comment]
@kgrote You're correct - note this was from quite some time ago, where I didn't know any better! `type` is definitely a non-allowed handle for Super Table fields.

**Comment by kmgdevelopment** [comment]
I would recommend figuring out how to display a more useful error in that instance. As it is you get a Yii error with the message 

> Unable to locate message source for category '"{handle}" is a reserved word.'.

Which is confusing because it doesn't tell you specifically which handle is the problem. Also the bit about "message source for category" is confusing.

**Comment by engram-design** [comment]
@kgrote Just fixed that yesterday in [2.0.11](https://github.com/verbb/super-table/releases/tag/2.0.11)!

**Comment by kmgdevelopment** [comment]
Nice! 👏🏻
