### ISSUE TITLE
Custom order od categories in SUper table's category field

### ISSUE THREAD

**Issue by lexislav** [engram-design/SuperTable#511]
### What are you trying to do?

Set order of selected categories by draging them as in other Craft's fields. SUper table's category filed seems not have this feature.

### What's your proposed solution?

Manual ordering of categories selected in the filed would be hepfull.

**Comment by engram-design** [comment]
Super Table has now reached its end of life, and we'll be sticking with bug/security fixes from here on out. More in the [announcement](https://verbb.io/blog/so-long-super-table).
