### ISSUE TITLE
Upgrading to 3.0.8 causes JS error that breaks control panel

### ISSUE THREAD

**Issue by aelvan** [engram-design/SuperTable#514]
### Describe the bug

After upgrading to Super Table 3.0.8, a JS error occurs that makes the control panel unusable. It seems like the JS that super table outputs, breaks at some point, and the remanining JS is output to the DOM, see screenshots:

![CleanShot 2023-03-28 at 12 12 35](https://user-images.githubusercontent.com/2675644/228204940-34580b78-3cb4-4f83-b622-809aefa0c49d.png)

![CleanShot 2023-03-28 at 12 15 22](https://user-images.githubusercontent.com/2675644/228205087-166ad3aa-5403-407b-9d85-bc5695cefa66.png)

### Steps to reproduce

1. Upgrade from 3.0.7.
2. Open an entry edit screen with super table inside a matrix.

### Craft CMS version

4.3.11

### Plugin version

3.0.8

### Multi-site?

No

### Additional context

The super table field is inside a matrix content builder. Let me know if you can't reproduce and I'll try to make a reduced example case.

**Comment by mikewink** [comment]
I am experiencing the same behavior in a multisite installation. Running on Craft CMS 4.3.10 and Super Table 3.0.8. My Super Table field is in a Matrix field.

**Comment by engram-design** [comment]
Looks to be due to https://github.com/verbb/super-table/commit/a382ff206531b2613ff3e3030534fbc103f26771, which to be fair I didn't update the requirements to [Craft 4.4.4](https://github.com/craftcms/cms/blob/develop/CHANGELOG.md#444---2023-03-20)

Should be fixed in [3.0.8.1](https://github.com/verbb/super-table/releases/tag/3.0.8.1)

**Comment by aelvan** [comment]
Myeah, that change in 4.4.4 and 3.8.4 look... dangerous.
