### ISSUE TITLE
Cannot add Matrix field inside SuperTable

### ISSUE THREAD

**Issue by pimago** [engram-design/SuperTable#52]
I think have somekind of bug. I cannot add any Matrix fields inside SuperTable. Other fieldtypes work fine. But if want to add an field inside a Matrix I get a 500 error when I save. I uses to work, but at somepoint it stopped. Is there a limit of Matrix fields inside SuperTable?

SuperTable is 0.4.2 and Craft 2.5.2

**Comment by pimago** [comment]
A tested a bit more. Same Row, same Matrix, different Block, different Fieldtype seems to work. But now my last two or three SuperTable Rows are deleted. Seems to be random if two or three.

If three rows are deleted or if I delete a third one manually, I can add that field mentioned in my first post.

**Comment by gabrielmoreira** [comment]
@pimago 
I resolved a similar problem increasing `max_input_vars` and `post_max_size` into php.ini:
http://craftcms.stackexchange.com/a/2777

**Comment by engram-design** [comment]
@pimago Sorry for not getting back to you - I would agree with @gabrielmoreira - can you please see if that rectifies the issue?

**Comment by pimago** [comment]
Yes that solved my problem. Thank you!
