### ISSUE TITLE
Dynamic usage of maxRows and minRows

### ISSUE THREAD

**Issue by alexander-bozung** [engram-design/SuperTable#527]
### What are you trying to do?

I try to build reusable fields by using super-table blocks for example in oder to build "_actions_". An action for example has a field _link_ (linkit), a _text_, a _variant_ (button or textlink or something like that) etc. ... I use this super-table block "_action_" in different parent modules (for example with neo). 
Now I have modules that allow only one action to be added and others that allow two or more. To achieve this, I have tried to modify the "maxRows" field of my super-table block "_actions_" on a per module basis. 

### What's your proposed solution?

What I have tried is to use a AssetBunde (https://craftcms.com/docs/4.x/extend/asset-bundles.html) with a JavaScript that would then update the "maxRows" property - that is not working.

Is there a way to use maxRows and minRows dynamically depending on the parent element the super-table block element is used in?

**Comment by engram-design** [comment]
Super Table has now reached its end of life, and we'll be sticking with bug/security fixes from here on out. More in the [announcement](https://verbb.io/blog/so-long-super-table).
