### ISSUE TITLE
Unable to Query Blocks by method in documentation

### ISSUE THREAD

**Issue by ericanderson-artisandm** [engram-design/SuperTable#529]
### Describe the bug

I am trying to query a Super Table field on a pre-existing entry. I can see in the backend, the entry has the Super Table field and it is populated with content as expected. Trying to query  for the blocks per the [documentation](https://verbb.io/craft-plugins/super-table/docs/template-guides/block-querying)  like
```
{% set e = craft.entries.slug('il-tempio-del-suono').one() %}

{% set f = craft.app.fields.getFieldByHandle('authorizedHeritageDealerInfo') %}

{% set blocks = craft.superTable.blocks({ ownerId: e.id, fieldId: f.id }).all() %}
<pre>
    {{ dump(blocks|length) }}
</pre>
{% for block in blocks %}
	{% for field in block.getFieldLayout().getFields() %}
		{% set value = block.getFieldValue(field.handle) %}

		{{ dump(value) }}
	{% endfor %}
```
gives the following error 
`Calling unknown method: craft\models\FieldLayout::getFields()`

### Steps to reproduce

With super table installed,  try a block query  per https://verbb.io/craft-plugins/super-table/docs/template-guides/block-querying

### Craft CMS version

Craft CMS 4.3.9

### Plugin version

3.0.7

**Comment by alexroper** [comment]
I think the `getFields()` method has been removed in Craft 4. I used the [`getCustomFields()`](https://docs.craftcms.com/api/v4/craft-models-fieldlayout.html#method-getcustomfields) method instead.

This worked for me:

```
{% for block in blocks %}
    {% for field in block.getFieldLayout().getCustomFields() %}
        {% set value = block.getFieldValue(field.handle) %}

        {{ dump(value) }}
    {% endfor %}
{% endfor %}
```

**Comment by engram-design** [comment]
That's correct, the docs are simply out of date. Updated.
