### ISSUE TITLE
SuperTable and drafts

### ISSUE THREAD

**Issue by JoshAinsworth** [engram-design/SuperTable#53]
I have a simple supertable containing a few text fields/switches which wont save properly on a draft, but is working perfectly fine on a live entry.

When saving a draft, any new rows added to the supertable override existing rows (starting at the first), and the value of the switches are not saved.

**Comment by engram-design** [comment]
Thanks for reporting this, this is now fixed in the [0.4.3 release](https://github.com/engram-design/SuperTable/releases/tag/0.4.3).
