### ISSUE TITLE
Super Table within Matrix field triggers large number of jobs to update search index

### ISSUE THREAD

**Issue by baileydoestech** [engram-design/SuperTable#532]
### Describe the bug

We have a super table nested inside a matrix block as below:

![image](https://github.com/verbb/super-table/assets/3185073/478f9d06-9591-4b1f-88b4-d09e26fc538c)

When an entry containing this field is saved (any change, not just to the field in question) we see a large number of jobs triggered to Update search indexes and prune extra revisions. None of the fields have 'Use the field's values as search keywords' enabled.

![image](https://github.com/verbb/super-table/assets/3185073/eaf55033-016b-4a26-a3c9-0c2833b0f5dd)

This seems orders of magnitude larger compared to saving without the field, the jobs can sometimes just hang and do place quite a burden on the CPU/Memory of our site despite the change not usual touching this field. If this is expected then is there a way to disable it?

We have tried resaving the super table fields without any luck

### Steps to reproduce

1. Create a matrix block with a nested Super Table Field
2. Populate the field for a given entry
3. Save the entry without making any changes to the matrix block
4. See a large number of jobs triggered

### Craft CMS version

4.5.2

### Plugin version

3.0.9

### Multi-site?

Yes

**Comment by baileydoestech** [comment]
Looks similar to this request: https://github.com/verbb/super-table/issues/525

**Comment by 919Studios** [comment]
Hello @baileydoestech - I've had the _same exact_ issue - did you find a way get those large numbers of jobs to stop bogging down the cms?


There is an [async tool](https://github.com/ostark/craft-async-queue) that might be helpful to you that partly solves things… Im trying to find a way to not even need that in the first place though.

**Comment by baileydoestech** [comment]
I believe this got noticeably better for us in a recent Craft release but as super table is now deprecated we aren't going to spend much more time on looking into this. Async queue also helped with us

**Comment by 919Studios** [comment]
Just read the verbb news article… glad pixel and tonic added native way to do this now 👍🏻
Time to get movin' with Craft 5 😄
