### ISSUE TITLE
Super Table field not displaying in a entries edit screen

### ISSUE THREAD

**Issue by BenHall-1dr** [engram-design/SuperTable#538]
### Describe the bug

Whenever a static Super Table field is empty it is not displaying in a entries edit screen. Have rolled back to v3.0.9 and issue doesn't occur.

### Steps to reproduce

1. Add static Super Table field and attach to entry type
2. Attempt to create new entry
3. Should see super table field doesn't appear

### Craft CMS version

4.5.6.1

### Plugin version

3.0.10

**Comment by HAWilliams01** [comment]
I am experiencing the same issue on fields that are using the Static field toggle. I set the max and min rows to 1 so my site has the same functionality until this is resolved.

Craft CMS version
4.5.6.1

Plugin version
3.0.10

**Comment by nstcactus** [comment]
I am experiencing the same issue, with static fields too.

Existing blocks are rendered and editable but I cannot add new ones. Additionally, my Super table fields are nested in Neo blocks and if I clone an existing Neo block, the nested Super table blocks are editable.

**Comment by engram-design** [comment]
Looks like this was introduced in https://github.com/verbb/super-table/pull/528 and should have been checked more carefully.

Fixed in [3.0.11](https://github.com/verbb/super-table/releases/tag/3.0.11)
