### ISSUE TITLE
Craft 4 upgrade - Issue using Super Table field within matrix field

### ISSUE THREAD

**Issue by kate-stretton** [engram-design/SuperTable#539]
### Question

Hello,

I'm experiencing an issue with Super Table that I'm hoping you can please help with.

I've upgraded a site from Craft 3.9.4 to Craft 4.5.6.1. As part of this, I've also updated the Super Table plugin from 2.7.5.1 to 3.0.11. I'm now seeing the following error when I try to view an entry with a block that uses a Super Table field:

![image](https://github.com/verbb/super-table/assets/81283807/2ac4eeb5-c6f3-44af-bd0a-8d8305e9842d)

The Super Table field has always been within a Matrix field in the block:

![image](https://github.com/verbb/super-table/assets/81283807/1b251def-ed79-47d5-96a8-bdd4c2be35bf)

Here's a screenshot of the system report for this site:

![image](https://github.com/verbb/super-table/assets/81283807/c5a5b6a6-3fbd-46e4-8476-1cb0e16ecb29)

Do you have any suggestions regarding how I could resolve this?

Thanks,
Kate

**Comment by engram-design** [comment]
Sorry about that, should be fixed in [3.0.12](https://github.com/verbb/super-table/releases/tag/3.0.12)

**Comment by kate-stretton** [comment]
Thanks very much for such a quick fix :)
