### ISSUE TITLE
Importing EE Matrix Data Into Super Table

### ISSUE THREAD

**Issue by kgrote** [engram-design/SuperTable#54]
I was hoping you could point me in the right direction for migrating data from an EE Matrix field into a Super Table field. I have a Craft plugin going that 1. Creates a new Craft `EntryModel()` object, 2. Uses the `setContent()` method to add field content, and 3. uses the Craft `saveEntry()` method to publish the entry:

```
$newEntry = new EntryModel();

$newEntry->getContent()->title = 'My Title';
$newEntry->sectionId = 4;
$newEntry->authorId = 1;
// ...etc...

$newEntry->setContent(array(
  'body' => 'Lorem ipsum dolor...',
  'tagline' => 'Oh wow a new entry!'
));

craft()->entries->saveEntry($newEntry);
```

However Super Table is a special type of field, so it can't just be added to the Entry object the same way plain text fields can. I see that Super Table uses its own block model, but I'm not sure how to 1. initialize it, 2. add data to it, and 3. incorporate it into the `EntryModel()` object and/or the `saveEntry()` method. Can you get me going with some starter code?

**Comment by engram-design** [comment]
Hey there - have a look at the Wiki article [Programatically saving a Super Table field with content](https://github.com/engram-design/SuperTable/wiki/Programatically-saving-a-Super-Table-field-with-content), which should help you out! Let me know if you have any issues.

**Comment by kgrote** [comment]
Exactly what I needed, thanks.
