### ISSUE TITLE
Getting unknown property: verbb\supertable\fields\SuperTableField::minBlocks

### ISSUE THREAD

**Issue by adrianjean** [engram-design/SuperTable#540]
### Describe the bug

Supertable throws an error in the CP:

`Getting unknown property: verbb\supertable\fields\SuperTableField::minBlocks`

... when there is a "Min Rows" set in the field Supertable configuration. 

### Steps to reproduce

1. In the field configuration for a SuperTable field, set a value for `Min Rows`
2. Edit an entry that has that field and note the error.

### Craft CMS version

4.5.6.1

### Plugin version

3.0.11

### Multi-site?

Yes

**Comment by engram-design** [comment]
Already fixed in https://github.com/verbb/super-table/releases/tag/3.0.12
