### ISSUE TITLE
[FR] [Craft 5] Use the "Inline-editable blocks" view mode for migrated ST fields

### ISSUE THREAD

**Issue by mmikkel** [engram-design/SuperTable#553]
### What are you trying to do?

As of 3.0.0-beta.1, migrated SuperTable fields use the default "Cards" Matrix view mode. IMO, it'd be more apt to use the "As inline-editable blocks" view mode, since that more closely aligns with how SuperTable appears in versions prior and is (I assume) likely the one that most people will want to use with the migrated fields going forward.

Of course the view mode can be manually changed post-migration, but kind of a chore :)

### What's your proposed solution?

Migrated SuperTable fields should use the "As inline-editable blocks" view mode setting, instead of the default "Cards" Matrix view mode.

**Comment by engram-design** [comment]
A good point, I think that makes sense as well

**Comment by engram-design** [comment]
Should be updated in [4.0.0](https://github.com/verbb/super-table/releases/tag/4.0.0)
