### ISSUE TITLE
[5.x] In Craft 5 will Super Table's old layouts return?

### ISSUE THREAD

**Issue by bryce-pod1** [engram-design/SuperTable#556]
### Question

Is Super Table only a Matrix clone for migration purposes now, or will the old layout options return?

The static and table views were my go to for self contained settings panels, and table builders that required custom fields.
_I know Crafts table field will allow "relational column types" soon, but that's probably not an adequate replacement._

The Super Table docs still mention the layouts and I haven't been able to find solid reference to this going away, so I'm hoping it's just a mater of time?

**Comment by engram-design** [comment]
No [further development](https://verbb.io/blog/craft-5-plugin-update#super-table) will be done on Super Table for Craft 5, and yes - it's just a Matrix clone for migration. You will be able to safely remove the plugin once migrated to Craft 5.

I know that we were all very fond of the layouts Super Table provided (myself included), but if we want that back, I think we collectively need to push Craft's Matrix field to support those layouts. I'd much rather see these in core, and with Matrix-in-Matrix out of the way, and a few new UI options for Matrix, I see no reason Craft couldn't implement a similar more streamlined UI.

The docs will be updated once out of beta to explain the situation.

**Comment by bryce-pod1** [comment]
Thanks for the quick reply. 

It's sad, but understandable.
Hopefully we get these things in core sooner rather than later.

The matrix changes and being able to reuse fields are nice, but I think we're still missing a "compact self-contained multi settings panel" option in Craft. I guess they're leaning into the popover menu and nested entries instead.

**Comment by engram-design** [comment]
I do agree that something like that is still needed! I’m not sure if there’s a feature request open about it with Craft, but I’ll be sure to create one. I think a lot of people would be in the same boat.

**Comment by engram-design** [comment]
FYI on our official [announcement](https://verbb.io/blog/so-long-super-table).
