### ISSUE TITLE
Cannot add more than one option for Dropdown

### ISSUE THREAD

**Issue by richhayler** [engram-design/SuperTable#56]
I am using a super table within a matrix and have set one of the columns as a dropdown field. In the modal window for the dropdown field options I cannot add more than one dropdown option. Clicking the "add an option" doesn't create a new option as would be expected.

**Comment by edolyne** [comment]
I'm also experiencing this issue.

**Comment by johanhatlehols** [comment]
I do as well! Same goes for similar fields, like radio and multiple choice.

**Comment by engram-design** [comment]
Thanks for letting me know about this - a fix will be going out later today with the next release.

**Comment by engram-design** [comment]
Refer to the [0.4.3 release](https://github.com/engram-design/SuperTable/releases/tag/0.4.3) which has fixed this.
