### ISSUE TITLE
Rows not displayed for Static Table

### ISSUE THREAD

**Issue by richhayler** [engram-design/SuperTable#57]
Have just updated to v0.4.3 and now when adding a new entry the row is not displayed for static table in "table layout". Only the column headings are shown.

**Comment by engram-design** [comment]
@richhayler Sorry about that issue, please refer to the [0.4.4 release](https://github.com/engram-design/SuperTable/releases/tag/0.4.4) where this is fixed. Sorry again!

**Comment by richhayler** [comment]
All good. I love this plugin - so awesome to have more control over my field layouts.

**Comment by engram-design** [comment]
Great! Any suggestions on how we can make it better let us know :smiley:

**Comment by richhayler** [comment]
Here's a screenshot of a little extra CSS I added to the plugin to hide the table and row styling. Happy to share if you would like me to send this to you. http://hayler.com/supertable.png

**Comment by engram-design** [comment]
@richhayler Seems pretty cool! Happy to stick with the Craft-esque style at the moment, but I do plan on giving a lot more control in how things are laid out. Thanks for sharing though!
