### ISSUE TITLE
Adding a new locale when using with a Craft Commerce product type results in a stuck background task

### ISSUE THREAD

**Issue by dommmel** [engram-design/SuperTable#58]
Hi there. Thanks for the excellent plugin. Can't live without it.

I think I ran into an issue when using a superTable for a Craft Commerce product type and then adding a new locale.

I end up with commerce background task "Resaving products" that comes with the following PHP error

    PHP Fatal error:  Call to a member function getContentTable() on null in /var/www/craft/plugins/supertable/fieldtypes/SuperTableFieldType.php on line 371

**Comment by engram-design** [comment]
Fixed in your PR - thanks again!
