### ISSUE TITLE
Issue with Craft\ElementCriteriaModel

### ISSUE THREAD

**Issue by kerns** [engram-design/SuperTable#61]
I keep hitting a wall with this... to the point I know I'm either missing something very obvious, or have stumbled on to a bug. Running the latest version of Craft as of this date (2.6.2776). Running Super Table 0.4.6

Am I missing something obvious?

```
{% if block.videoEmbed | length %}
    {% for row in block.videoEmbed %}
        {{ block.videoEmbed.videoID }}
    {% endfor %}
{% endif %}
```
---
![screenshot 2016-03-21 16 50 51](https://cloud.githubusercontent.com/assets/20254/13919168/4b86091e-ef85-11e5-82de-f43f9f204963.png)
---
![screenshot 2016-03-21 16 51 51](https://cloud.githubusercontent.com/assets/20254/13919171/547217fc-ef85-11e5-88fd-92f74b93f37f.png)

**Comment by engram-design** [comment]
I believe you're wanting to do `{{ row.videoID }}` as opposed to `{{ block.videoEmbed.videoID }}`

**Comment by kerns** [comment]
I knew this was going to be embarrassing. Thanks – sorry I had just adopted some of the new code for static fields elsewhere in my code – removing the for row loop... and well... no excuse. Thanks!

**Comment by engram-design** [comment]
No worries at all - thought that may have been the case! Cheers :smiley:
