### ISSUE TITLE
Documentation With Templating Examples

### ISSUE THREAD

**Issue by aenrii** [engram-design/SuperTable#62]
Hey Josh, 

Not really an issue per se, but any chance you could put together a quick couple of examples of templating? Like for example how to fetch content from a matrix field (and blocks / block types) within a SuperTable row. Any documentation really. :)

**Comment by engram-design** [comment]
Hey there - no formal documentation yet, just bits and pieces I've kept in the Wiki - mostly for plugin development. How does this page look for a start?

https://github.com/engram-design/SuperTable/wiki/Templating-examples

**Comment by aenrii** [comment]
Excellent, thanks so much for this!

I think the issue I was having was that I had a SuperTable containing a Matrix field as well as a Matrix field outside of the SuperTable that had the same naming for the same blocks inside them. Going to double check when I get a sec.

**Comment by engram-design** [comment]
No problems - feel free to post a screenshot of your field settings if you need further assistance. It can get particularly tricky when you have a Matrix-SuperTable-Matrix setup!
