### ISSUE TITLE
Can't save anymore

### ISSUE THREAD

**Issue by nmsdvid** [engram-design/SuperTable#63]
I just came across a problem when I can't save new entries anymore, its seems that super table has some limit problem. Does someone came across this problem already ? Or know a solution ?

**Comment by engram-design** [comment]
This can be a common problem - have you had a look at the [Troubleshooting](https://github.com/engram-design/SuperTable/#troubleshooting) section?

**Comment by nmsdvid** [comment]
Ah sorry I totally skipped the Troubleshooting section, it worked with the php.ini.
