### ISSUE TITLE
SuperTable > Matrix Field Config Modal = Slow UI

### ISSUE THREAD

**Issue by aenrii** [engram-design/SuperTable#64]
I'm getting super sluggish responsiveness in the UI when I have multiple matrix blocks with multiple asset fields, LJ Dynamic Fields, and some other misc fields in them (even key input is slow—hit a key and it takes a second or two to get typed). Not sure if this is primarily a Craft issue.

**Comment by engram-design** [comment]
I'm guessing this isn't the case when editing any other Matrix field on your site?

**Comment by aenrii** [comment]
That's correct. Smooth sailing. 

Absolutely love this plugin btw. Enabling the feature I was missing most (nesting matrix fields). Excellent work.

**Comment by mikestecker** [comment]
It's more than just slow for me. I was happy when I saw this issue because it means I'm not alone. For me, I'm seeing delays of more than a minute in between interactions when the matrix modal is open. Not sure what's going on. Oh, and it kicks my fans into high gear and pushes Safari's CPU usage high.

**Comment by m9dfukc** [comment]
Hey, I'm also suffering from this using latest versions of Craft (v. 2.6.2780) and SuperTable (v. 0.4.6). I'm using Matrix fields with several SuperTable fields. Especially scrolling get's very sluggish the more content/fields I add. Tried booth Safari (v. 9.1) and Chrome (v. beta 51), Safari seems more worse that Chrome but booth are very slow - very unpleased UI experience :( 

... I'll investigate further!

p.s.: Definitely related to Matrix <--> SuberTable, other parts of the site (not using these in conjunction) don't show this behaviour.

**Comment by dennisfrank** [comment]
Same here: Matrix in SuperTable in Matrix. The inner Matrix seems to make the front end extremely unresponsive: bumpy scrolling, text input lag an adding an item to the inner Matrix took about 20 to 30 seconds. 

Memory usage of the corresponding Chrome tab goes up quite high too. 

Testet in newest Chrome and Firefox on OS X.

**Comment by engram-design** [comment]
I can only seem to replicate this in Safari - Chrome and Firefox seem fine. I've had a really good crack at trying to fix this, but haven't found the issue so far. It does look to be related to the modal window, which will hopefully soon be replaced with a new settings interface.

**Comment by engram-design** [comment]
The modal for the field settings is no more as of [1.0.0](https://github.com/engram-design/SuperTable/releases/tag/1.0.0), so this should be resolved.

Please re-open if this is not the case, but my testing shows things aren't sluggish anymore.
