### ISSUE TITLE
Broken in quick entry forms

### ISSUE THREAD

**Issue by leevigraham** [engram-design/SuperTable#67]
SuperTable is broken in the quick entry form overlays.

I'm running:

- Craft CMS 2.6.2780
- Super Table 0.4.6

<img width="627" alt="screen shot 2016-04-16 at 7 47 19 pm" src="https://cloud.githubusercontent.com/assets/25124/14580273/176b5012-040c-11e6-8833-2e816e9bcfde.png">
<img width="1052" alt="screen shot 2016-04-16 at 7 46 58 pm" src="https://cloud.githubusercontent.com/assets/25124/14580274/1790984a-040c-11e6-922e-06630d3d7037.png">
<img width="652" alt="screen shot 2016-04-16 at 7 46 48 pm" src="https://cloud.githubusercontent.com/assets/25124/14580275/17964664-040c-11e6-9e78-a0689161e4ed.png">

**Comment by engram-design** [comment]
This should be fixed in the latest master - let me know if you have any further issues!
