### ISSUE TITLE
SuperTable_BlockModel#getType error when saving entity with supertable

### ISSUE THREAD

**Issue by altmind** [engram-design/SuperTable#68]
Getting this error when saving an entity having supertable field. Using supertable master and latest craft from 2.6 branch.
```
SuperTable_BlockModel and its behaviors do not have a method or closure named "getType".
```
Probably introduced with the latest commit - https://github.com/engram-design/SuperTable/commit/703586f61539e43625e0ec7e2306a8024bb8b98b

**Comment by engram-design** [comment]
@altmind Yep, have now reverted that commit, so all good! Thanks for the report 👍
