### ISSUE TITLE
Programatically saving a Static SuperTable

### ISSUE THREAD

**Issue by josephbergdoll** [engram-design/SuperTable#69]
Hello — I'm trying to save some data via my plugin to a SuperTable field. It is a static field, and following the [Wiki method](https://github.com/engram-design/SuperTable/wiki/Programatically-saving-a-Super-Table-field-with-content) doesn't seem to work for this.

**Comment by engram-design** [comment]
Hey there - I've just updated the example for you, which should hopefully help out - https://github.com/engram-design/SuperTable/wiki/Programatically-saving-a-Super-Table-field-with-content

**Comment by josephbergdoll** [comment]
Hmm – I went ahead and made changes but it's still not having any effect…

I'm hooking into updating my "thumbnail" field with a programmatically created asset. The asset is being saved but the relationship is not, nor is the crop position.

`$response = craft()->assets->insertFileByLocalPath($tmpfname, $slug . '.jpg', '11');
    $fileIds = array();
    if ($response->isSuccess()) {
      $fileId = $response->getDataItem('fileId');
      $fileIds[] = $fileId;
      error_log(print_r($fileIds, true));
      $field = craft()->fields->getFieldByHandle('thumbnail');
      $blockTypes = craft()->superTable->getBlockTypesByFieldId($field->id);
      $blockType = $blockTypes[0];

      $superTableData = array();
      $supderTableData['new1'] = array(
        'type' => $blockType->id,
        'enabled' => true,
        'fields' => array(
          'image' => $fileIds,
          'cropPosition' => 'left'
        )
      );

      $entry->setContentFromPost(array('thumbnail' => $superTableData));
      if (craft()->elements->saveElement($entry)) {
        error_log('saved element');
        return true;
      }
      else {
        Craft::dd($entry->getAllErrors);
      }
    }`

**Comment by engram-design** [comment]
Is `cropPosition` just a plain text field, or a Position Select field? What does `error_log(print_r($fileIds, true));` print out? Are there any errors shown through `Craft::dd($entry->getAllErrors);`?

**Comment by josephbergdoll** [comment]
`cropPosition` is a select dropdown with options `center` (default), `left`, and `right`. The single file ID gathered from the `$response` is printed upon the log command, and the element is always successfully saved. Just not updating the SuperTable field.

**Comment by engram-design** [comment]
Should you be using `craft()->entries->saveEntry($entry);` as opposed to `craft()->elements->saveElement($entry)`? Haven't tested all that, but will now.

**Comment by josephbergdoll** [comment]
Doesn't matter as both do the same thing.

**Comment by engram-design** [comment]
I'm pretty sure they're not the same thing - Have a look at `app/services/EntriesService.php` and `saveEntry()`. My testing shows that `craft()->elements->saveElement($entry)` doesn't work, as you're just creating the element for the entry, not the entry plus the element if that makes sense?

**Comment by josephbergdoll** [comment]
Not to worry — it's working completely great in multiple instances in my app. Thanks for the help and all the best!
