### ISSUE TITLE
Get elements by SuperTable row criteria

### ISSUE THREAD

**Issue by carlcs** [engram-design/SuperTable#7]
I think it would be really great if it was possible to query for elements, which meet certain SuperTable criteria.

Example:
Imagine an "Events" channel / entry type `events` with a "Dates" SuperTable field `dates` attached to it. There's two columns in `dates`, a Date/Time field `date` and a Text field `description`. Now you'd like to query for entries with `dates` rows, which fulfill the following criteria

```
 date('and', '>= 2015-06-01', '< ' ~ '2015-06-01'|date_modify('+1 day'))
```

to get "Events" entries with "Dates" for a set day only.

[Low Blocks](https://github.com/low/lowblocks) plugin solves this for Matrix fields (indirectly via Matrix blocks and it's `owner` property). And I bet, that something like this integrated into SuperTable makes the plugin even more powerful.

**Comment by engram-design** [comment]
You can sort of do this at the moment using `craft.superTable.blocks()`, and passing in a criteria model. Dates are another matter, which I might look into extending.

**Comment by codyjames** [comment]
We're looking to do exactly this. Did either of you ever get something like this working?
