### ISSUE TITLE
Saving Matrix - SuperTable fields results in a save time period as-long-as Apache2 timeout value

### ISSUE THREAD

**Issue by roberttolton** [engram-design/SuperTable#71]
Hi,

Craft CMS 2.6.2783
Super Table 0.4.6

Following the README, and this thread:
http://craftcms.stackexchange.com/questions/2765/matrix-field-input-error-from-within-the-control-panel/2777#2777

I have changed the values in my php.ini file to the below:
max_input_vars = 3000
post_max_size = 20M

I have confirmed these values are being reported by Craft using the phpinfo page.

I'm not saving anything complex, two instances of a block type using SuperTable as one of the fields in each with a few rows added. The page just never loads, but the data seems to make it to the database as the front-end page is updated when refreshed.

I also switched out MySQL 5.7 for MariaDB 10.1 to reduce memory footprint, and it's not running out of memory.

I'm developing locally, on a Vagrant VirtualBox with Ubuntu 14.04, PHP 5.6 and Apache2

**Comment by fuelintegrated** [comment]
So I let it run for as long as it wanted, and it eventually succeeded to loading the entries page again, with a console log of:
```
[Log] Time:   300.73648s (news, line 495)

[Log] Memory: 8,208Kb (news, line 496)

[Log] Total Queries: 26 (news, line 497)
```

A time of 300 seconds is surprising given the php.ini states:
```
max_execution_time = 30
```

Or am I misinterpreting what Craft reports?

**Comment by fuelintegrated** [comment]
So I've replicated this on another install of Craft CMS, with zero content, no other plugins other than SuperTable.

The initial creation of an entry with a Matrix / SuperTable mix works, and subsequent editing of that entry **without** touching the Matrix / SuperTable fields works fine, but as soon as you make a change to the Matrix / SuperTable fields, be it re-order or simply adding content, when I hit save I have to wait 300 seconds for the page to finish loading.

Considering this is running on a pretty common LAMP stack, I'm not sure why this issue hasn't been reported before, and I can't make the installation anymore bare-bones than it is..!

**Comment by fuelintegrated** [comment]
Further testing, I dropped my Apache2 timeout down from the default 300, to 10, and what do you know, the SuperTable entries started successfully finishing their saves after _exactly_ 10 seconds..!

So my question would be, what is CraftCMS / SuperTable trying to do that causes the the process to hang as long as the apache timeout?

My CrafCMS is in Dev Mode and I see no errors, wondering if I should start poking it with debug tools..

**Comment by fuelintegrated** [comment]
Captured a video to try and show what's happening:
http://cloud.roberttolton.com/3n3g2s1Y0929

I left the apache timeout at 10 seconds, I didn't think recording the video for the default 300 seconds would be particularly fun..!

**Comment by engram-design** [comment]
Hey - thanks for putting that video together. Can't say I've ever come across that issue, and particularly interesting to see that its not consistent... I'll start testing locally to see if I can replicate.

**Comment by engram-design** [comment]
Did we ever get to the bottom of this one? My memory is a little hazy, but I think we started to see this issue for a normal Matrix field right?

**Comment by roberttolton** [comment]
It was a weird thing that boiled down to accessing the local Craft install via anything _other_ than `localhost`, as that led to the timeout. Put it down to some weird Ubuntu / Apache issue with localhost.

**Comment by engram-design** [comment]
Ah, I think I recall that. Closing for now, but good reference if it pops up again...

**Comment by xposedbones** [comment]
I'm having the same issue, except that it happens on both my local machine and staging/prod environment on Heroku so `localhost` isn't the issue. I'm using craft 3 with a matrix containing about 20 supertable field and it's taking exactly the same time as apache's timeout. On local, it just works after 5 minutes, but on heroku it crashes the server. Everything used to work great on Craft 2

**Comment by engram-design** [comment]
@xposedbones This _might_ be related to Project Config - https://github.com/craftcms/cms/issues/4459
