### ISSUE TITLE
When deleting an entry with a Super Table field SuperTable_Block elements are not deleted

### ISSUE THREAD

**Issue by tjdraper** [engram-design/SuperTable#72]
I discovered this because a field type I am working on needs to be aware when any element that contains my field is deleted so it can clean up after itself. elements.onBeforeDeleteElements was not being fired so further investigation lead me to find that Super Table is not deleting it's elements if an entry (or presumably anything else with a Super Table field) is deleted.

Compare this to Matrix behavior where when any element that has a Matrix field is deleted, the Matrix Elements are deleted and elements.onBeforeDeleteElements is fired so I can also clean up after my field type in the Matrix.

So, SuperTable should probably clean up after itself like Matrix :)

**Comment by engram-design** [comment]
@tjdraper Certainly agree with you there, and my testing shows that it cleans up properly after itself, just like Matrix. I'd be interested to see if thats the same for you. I tested with a few elements (Entries, Categories, Users) and assigned a Matrix and Super Table field, added content, checked their blocks were in the corresponding tables, deleted the element, and verified the blocks no longer exist.

However, one scenario I've found - which is also the case for Matrix - is where Block elements can get orphaned. If you add your fields to an entry, save content - but then remove those fields from the entry, and save again, it'll keep Block elements there. I might look into this scenario, but just wanted to clarify.

**Comment by tjdraper** [comment]
I'm really sorry I'm just now coming back to this. I had other projects totally side track me from the project where this was an issue. But I'm committed to getting this project out the door in the next week or so.

So here's the scenario. My field type has its own table and creates items there for each field.

I am watching for element deletion to clean up after my field type like so:

```
craft()->on('elements.onBeforeDeleteElements', function (Event $event) {
	// ...do stuff to delete rows in my table owned by the element being deleted
});
```

This works perfectly when deleting rows from a SuperTable field containing my field type. However, where things get tripped up is if I delete an entry (from the entry listing page, select entry, use the gear dropdown and select delete). `onBeforeDeleteElements` is not fired for the SuperTable row.

I have tested with Matrix and deleting an entry does fire the `onBeforeDeleteElements` event for any matrix rows within that entry.

Personally, I'm a little more visual so I made a video showing exactly what's happening. I hope that's helpful: https://vimeo.com/209932709/db0579c79a

**Comment by engram-design** [comment]
@tjdraper This is a tricky one, because Craft's native `deleteElementById` function (in ElementsService.php) has a special case for Matrix. Check out line 1990 if you're interested.

I'll have to do some thinking about how we can achieve this. At the very least, you could roll your own solution by listening to the `entries.onDeleteEntry`, checking for a Super Table field and deleting.

**Comment by engram-design** [comment]
Give the [latest master](https://github.com/engram-design/SuperTable/archive/master.zip) a crack and see how that goes for you! Super Table itself will now listen to `elements.onBeforeDeleteElements` and cleanup blocks owned by that element.

**Comment by tjdraper** [comment]
Perfect! That works exactly as expected.
