### ISSUE TITLE
Relating an entry from any Section

### ISSUE THREAD

**Issue by richardwiggins** [engram-design/SuperTable#73]
I've been using Super Table to great affect within various Matrix Blocks, and I've have already used it with related entries where I already know the section, but can't figure out how to get it working when the user can select from entries across multiple sections.

This is basically what I need to update:

`{% set link = craft.entries.section(?????).relatedTo(row) %}`

**Comment by richardwiggins** [comment]
Actually, ignore me. I've just realised I can leave the section blank.

**Comment by engram-design** [comment]
Glad you got it sorted! 😃
