### ISSUE TITLE
Select Dropdown drop-down values are not shown on drafts

### ISSUE THREAD

**Issue by kara-todd** [engram-design/SuperTable#77]
It seems like the checkbox values stored in the craft_entrydrafts table are not being correctly displayed. To replicate... create an entry with a select drop-down inside a supertable field and then 'save as draft.' Text values will display correctly, but the select drop-down will default to the first option.

I tried to poke into this but wasn't sure where the draft data is being called from.

**Comment by engram-design** [comment]
@kara-todd Thanks for submitting this, I've traced the issue back to a conditional within Craft itself that has a case for Matrix field handling for this situation, which needs to happen similarly for a Super Table field. Just trying to work through the best way to implement this as its a core-specific function. Thanks for your patience!

**Comment by kara-todd** [comment]
@engram-design No problem! Thank you for looking into it. :)

**Comment by engram-design** [comment]
Just another quick update on this, there'll be a change in the next release of Craft that will fix this, so be on the lookout!

**Comment by engram-design** [comment]
Fixed in the [0.4.7 release](https://github.com/engram-design/SuperTable/releases/tag/0.4.7). Please also ensure you update to the latest [Craft 2.6.2795](https://craftcms.com/changelog#build2795).

Big shout-out to @brandonkelly for fixing this!
