### ISSUE TITLE
Default upload locations with variables not working when used in this combo: Matrix > Super Table > Matrix > Asset field

### ISSUE THREAD

**Issue by zackspear** [engram-design/SuperTable#78]
SuperTable has been a life saver for the current project that I'm working on. However when trying to use variables in the Default upload location setting for an asset field while using Matrix with a Super Table with a Matrix field (so nested Matrix essentially) the upload fails because Craft can't find the path. So I'm not able to upload assets to the asset field.

I tried a few different variations of the variables
```
{owner.section.name | kebab}/{owner.id}/page-builder # Tried the kebab filter without the spaces as well
{owner.owner.section.name | kebab}/{owner.owner.id}/page-builder # for the hell of it
```

Here's the error I get
![screenshot 2016-06-30 13 08 28](https://cloud.githubusercontent.com/assets/2531682/16502569/ece2d520-3ec3-11e6-8ce4-426c82c69a3e.jpg)

```
Could not resolve the subpath “{owner.section.name | kebab}/{owner.id}/page-builder”.
```

with the response being
```html
<h1>Craft\InvalidSubpathException</h1>
<p>Could not resolve the subpath “{owner.section.name | kebab}/{owner.id}/page-builder”. (/var/www/mount-madonna-center/core/app/fieldtypes/AssetsFieldType.php:546)</p><pre>#0 /var/www/mount-madonna-center/core/app/fieldtypes/AssetsFieldType.php(694): Craft\AssetsFieldType->_resolveSourcePathToFolderId('2', '{owner.section....', true)
#1 /var/www/mount-madonna-center/core/app/fieldtypes/AssetsFieldType.php(415): Craft\AssetsFieldType->_determineUploadFolderId(Object(Craft\Model), true)
#2 /var/www/mount-madonna-center/core/app/controllers/AssetsController.php(86): Craft\AssetsFieldType->resolveSourcePath()
#3 /var/www/mount-madonna-center/core/app/framework/web/actions/CInlineAction.php(49): Craft\AssetsController->actionExpressUpload()
#4 /var/www/mount-madonna-center/core/app/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#5 /var/www/mount-madonna-center/core/app/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#6 /var/www/mount-madonna-center/core/app/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/mount-madonna-center/core/app/framework/web/CWebApplication.php(282): CController->run('expressUpload')
#8 /var/www/mount-madonna-center/core/app/etc/web/WebApp.php(815): CWebApplication->runController('assets/expressU...')
#9 /var/www/mount-madonna-center/core/app/etc/web/WebApp.php(285): Craft\WebApp->_processActionRequest()
#10 /var/www/mount-madonna-center/core/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#11 /var/www/mount-madonna-center/core/app/index.php(62): CApplication->run()
#12 /var/www/mount-madonna-center/www/index.php(23): require_once('/var/www/mount-...')
#13 {main}</pre>
```

This happens regardless of restricting the upload path to a single folder or not. And it happens when dragging and dropping the asset to the field as well as clicking into the field to upload (when restricting to single folder).

I'm using S3 if it makes a difference here.

If any of this needs more clarification or if you need more info, just let me know.

For now I'm just going to use a static Default upload location `page-builder` (which does work) for now as this isn't a deal breaker. It's just nice to keep the assets organized by their section and entry instead of just in a single folder.

Cheers

**Comment by zackspear** [comment]
Happening for me with Matrix > Super Table > Asset as well. So not just limited to what I mentioned above.

**Comment by engram-design** [comment]
I'm currently using `{owner.owner.slug}` for a Matrix > Super Table, and that seems to pick it up okay! Can you let me know if that works for you? Happy to test a Matrix > Super Table > Matrix configuration too...

**Comment by engram-design** [comment]
Just tested and confirmed `{owner.owner.owner.section.name | kebab}/{owner.owner.owner.id}/page-builder` works - albeit a little lengthly! Closing for now, but reopen if you have further issues.
