### ISSUE TITLE
Row header width not adjustable or automatic

### ISSUE THREAD

**Issue by ChaseGiunta** [engram-design/SuperTable#79]
In the sample image below (from the readme), it seems to show row headers have their width set to auto, or they're adjustable by us to fit the content inside.
![image](https://raw.githubusercontent.com/engram-design/SuperTable/master/screenshots/static.png)

This doesn't seem to be the case anymore.
![image](https://cloud.githubusercontent.com/assets/1377169/17604919/8e0c72c8-5fdd-11e6-8ec8-5e477768744c.png)

**Comment by engram-design** [comment]
Yeah, it was the case a few versions ago that this was automatic - which was great! I had to switch this to use `table-layout: fixed;`, as there were issues being caused when a Super Table field was being placed inside a Matrix field and overflow (see https://github.com/engram-design/SuperTable/issues/24 - where we've actually had this convo before 😃 )

I've always wanted to fix this, so may have another crack at it.

**Comment by ChaseGiunta** [comment]
I didn't spend _too much_ time on it, but getting an automatic width in CSS didn't seem like a simple thing to do (if by some hacky way it's actually possible). 

Looks like the width is being set explicitly to 60px on those `<td>`s. Would it be possible to loop through all the set column width values, find the largest value, and set the width for all `<td>`s to that value when set to "Row" field layout?

**Comment by slimiles** [comment]
I would really appreciate the idea of @ChaseGiunta :)

**Comment by engram-design** [comment]
Fixed in [1.0.0](https://github.com/engram-design/SuperTable/releases/tag/1.0.0)
