### ISSUE TITLE
Calling a field "content" with no validation

### ISSUE THREAD

**Issue by johnwbaxter** [engram-design/SuperTable#8]
Hey Guys!

As "content" is a reserved word, you shouldn't be able to give a supertable field the name "content". But Supertable lets you do it without passing it through the validation.

Thanks!

John

**Comment by carlcs** [comment]
Can't confirm this. I just tried to save a SuperTable field with a field handle "content" and it didn't pass validation.

**Comment by engram-design** [comment]
@johnwbaxter @carlcs Yep, there's work to be done on validation - I just haven't done it yet due to figuring out the best way to validate the inner fields! It's on the roadmap to be sorted very soon.

**Comment by johnwbaxter** [comment]
@engram-design No worries, just letting you know in case you didn't!! :+1:

**Comment by andyharris** [comment]
Related to this, I just created a ST field with a handle of 'link' - it wouldn't let me save the field (save button just refreshed the screen) but also returned no error message (changing link to linkUrl obviously fixed it.)

**Comment by engram-design** [comment]
@johnwbaxter @carlcs @andyharris Thanks for your feedback, this has been added as of 0.2.9.
