### ISSUE TITLE
Front End saveEntry form with Assets Field

### ISSUE THREAD

**Issue by iamtompickering** [engram-design/SuperTable#80]
I'm using your example front end form to add to super tables and it works an absolute treat, but I'm trying to get an assets field to work with it and can't seem to crack it - keep getting errors. I think it's more to do with the existing files in the assets field. Currently in the existing parameter block for loop I'm am doing:

`<input type="hidden" name="fields[{{ fieldHandle }}][{{ block.id }}][fields][listItemIcon][]" value="{{ block.listItemIcon.first().url() }}">`

Have a feeling the value isn't what I should be passing...?

**Comment by engram-design** [comment]
What errors are you getting out of interest? And you'll need to pass the ID of the asset, so maybe give this a try:

`<input type="hidden" name="fields[{{ fieldHandle }}][{{ block.id }}][fields][listItemIcon][]" value="{{ block.listItemIcon.first.id }}">`

I assume `listItemIcon` is the handle for your Asset field as well

**Comment by engram-design** [comment]
Closing - tested and working from my end, reopen if you still have issues.
