### ISSUE TITLE
Upgrade to 0.4.8 table name exceeds 64 characters

### ISSUE THREAD

**Issue by dave-agilepixel** [engram-design/SuperTable#83]
I'm getting an error 

"Identifier name 'craft_supertablecontent_46_sectionbuttons_elementId_locale_unq_idx' is too long"
It looks like it's this file m150901_144609_superTable_fixForContentTables.php which is running the update and creating these tables.

It seems that in MySQL there's a limit of 64 characters for table names, so this fails as it's too long, is there a work around or fix for this?

Thanks

Dave

**Comment by engram-design** [comment]
Have you had a look at https://github.com/engram-design/SuperTable/wiki/Release-Notes#updating-from-034-to-035 which describes this issue?

To fix this error, you'll have to manually update your table name from `craft_supertablecontent_sectionbuttons` to `craft_supertablecontent_46_sectionbuttons`.

**Comment by dave-agilepixel** [comment]
Wouldn't  it be a better solution to not require users to manually update the table names, ie rather than have a prefix of supertablecontent maybe change it to stc or something equally short, which would reduce the change of this issue?

**Comment by engram-design** [comment]
Yes, of course - but I'm hesitant to make this change _again_ in case we come across this same issue again. Say a user has a field with such a long name, that even changing `supertablecontent` to `stc` won't make a difference.

Having said that, I've been pondering this for some time, and might even make it to the next release. Will just spend some time testing this.

**Comment by dave-agilepixel** [comment]
Awesome thanks for your consideration :)

**Comment by engram-design** [comment]
No problem - you'll still likely need to manually update the table name for now. Bare in mind, this is a once-off issue for upgrading.
