### ISSUE TITLE
Get values during register-validation

### ISSUE THREAD

**Issue by akuales** [engram-design/SuperTable#84]
I am using supertable to populate a user during registration. 
It works perfectly fine to store the data, as long as there is no error during the process.
As soon as I get an error (eg. duplicated username) I don't have access to the information of the supertable fields anymore, when the other registration-errors are shown => `{{ account.email }}` gets displayed in `<input />`
I send: `fields[{{fieldHandle}}][new1][fields][city]` which works perfectly fine.
Is there any way to access those supertable fields? I do see them, when I `dump(account)` but I cannot access them.

**Comment by engram-design** [comment]
I'm afraid I'd need to see what you're implementing to help more. I'm a little confused about how you use Super Table to populate a user during registration. Are you able to share a gist or snippets of the code?

**Comment by akuales** [comment]
Thank you very much for your quick reply.
I've created a simple gist showing my register form (until line 40 it's just a copy of crafts register-template).
[https://gist.github.com/akuales/f65e43df167d886d8380650990b0f9fc](url)
After that its a customized version of: [https://github.com/engram-design/SuperTable/wiki/Updating-a-Super-Table-field-from-a-front-end-form](url)

If I fill out the form, and there is no error within the values (username, email, password), every field (also security) gets populated perfectly fine in the backend.
Whereas, if I type a username that is already taken, my register page refreshes but crashes as it can't find `{{account.security.new1.fields.singer}}` (line 51) even though `account.security` is defined.
If I delete line 41 to line 58 (all the supertable fields), the page refreshes perfectly fine and the taken-username-error gets displayed.
As said, I can `dump(account.security)` successfully and I see the values from the supertable-fields - but I was never able to access each of them. 

Thanks alot for your support!

**Comment by engram-design** [comment]
If you'd like to give the following a go:
```
<label for="favSinger"><span>fav. singer</span></label>
<input type="text" name="fields[{{fieldHandle}}][new1][fields][singer]" value="{% if account is defined and account.security|length %}{{account.security.singer}}{% endif %}" />

<label for="favActor"><span>fav. actor</span></label>
<input type="text" name="fields[{{fieldHandle}}][new1][fields][actor]" value="{% if account is defined and account.security|length %}{{account.security.actor}}{% endif %}" />
            
<label for="favFood"><span>fav. food</span></label>
<input type="text" name="fields[{{fieldHandle}}][new1][fields][food]" value="{% if account is defined and account.security|length %}{{account.security.food}}{% endif %}" />
```

**Comment by akuales** [comment]
Thanks for your reply. 
By now we devided to go for an ajax approach - so no need to get the input-data back from the server for error-handling.
I will close this issue for now - will test your solution on the next project.
Thank alot.
