### ISSUE TITLE
Can't add new options to dropdown field within SuperTable 1.0.1

### ISSUE THREAD

**Issue by mach1media** [engram-design/SuperTable#85]
<img width="891" alt="screenshot 2016-08-30 17 19 46" src="https://cloud.githubusercontent.com/assets/740538/18109335/41e24550-6ed6-11e6-9dc2-7f54ff2142cb.png">

**Comment by engram-design** [comment]
Any JS errors in your console?

**Comment by mach1media** [comment]
No JS errors (or logs) reported in console. Tested in Chrome and Safari on Mac.

**Comment by engram-design** [comment]
Have you tried clearing your caches through Settings > Clear Cache? This isn't inside a Matrix field is it - just a plain Super Table field?

**Comment by mach1media** [comment]
Cleared all caches but no change in behavior. This is a plain SuperTable field on its own, not inside Matrix.

**Comment by engram-design** [comment]
I imagine this field was created in pre-1.0? This also happens for any new Super Table fields you create now I suppose? Sorry for the 20 questions, just struggling to reproduce on my end.

**Comment by mach1media** [comment]
No worries! Yes, the field in question was originally created before upgrading to 1.0.1. The [+ Add an option] button works perfectly when creating a NEW SuperTable 1.0 field and adding a dropdown field within it. The problem appears to be isolated to updating an existing SuperTable field which was created pre-1.0.

**Comment by engram-design** [comment]
Well, I've just tested creating a bunch of Super Table fields, with different inner-fields using pre-1.0, updating to 1.0, and then tried to configure field settings again, and all has worked fine. One of the fields I tested was a collection of dropdown fields. I did certainly have to clear the caches through the CP settings after each update however.

So thats pretty interesting - are you able to save the pre-1.0 Super Table field (without any changes), and then try to edit it again?

**Comment by mach1media** [comment]
Hey Josh, thanks again for continuing to look into this. Yes, I can save the pre-1.0 Super Table field without any changes, no Craft errors/exceptions are thrown. But the problem still persists with not being able to add new options to the dropdown field within the Super Table field that was upgraded to 1.0. Very strange indeed that you aren't replicate the issue. I'll try clearing the caches again to see if that helps this time.

**Comment by mach1media** [comment]
Not sure if this has any bearing on the issue, but this Super Table field is assigned to a Global field group.

**Comment by engram-design** [comment]
It shouldn't have anything to do with what group its assigned to. My only other thought it to completed remove the `supertable` plugin folder, download the latest 1.0.1 release again, clear caches, and try again. You may also need to remove your `craft/storage/runtime` folder.

**Comment by engram-design** [comment]
Closing for now, as unable to replicate the issue - no matter how hard I try!

**Comment by mach1media** [comment]
Thanks for trying Josh. Thankfully the fields in question in my project were pretty much set before this issue arose, so this is certainly not a show-stopper. Really appreciate this plugin, I’ve found myself using Super Table on just about every Craft build these days!

**Comment by engram-design** [comment]
No problem, and glad you like it! No one else has seemingly come across this yet, so fingers crossed...
