### ISSUE TITLE
Column width does not work for number fieldtype

### ISSUE THREAD

**Issue by migswd** [engram-design/SuperTable#86]
See here my 1st col is a text fieldtype : width does work fine (25%)
But 2nd col which is number fieldtype : width does not work for the field (the field does not extend to width)

![image](https://cloud.githubusercontent.com/assets/3531623/18117792/61259766-6f51-11e6-97f6-ce9b2caf8839.png)

**Comment by engram-design** [comment]
A number field's width is controlled by Craft. You'll notice when inspecting the element that it has a `size` attribute and missing `fullwidth` class like the Plain Text field does. This is the reason why it doesn't extend the full width of your column. Notably, the width column settings isn't meant to affect the inner fields, just the column.

I'm not doing to mess around with how core fields are presented, but you could very easily do this yourself using https://github.com/lindseydiloreto/craft-cpcss

**Comment by engram-design** [comment]
Closing - this is default Craft behaviour.
