### ISSUE TITLE
behaviors do not have a method or closure named "first".

### ISSUE THREAD

**Issue by dave-agilepixel** [engram-design/SuperTable#87]
Hello

We're upgrading from an older version of super-table, in our templates we had

{% if entry.superTableField.first.enable %}

we're now getting an error

Craft\SuperTable_BlockModel and its behaviors do not have a method or closure named "first".

I've found that I can just remove the "first" item and it doesn't error, however this causes issues as I have a lot of templates with first in, and I need them most of the time, but not all the time, so it's going to be a painful task to update to remove .first. if it needs to be removed?

Is there a way I can replicate the .first. method so I'm not loosing functionality?

Or is there a modification to the plugin that can be made to allow the "first" thing to work.

Thanks

Dave

**Comment by engram-design** [comment]
I assume you're referring to static option for Super Table fields? https://github.com/engram-design/SuperTable/wiki/Release-Notes#updating-from-042-to-043

**Comment by engram-design** [comment]
Closing - migration notes provided. Its a pain, but a find-replace shouldn't be _that_ time consuming. Please also advise if this isn't a Static field.
