### ISSUE TITLE
using a switch in a template for a supertable row

### ISSUE THREAD

**Issue by lexbi** [engram-design/SuperTable#88]
Could I use a switch on a loop of superTable rows instead of ifs within a for? I've attempted this already, but it appears that craft doesn't agree with `row.handle`

Here is my SuperTable field:
![image](https://cloud.githubusercontent.com/assets/2337910/18645244/598692d2-7ea4-11e6-8160-567079df6595.png)

Here is the markup I'm trying

```
{% for row in entry.pageContent %}
    {# lvl1 row #}
    {% switch row.handle %}

        {% case "contentWrapper" %}
            contentWrapper
        {% case "fullWidthImage" %}
            FullWidth

    {% endswitch %}

{% endfor %}
```

**Comment by engram-design** [comment]
Sure, give this a shot:
```
{% for row in entry.pageContent %}
    {% for fieldtype in row.getFieldLayout.fields %}
        {# lvl1 row #}
        {% switch fieldtype.field.handle %}
            {% case "contentWrapper" %}
                contentWrapper
            {% case "fullWidthImage" %}
                FullWidth
        {% endswitch %}
    {% endfor %}
{% endfor %}

```

**Comment by lexbi** [comment]
This actually doesn't work, loops over both fieldtypes for each "row", producing both to be output for every row. Have you any other ideas?

**Comment by engram-design** [comment]
Isn't being able to access the field's handle what you're after? Each `row` is a `SuperTable_BlockModel`, so there's no handle for that. Each block has a collection of fields, which you loop over.

```
{% for row in entry.pageContent %}
    {% for fieldtype in row.getFieldLayout.fields %}
        {% if fieldtype.field.handle == "contentWrapper" %}
            contentWrapper
        {% endif %}
    {% endfor %}
{% endfor %}
```

Maybe a bit of background on what you're trying to achieve?

**Comment by lexbi** [comment]
Yes sorry some context would help you I'm sure. Maybe this isn't really suitable for what I'm trying to achieve, trying to get it to behave like matrix in a matrix.

In your example above, it will get into the conditional every time, even if there isn't a single populated matrix or plain text field within it. 
So it will still get within that conditional, even if there is nothing populated like this:
![image](https://cloud.githubusercontent.com/assets/2337910/19020349/e9cc77be-889d-11e6-8328-83065c0f799d.png)

I would like a conditional which would only get in the conditional if one of the fields within a fieldtype is populated.

Would that be at all possible?

**Comment by engram-design** [comment]
My only other thought it so simply build an array in twig of your fields you want to output, outside of the actual HTML presentation. Am I right in thinking you want something like:

```
{% for row in entry.pageContent %}
    {% if row.hasContent() %}
        // A field in this Super Table row has content - show it
    {% endif %}
{% endfor %}
```

Sorry If I'm not fully understanding what your trying to do!
