### ISSUE TITLE
Error creating new field

### ISSUE THREAD

**Issue by billythekid** [engram-design/SuperTable#90]
New install of SuperTable, gives this error when hitting "new field":

Property "Craft\WebApp.superTable_matrix" is not defined.

Appears to be coming from /supertable/fieldtypes/SuperTableFieldType.php(22): Craft\SuperTableFieldType->_getFieldTypeInfoForConfigurator()

**Comment by billythekid** [comment]
installing release 1.0.1 "fixes" this. I guess the top tip is don't install dev versions. ;oP

**Comment by engram-design** [comment]
Not sure what that error was about. Were you installing the latest version from the master, or from a release?

**Comment by billythekid** [comment]
I was installing from master, iirc there was a file deleted between versions and presumed you were working on it. Installing latest release works fine for me.
