### ISSUE TITLE
CSS All Crazy After Update to 1.0

### ISSUE THREAD

**Issue by theskyfloor** [engram-design/SuperTable#91]
Here is my screenshot... not sure why it is happening!

![screen shot 2016-09-30 at 11 29 43 am](https://cloud.githubusercontent.com/assets/8887839/18999110/9325052c-8701-11e6-8b25-a4a7411a776a.png)

**Comment by engram-design** [comment]
While I would normally say to clear your template caches, I recon its those buttons causing the issue, let me test that out!

**Comment by engram-design** [comment]
Would you be able to give the latest master a go? Should be fixed.

**Comment by theskyfloor** [comment]
Yep! Fixed. Awesome!!
