### ISSUE TITLE
Feature Request: Collapse More Than 6 Block Types In A Nested Matrix 

### ISSUE THREAD

**Issue by theskyfloor** [engram-design/SuperTable#92]
It would be great if a certain threshold of blocks were reached in a nested matrix that the block selector could be turned into the dropdown instead of listing them all inline:

![screen shot 2016-09-30 at 11 32 46 am](https://cloud.githubusercontent.com/assets/8887839/18999222/0e3f4664-8702-11e6-945d-e00e6258d269.png)

**Comment by theskyfloor** [comment]
Wait I just realized this happens some of the time... So I guess the issue is that the above example isnt triggering the correct behavior.

**Comment by engram-design** [comment]
Would you be able to give the latest master a go? Should be fixed.

**Comment by theskyfloor** [comment]
Brilliant! Fixed.
