### ISSUE TITLE
Support for Feed Me 2.0

### ISSUE THREAD

**Issue by engram-design** [engram-design/SuperTable#93]

**Comment by nyehughes** [comment]
I have this issue too and wonder if you have an ETA for Feedme 2 support? (Or a work around in the meantime?) Thanks!

**Comment by dustinwalker** [comment]
Also curious if there is any update on this one. Looking forward to using version 2 in a migration. Thanks again for the great add-on!

**Comment by astuteo** [comment]
+1. Love the add-on. We use it frequently, but need to FeedMe 2 integration.

**Comment by engram-design** [comment]
Implemented in the [latest master](https://github.com/engram-design/SuperTable/archive/master.zip). Will roll into the next release after some peer testing, so go ahead when you can!
