### ISSUE TITLE
Min. Rows

### ISSUE THREAD

**Issue by carlcs** [engram-design/SuperTable#94]
It would be useful if it was possible to set a min. number of rows required per field.

Similar to the feature request for Matrix fields:
[Minimum number of rows in Matrix fields](https://craftcms.uservoice.com/forums/285221-feature-requests/suggestions/12253086-minimum-number-of-rows-in-matrix-fields)

**Comment by engram-design** [comment]
Added in the [latest master](https://github.com/engram-design/SuperTable/archive/master.zip).
