### ISSUE TITLE
Limit rows setting not being respected in the entry form

### ISSUE THREAD

**Issue by johnwbaxter** [engram-design/SuperTable#97]
Seem to have a bug with super table where if you have it set to 3 rows limit for example and then you remove one of those rows on the entry, the `add row` button stays greyed out so you can't add the row back in.

So to be clear:
Have it set to 3 rows.
Add those 3 rows into the entry.
Remove a row so you now only have 2.
Add Row button is greyed out so i cannot add a row to make it back up to 3.

FYI I have updated supertable to 1.0.2 (from 1.0.1) and it's not resolved the issue.

**Comment by engram-design** [comment]
This should be fixed in the [latest master](https://github.com/engram-design/SuperTable/archive/master.zip), and specifically [#391373e](https://github.com/engram-design/SuperTable/commit/391373e8dc7f8671919996669e758403770f154b) commit. Will roll into the next release.
